### ISSUE TITLE
Error In Readme WRT Deleting Serverless App

### ISSUE THREAD

**Issue by mashaalmemon** [twilio/twilio-video-app-react#101]
Hi There,

You have an error in your readme. It says that to delete the app you should run this command:

```
$ twilio rtc:apps:delete
```

But it appears the command is actually:

```
$ twilio rtc:apps:video:delete
```

I was persistent enough to figure out so my trial account wouldn't have credits wasted. Others may not be so persistent.

**Comment by aaalaniz** [comment]
Apologies for the typo. The issue was fixed in #102 

Thank you for filing the issue!
