### ISSUE TITLE
Switch camera isn't working on android browser

### ISSUE THREAD

**Issue by praveshkhatana** [twilio/twilio-video-app-react#103]
I am trying to integrate the Switch Camera feature which is working fine on IOS but not on the Android browser. 

On Android, It stops the video but does not restart it again. What I am doing wrong here

```
videoTrack.stop()
      getLocalVideoTrack(deviceID).then((track: LocalVideoTrack) => {
        if (localParticipant) {

          localParticipant.tracks.forEach(trackPublication => {

            localParticipant.unpublishTrack(trackPublication.track);
            localParticipant.emit('trackUnpublished', trackPublication);
          });
          localParticipant.publishTrack(track);
        }
        
      });
```

**Comment by timmydoza** [comment]
Thanks for the issue @praveshkhatana! Glad you could get this working on iOS.

Could you please provide a more complete complete code example? A link to a fork would be nice. It's difficult to figure out what the issue is without more context. I'd also be interested in how you got it working on iOS. 

Thanks!

**Comment by bhargavgoli** [comment]
Hey @timmydoza  Hope you doing great.

I was trying to modify the **userLocalVideoTrack** hook to flip the camera.

I have the same issue. Please find the below code.

`export function useLocalVideoTrack() {
    const [track, setTrack] = useState<LocalVideoTrack>();
    const camFacing: CameraFacing = CAMERA === 'Front' ? 'Back' : 'Front';
    const [cameraFacing, setCameraFacing] = useState<CameraFacing>(camFacing);

    const getLocalVideoTrack = useCallback(
        async () => {


            const permissions = await navigator.mediaDevices.getUserMedia({audio: true, video: true});
            const devices = await navigator.mediaDevices.enumerateDevices();
            const videoDevices = devices.filter(d => d.kind === 'videoinput');
            let videoPermissions = videoDevices.length > 1 && (CAMERA === 'Back' || CAMERA === null) ? {facingMode: 'user'} : {facingMode: 'environment'};


            if (CAMERA === null) {
                CAMERA = camFacing;
            } else {
                // alert(camFacing);
                const camF = CAMERA !== 'Front' ? 'Front' : 'Back';
                setCameraFacing(camF);
                CAMERA = camF;
            }

            return Video.createLocalVideoTrack({
                frameRate: 24,
                height: 480,
                width: 720,
                facingMode: videoPermissions.facingMode,
                name: 'camera'
            }).then(newTrack => {
                setTrack(newTrack);
                return newTrack;
            });
        },
        []
    );

    useEffect(() => {
        // We get a new local video track when the app loads.
        getLocalVideoTrack();
    }, [getLocalVideoTrack]);

    useEffect(() => {
        const handleStopped = () => setTrack(undefined);
        if (track) {
            track.on('stopped', handleStopped);
            return () => {
                track.off('stopped', handleStopped);
            };
        }
    }, [track]);

    return [track, getLocalVideoTrack, cameraFacing] as const;}
`
The above code is working perfect with IOS, but not on android phones.

**Comment by bhargavgoli** [comment]
Hey @timmydoza 

I got fixed.

Thanks.

**Comment by timmydoza** [comment]
@praveshkhatana @bhargavgoli 
We just added this feature to the master branch of our app. If you are interested, you can see changes in the PR here: https://github.com/twilio/twilio-video-app-react/pull/152
