### ISSUE TITLE
Deploy the Twilio React App without the Twilio serverless functions?

### ISSUE THREAD

**Issue by QasimQureshi** [twilio/twilio-video-app-react#107]
I want to use the Twilio react app as a starting point for a Redwood.js project that's hosted on Netlify.

Could I build and deploy the project to Netlify (where I wouldn't have access to the Twilio Serverless functions)

**Comment by timmydoza** [comment]
Thanks for the question @QasimQureshi!

Once you build your static assets with `npm run build`, you can then run `node server.js` to serve the application on port 8081 without Twilio Serverless Functions.

The server (https://github.com/twilio/twilio-video-app-react/blob/master/server.js) does these two things:
- It serves static assets from the `./build` folder
- It serves video access tokens from the `/token` endpoint. 

One thing to note, is that this server does not provide any kind of authentication or security. If you use it to serve the app on a public URL, then anyone can use the app and incur charges on your account. Use with caution.

If you'd like to implement your own solution, I'd suggest taking a look at the code inside server.js. You could use the same token minting logic in your own backend. 

Hope it helps!!

**Comment by QasimQureshi** [comment]
Thanks @timmydoza! 

I've got to put together a really simple demo, preferably without a backend.

I might actually just hardcode a token if that'll let me get by with a JAMstack serverless solution.

**Comment by timmydoza** [comment]
A hard-coded token would work, but it wouldn't allow multiple users to join a room at the same time. If you want multiple users in a room, you'd need multiple tokens (this is why we have a server).

It would be possible to have a token server as a JAMstack serverless function. Take a look at the serverless function that we use to deploy the app as a Twilio Serverless Function: https://github.com/twilio-labs/plugin-rtc/blob/master/src/video-token-server.js

Twilio Serverless Functions are similar to the serverless functions used by JAMstack. You would have to change a few things though (JAMstack doesn't use `Twilio.response()`, for instance). The server function I linked to could be a good starting point.

Also, if all you need is a really simple demo, you should consider deploying the app with Twilio Functions with our CLI tool.  Here's a short youtube video to help you get started: https://www.youtube.com/watch?v=pSASQcHrmPg

**Comment by mosesoak** [comment]
I've successfully published this sample app to an nginx server without any major issues. :tada:

- In the nginx config I path the doc root to the `build` dir:
```
    root /var/www/html/build;

    location /token {
        # can set to your host address. no trailing slash after /token in both places
        proxy_pass    http://localhost:8081/token;
    }
```
- synced the site files up (minus `node_modules` and a few other things)
- ssh'd into `/var/www/html`  and did `npm i` once, then `npm run server`

Works like a charm!
