### ISSUE TITLE
Question: Is there a way to pass the token via the URL to go directly into a room?

### ISSUE THREAD

**Issue by Ardenexal** [twilio/twilio-video-app-react#112]
In the Readme, it talks about creating a token but I'm not sure how to use the token to open the app straight into a room.

Is there a way I can do something like this?
`https://video-app-**-dev.twil.io?token=[token]`

**Comment by timmydoza** [comment]
Thanks for the question @Ardenexal!

There currently isn't a way to pass the token as a query parameter. It's a feature that we have not implemented. 

You could fork the repo and implement it yourself. A simple way to get it working is to put this code on line 46 of `src/components/VideoProvider/index.tsx`. 
```
  useEffect(() => {
    if (window.location.search.includes('?token=') && room.state !== 'connected' && !isConnecting) {
      const token = window.location.search.split('?token=')[1];
      connect(token);
    }
  }, [connect]);
```

You'll have to import `useEffect` at the top of the file. Here's a gist of the whole file: https://gist.github.com/timmydoza/2fa06a5e232332ed7bbd87f03b26f39e
