### ISSUE TITLE
Controls shift position on hover in Safari 12.1 on Mac

### ISSUE THREAD

**Issue by alexlavr** [twilio/twilio-video-app-react#113]
**Describe the bug**
Controls at the bottom of the screen (Mute Audio, Mute Video) shift left and right on hover. 

**To Reproduce**
1. Launch app 'npm run dev'
2. In Safari, Open application page (http://localhost:3000)
3. Move mouse to hover over the controls at the bottom of the screen (Mute Audio, Video, etc)
4. See error where the controls shift position

**Expected behavior**
Control buttons should stay in place, not shift position. 

**Screenshots**
![Screen Recording 2020-03-26 at 4 21 53 PM_1](https://user-images.githubusercontent.com/213710/77652577-7e606e00-6f7f-11ea-8943-7ccca7d32726.gif)

**Environment (please complete the following information):**
 - OS: Mac 10.14.6 
 - Browser:12.1.2
 - App Version: 0.1.0

**Additional context**
This problem does not happen in Chrome

**Comment by timmydoza** [comment]
Thanks for the detailed bug report @alexlavr. I've confirmed that it is an issue. It's a low priority problem, but hopefully we can address it soon!
