### ISSUE TITLE
Cannot enter room on chrome for iOS

### ISSUE THREAD

**Issue by moriadamri** [twilio/twilio-video-app-react#116]
**Describe the bug**
cannot enter a session from chrome on ios. 

**To Reproduce**
1. Deploy the last version(2.3.0)
2. Go to the deployed version of the app on ios device
3. See error: getUserMedia is not supported

**Expected behavior**
Enter the session

**Screenshots**
![image](https://user-images.githubusercontent.com/17779312/77847062-e2bf3f80-71c2-11ea-8144-58273b1e6890.png)

**Environment (please complete the following information):**
 - Browser: Chrome 80
 - App Version: 2.3.0

**Additional context**
i saw this supported browser list:
https://www.twilio.com/docs/video/javascript#supported-browsers
do we some workaround?

**Comment by timmydoza** [comment]
Thanks for the issue @moriadamri! 

Unfortunately, this app doesn't work in Chrome on iOS and there are no workarounds. Chrome (and Firefox) on iOS do not have access to the needed WebRTC APIs. On iOS, Safari is the only browser that this app will work with.

I have created a ticket in our backlog to show a more informative error message when the browser is not supported. The error message you received is not very helpful, so we will be improving that experience.

**Comment by MisterJimson** [comment]
It seems as though this may have changed in iOS 14.3. Does this open up possibility for support?

https://bugs.webkit.org/show_bug.cgi?id=208667

**Comment by timmydoza** [comment]
It's possible! I'm not sure if or when we will support iOS Chrome or Firefox, as these browsers would first need to pass our testing and validation. But we understand that these browsers are popular, and we would like to support them if it's possible. We're looking into it 🙂

**Comment by MisterJimson** [comment]
@timmydoza do you have an issue we could track for the above support?

**Comment by MisterJimson** [comment]
@timmydoza hey just really hoping I could track that feature request somewhere, its a critical issue for us currently.
