### ISSUE TITLE
Add an explicit comment to .env.example advising to make a copy of that file

### ISSUE THREAD

**Issue by devinrader** [twilio/twilio-video-app-react#117]
**Describe the bug**
Its very easy to miss the step of making a copy of `.env.example` into `.env`.  Users end up putting their credentials into `.env.example`, never making a copy if it and then being confused why the app is making invalid tokens.

**Additional context**
Can we just add a comment to `.env.example` that tells users to make a copy of that file?

**Comment by timmydoza** [comment]
Sure thing @devinrader! That's a good idea.
