### ISSUE TITLE
Use a P2P room instead?

### ISSUE THREAD

**Issue by QasimQureshi** [twilio/twilio-video-app-react#121]
Am I correct in assuming that the Twilio-react-app uses regular group rooms?

Would it be a significant amount or retooling to switch to peer-to-peer rooms instead?

**Comment by aaalaniz** [comment]
Hey @QasimQureshi 

By default, all rooms connected to or created are configured as Group Rooms. You can change this behavior by navigating to the [Twilio Console and updating the default Room type](https://www.twilio.com/console/video/configure) (Screenshot below).

<img width="1428" alt="Screen Shot 2020-03-31 at 11 05 42 AM" src="https://user-images.githubusercontent.com/1734140/78048738-c98fcd80-733f-11ea-91e7-81206ea6001b.png">

The React app should work with this change, but please note the following features are not available in P2P rooms.

* Dominant Speaker
* Network Quality
* Bandwidth Profiles

For more details about the differences between using P2P versus Group rooms, I recommend reading through [this developer guide](https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#p2p-or-group-rooms).

Thanks!

**Comment by Meetmetha** [comment]
Tried it the room generated is always a Group in spite of setting it to p2p in console
