### ISSUE TITLE
Screen sharing doesn't work

### ISSUE THREAD

**Issue by imjared** [twilio/twilio-video-app-react#122]
**Describe the bug**
The video widget allegedly allows for screen sharing per the [features listed here](https://github.com/twilio/twilio-video-app-react#features). When spinning up an instance of the app, however, screen sharing doesn't work. This behavior can be reproduced on a deployed resource.

**To Reproduce**
1. Clone repo and start it up using the provided steps. You can also see a deployed version [here](https://video-app-4457-dev.twil.io/?passcode=3234124457).
1. Enter a room and click share screen. Accept all required permissions and click share screen in the dialog that pops up. In safari, there's an icon that shows a "screen" as if the screen is being shared.

**Expected behavior**
1. I'd expect my screen to either be visible in the main grey area or in my thumbnail picture
1. Actual behavior: no screen is visible :(

**Screenshots**
![image](https://user-images.githubusercontent.com/525011/78084087-5315be80-7385-11ea-9ed2-63f4fad01b60.png)

![image](https://user-images.githubusercontent.com/525011/78084213-96702d00-7385-11ea-8cf8-b17d9d2cdad5.png)

![image](https://user-images.githubusercontent.com/525011/78084298-c1f31780-7385-11ea-9662-35366dcd5bab.png)

**Environment**
 - OS: mac, latest
 - Browser: chrome. reproduced in safari. safari does show an icon that seems to symbolize that i'm using 
 - App Version: 0.1.0
 - SDK Version: "twilio-video": "^2.3.0",
 - Node.js version: v12.16.1

**Comment by timmydoza** [comment]
Hey @imjared! Thanks for the issue, and thanks for the deployment link! 

I tried your deployment link and you are correct, there does seem to be a problem. I took a look at the source maps in the browser dev tools and it looks like `src/components/MainParticipant/MainParticipant.tsx` has been changed. This is the code that I see in the source maps:

```
import MainParticipantInfo from '../MainParticipantInfo/MainParticipantInfo';
import ParticipantTracks from '../ParticipantTracks/ParticipantTracks';
import React from 'react';
import useMainSpeaker from '../../hooks/useMainSpeaker/useMainSpeaker';
import useSelectedParticipant from '../VideoProvider/useSelectedParticipant/useSelectedParticipant';
import useScreenShareParticipant from '../../hooks/useScreenShareParticipant/useScreenShareParticipant';

export default function MainParticipant() {
  const mainParticipant = useMainSpeaker();
  const [selectedParticipant] = useSelectedParticipant();
  const screenShareParticipant = useScreenShareParticipant();

  const videoPriority =
    mainParticipant === selectedParticipant || mainParticipant === screenShareParticipant ? 'high' : null;

  console.log(mainParticipant);

  return (<h2>test</h2>)

  // return (
  //   /* audio is disabled for this participant component because this participant's audio 
  //      is already being rendered in the <ParticipantStrip /> component.  */
  //   <MainParticipantInfo participant={mainParticipant}>
  //     <ParticipantTracks participant={mainParticipant} disableAudio enableScreenShare videoPriority={videoPriority} />
  //   </MainParticipantInfo>
  // );
}
```

This would explain why we are seeing "test" in your screen shots. It looks like the main participant (who may be sharing their screen) is not being rendered. Reverting this file back to its normal state should fix everything for you.

**Comment by imjared** [comment]
🤦‍♂ you're a saint. had changed this yesterday to get it running while #115 was broken.

thanks for the quick reply

**Comment by timmydoza** [comment]
Not a problem! 😄👍
