### ISSUE TITLE
Segmentation fault: 11 while running tests with test:ci on node v13.2.0

### ISSUE THREAD

**Issue by TugayYaldiz** [twilio/twilio-video-app-react#127]
**Describe the bug**
This doesn't related with the test. As far as my understanding, it's related to node version. Because it was ran all tests as expected on v12.16.1 LTS and v13.12.0 Current. I wasn't tested all ranges between this two versions. Maybe some other versions has this error also, but v13.2.0 seems doesn't work.

**To Reproduce**
1. nvm install 13.2.0
2. npm run test:ci
3. See error

**Expected behavior**
İt should run all tests, as expected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22748758/78351627-6607d900-75a7-11ea-9923-b25afc8ba2bd.png)

**Environment:**
 - OS: Mac 10.15.3
 - App Version: 0.1.0
 - Node.js version: 13.2.0

**Additional context**
Maybe you should just point this out in README as a notice.

**Comment by timmydoza** [comment]
Thanks for the issue @TugayYaldiz!

I can reproduce this issue with version 13.2.0 of node. I'm not sure why this issue occurs, but I've found that versions 13.3.0 and newer work just fine. I think the fix here is to use a newer version of node.  😄 

Thanks for pointing this out, but I don't think that there is anything in the Video App that needs to be fixed, so I'm closing the issue.
