### ISSUE TITLE
Settings screen to choose inputs/outputs (cam/mic/speakers)

### ISSUE THREAD

**Issue by jhogervorst** [twilio/twilio-video-app-react#135]
**What is the feature that you would like to see in the app? Please describe.**

A settings screen where the user can choose which inputs/outputs (cam/mic/speakers) are used.

**Is your feature request related to a problem? Please describe.**

When users have multiple inputs/outputs (like a laptop + external display with built-in cam/mic/speakers), they might want to switch between them for optimal audio/video.

**Describe alternatives you've considered**

Users might be able to change the cam/mic through their system settings, but this is not ideal.

**Additional context**

Of course one can implement this themselves, but it would be nice to have it in the demo, as it’s a commonly used feature.

**Comment by aaalaniz** [comment]
Hey @jhogervorst 

You'll be happy to know this feature is actively in development. We will be sure to reference this ticket in any upcoming PRs. Feel free to provide any feedback in PRs as well.

Thanks!

**Comment by RusseII** [comment]
@aaalaniz is there an ETA? Looking to implement this myself also, but may hold off if its coming out within the new few days.

**Comment by timmydoza** [comment]
@jhogervorst @RusseII This feature has been merged to master. You can see the PR here: https://github.com/twilio/twilio-video-app-react/pull/185
