### ISSUE TITLE
Basic Deployment

### ISSUE THREAD

**Issue by medycs-healthcare** [twilio/twilio-video-app-react#140]
Looking to complete the basic implementation but the application will not deploy on my computer and provide me with the Web URL and password. 

I have followed the instructions step by step twice now and still no luck. Not sure if it is something to do with my computers setup but hoping this could be answered for others in the future who have the same problem.

**Expected behaviour**
Application deploys and I get a link

**Environment (please complete the following information):**
 I'm using windows and running everything through the terminal in VS code which is using PowerShell

**Comment by ervingayle** [comment]
@medycs-healthcare  Are you getting an error that you can share? The deployment process is fairly simple. Also, you do not get prompted for a passcode if you are testing locally. It is there in code. Need more information to help you.

**Comment by medycs-healthcare** [comment]
Hi Ervin,

Thanks for getting back to me. Yes for sure I can share some more with you.

I have been working with Twilio Support as well on this same issue. I can
provide my ticket number if you need that too.

I have been trying to run this project by following the video and the
documentation you provide, however when I run 'npm run deploy:twilio-cli' I
don't get any link or anything like in the video, it just moves to the next
line. I then try running 'twilio rtc:apps:video:view' to get a link and it
does the same thing, just goes to the next line in my terminal. I then
tried running 'twilio  rtc:apps:video:delete' and it tells me Nothing has
been deployed so there is nothing to delete.

I have attached screenshots for you.

Maybe there is something wrong on my OS. Only new to development so if its
as simple as a missing package or a wrong directory then please let me know.

Thanks,
Tom

**Comment by ervingayle** [comment]
I didn't see any screenshot(s). As a disclaimer, I do not work for Twilio but I do have this solution deployed successfully and wanted to help. I will not be able to view any ticket information as that is for Twilio Support.

Can you try running the following and providing the output:
npm -v

**Comment by timmydoza** [comment]
Sorry to hear you are having trouble deploying @medycs-healthcare.

It sounds like the commands are not printing error messages, is that correct?

One thing to try is running `npm run deploy:twilio-cli -- -l debug`. This should print verbose debugging messages to the console, which should hopefully provide us with some clues as to what is going wrong. 

The debug flag can be added to other commands as well, such as `twilio rtc:apps:video:view -l debug`.

**Comment by medycs-healthcare** [comment]
Awesome thank you.

This is what was returned:
  Error: command rtc:apps:video:deploy not found
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env
REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy
--authentication=passcode --app-directory ./build "-l" "debug"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli
script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\tomma\AppData\Roaming\npm-cache\_logs\2020-04-14T09_09_27_750Z-debug.log
PS C:\Users\tomma\twilio-video-app-react>

**Comment by medycs-healthcare** [comment]
Hi Tim,

Yes that plugin is installed and I now get an output when I run npm run
deploy:twilio-cli but it still mentions error. I have attached for your
reference.
PS C:\Users\tomma\twilio-video-app-react> npm run deploy:twilio-cli

> twilio-video-app-react@0.1.0 deploy:twilio-cli
C:\Users\tomma\twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio
rtc:apps:video:deploy --authentication=passcode --app-directory ./build


> twilio-video-app-react@0.1.0 build C:\Users\tomma\twilio-video-app-react
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  262.75 KB  build\static\js\2.34d9ac37.chunk.js
  12.78 KB   build\static\js\main.02a0aa36.chunk.js
  784 B      build\static\js\runtime-main.fa60846a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

 » Could not find profile "undefined".
 » To create the profile, run:

  twilio profiles:create

Alternatively, twilio-cli can use credentials stored in environment
variables:

# OPTION 1 (recommended)
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_API_KEY = an API Key created at twil.io/get-api-key
TWILIO_API_SECRET = the secret for the API Key

# OPTION 2
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_AUTH_TOKEN = your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not
required to move forward with installation.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env
REACT_APP_SET_AUTH=passcode npm run
build && twilio rtc:apps:video:deploy --authentication=passcode
--app-directory ./build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli
script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\tomma\AppData\Roaming\npm-cache\_logs\2020-04-15T06_27_23_395Z-debug.log
PS C:\Users\tomma\twilio-video-app-react>

**Comment by timmydoza** [comment]
Thanks for the detailed error message @medycs-healthcare! 

It looks like you may not have logged into the Twilio CLI.  Try running `twilio profiles:list`.  If you have not logged into the Twilio CLI before, it will say `No profiles have been configured.`

To login to the Twilio CLI, run `twilio login`. You will be prompted for your Account SID and Auth Token, both of which you can find on the dashboard of your Twilio console.

Hopefully this helps! Let me know 😄

**Comment by medycs-healthcare** [comment]
Thanks Tim,

Yes has helped and now working. Much appreciated.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
16/04/20,
03:27:02 pm

**Comment by timmydoza** [comment]
@medycs-healthcare I'm glad it's working!
