### ISSUE TITLE
JS implementation

### ISSUE THREAD

**Issue by louishugens** [twilio/twilio-video-app-react#141]
Our to implement this in js instead of ts? Thanks

**Comment by timmydoza** [comment]
Hi @louishugens!

You may want to look at Twilio's Video quickstart:

https://github.com/twilio/video-quickstart-js

It has many examples of Twilio Video features, all implemented with vanilla JS (without TS or React). 

Additionally, our JS Getting Started guide has many JS examples in it that could help you out:

https://www.twilio.com/docs/video/javascript-v2-getting-started

**Comment by louishugens** [comment]
Sorry, needed React with js not ts. I have trouble with control buttons
like close video.
Best Regards
Hugens LOUIS
(+509)-47007622
