### ISSUE TITLE
Add option for programmable voice

### ISSUE THREAD

**Issue by imjared** [twilio/twilio-video-app-react#145]
**What is the feature that you would like to see in the app? Please describe.**
As a user, I'd like my meeting room to be joinable via telephone. This number could either be unique or use a generated PIN.

As someone in a meeting, I'd like to have an idea of who is calling in (if possible) or at least a reference to their phone number. If audio is coming from a telephone participant, I'd like to see which participant is making noise.

**Is your feature request related to a problem? Please describe.**
Not really, no.

**Describe alternatives you've considered**
The alternatives I've considered include:
- bypassing Twilio and having our volunteers and users use their personal phones to connect. This breaches a bit of a privacy wall since users would have to share their phone numbers.
- requiring access to a computer/webcam for our tool (most likely)

**Additional context**
We're working with lower-income users who may not necessarily have access to a computer and/or webcam.

**Examples**
jitsi
<img src="https://user-images.githubusercontent.com/525011/78959282-7bee3000-7ab8-11ea-9ccc-176dda6fa0b6.png" width="75%" />

google hangouts:
<img src="https://user-images.githubusercontent.com/525011/78959356-b0fa8280-7ab8-11ea-86aa-3b74e8a44069.png" width="75%" />

**Comment by ervingayle** [comment]
@imjared You can address this with Twilio Studio using the conference PIN sample template and leverage the same pin concept in your screenshots leveraging Twiml to connect your volunteers to the room. https://www.twilio.com/docs/video/adding-programmable-voice-participants-video-rooms. The users that dial in by phone will show up in the video room as cards with their phonenumber-random string as the identity.

Also, I built a service that leverages this solution that I wish to offer to schools and non-profits, volunteers at no cost. Would you be interested in trying it out?

**Comment by timmydoza** [comment]
Thanks for the feature @imjared! It is possible to do this with Twilio. However, we do not have plans to add this feature to this app. 

If you want to try out the feature yourself, I'd recommend that you check out our guide that was shared by ervingayle above: https://www.twilio.com/docs/video/adding-programmable-voice-participants-video-rooms.
