### ISSUE TITLE
Add a way to share internal audio with screenshare

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#148]
**What is the feature that you would like to see in the app? Please describe.**
Share internal audio with screen sharing

**Is your feature request related to a problem? Please describe.**
I want to be able to do things similar to watching yt videos together in the call, but there is not currently a way to share internal audio

**Comment by timmydoza** [comment]
Thanks for the suggestion @RusseII!

Unfortunately it isn't possible to implement this feature. The system audio is not available to the WebAudio API as an audio input device.

**Comment by nuenook** [comment]
Hey, I think now is possible to do with Google Chrome & Edge Chromium

![D1mKY](https://user-images.githubusercontent.com/16642760/83738287-50359380-a67e-11ea-9a6b-13927fd01fa3.jpg)


ref: https://stackoverflow.com/questions/19382444/is-it-possible-broadcast-audio-with-screensharing-with-webrtc

**Comment by piyush2054** [comment]
Hi @timmydoza Since it's supported on Google Chrome and Edge Chromium. Can this be re-opened?

**Comment by RusseII** [comment]
@timmydoza

**Comment by viney-raintree** [comment]
Any updates on the above request?

**Comment by viney-raintree** [comment]
@timmydoza

**Comment by 1dolinski** [comment]
@timmydoza any update on this buddy, a highly requested feature and we're starting to look at a work around..

**Comment by spalmertwilio** [comment]
The Twilio Blog has some excellent posts that might help, please review: 

- https://www.twilio.com/blog/play-video-files-twilio-video-call
- https://www.twilio.com/blog/play-audio-files-twilio-video-call
- https://www.twilio.com/blog/screen-sharing-javascript-twilio-programmable-video
