### ISSUE TITLE
Add UI to guide the user when camera or microphone permissions get denied

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#149]
**What is the feature that you would like to see in the app? Please describe.**
UI for handling different error events like camera permission denied, microphone permission denied, etc. 

**Is your feature request related to a problem? Please describe.**
Non tech savvy users having issues with the camera/microphone not working and being lost in how to fix the problem

**Comment by timmydoza** [comment]
Thanks for the feature @RusseII!

It's a nice suggestion, so we have added a ticket to our internal backlog.  Thanks!

**Comment by RusseII** [comment]
Any time frame estimate on this? @timmydoza 

I saw https://github.com/twilio/twilio-video-app-react/pull/210 which will help somewhat when people don't have an audio track

Wondering if this is something still in your backlog, or if active development has started on it yet. 

Thanks for all that you do!!

**Comment by timmydoza** [comment]
Hey @RusseII!

Quick update on this - we have updated our Best Practices guide to include advice on how to best handle errors: https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#handling-errors

With that - we will soon be modifying the app so that it follows those guidelines.  

Thanks for your patience!

**Comment by gajus** [comment]
What's the correct way to ask for permission once this happens?

**Comment by RusseII** [comment]
@timmydoza - Best practices guide is great! Thanks for sharing.

Have you started modifying the app to follow those guidelines? 

Curious on the timeline so I know if I should implement this myself for our app, or if it was close to being added on your side.

Thanks!!

**Comment by timmydoza** [comment]
@RusseII - sorry about the delay, but this has been added to the app! Here's a little demo.

![device-error](https://user-images.githubusercontent.com/12685223/95255918-57f97600-07df-11eb-89ac-08f236be4720.gif)

It displays a user friendly error for the most common errors reported by `getUserMedia`. It also will display a warning when no audio or video input devices are detected (via `enumerateDevices()`).
