### ISSUE TITLE
implementation using JS

### ISSUE THREAD

**Issue by AliSufian27** [twilio/twilio-video-app-react#151]
**What is the feature that you would like to see in the app? Please describe.**
I want to implement using JS in ASP.NET MVC?

**Comment by timmydoza** [comment]
Hi @AliSufian27!

Unfortunately, we don't have any ASP.NET examples for you. However, you may want to look at Twilio's Video quickstart:

https://github.com/twilio/video-quickstart-js

It has many examples of Twilio Video features, all implemented with vanilla JS (without TS or React).

Additionally, our JS Getting Started guide has many JS examples in it that could help you out:

https://www.twilio.com/docs/video/javascript-v2-getting-started
