### ISSUE TITLE
Allow changing audio volume

### ISSUE THREAD

**Issue by jhogervorst** [twilio/twilio-video-app-react#154]
**What is the feature that you would like to see in the app? Please describe.**

A method to increase/decrease the audio output volume.

**Is your feature request related to a problem? Please describe.**

The current volume is a bit low, compared to e.g. Slack audio calls.

**Describe alternatives you've considered**

Users can change the system audio volume. However, this may not be enough (e.g., on iOS devices) to get a good volume.

**Additional context**

We reviewed the code, but couldn’t find a way to increase the volume currently:

> API doesn’t allow us to adjust the audio volume.. HTML audio “volume” attribute is set to 100%. As I see we can’t solve that issue for now → we also can’t adjust the volume programmatically on our own (like Slack can).

A customisable volume slider (maybe in the [settings screen](https://github.com/twilio/twilio-video-app-react/issues/135)?) would be great. A ‘fixed’ volume change (e.g., 20% louder that currently) would also be nice to start with.

**Comment by timmydoza** [comment]
Thanks for the feature suggestion @jhogervorst!

I'm wondering if you could please elaborate on the low volume issue you experienced. What browser and device were you using? Were all participants quiet or just a few? Was the volume on your speakers (if any) turned up enough? 

I'm a little hesitant to add this feature to the app because the app's volume will always depend on the system's volume. A volume slider in the app cannot make the audio louder than the system audio would permit. Plus this doesn't appear to be a feature that is present in other video collaboration apps (like Google Meet, or Jitsi). Let me know if you can think of any other applications that have this feature so I can check it out 🙂.

We are looking at adding a feature that lets users select their audio output device.  This could help users choose the most audible device for the application.

**Comment by jhogervorst** [comment]
> What browser and device were you using? Were all participants quiet or just a few? Was the volume on your speakers (if any) turned up enough?

My colleagues tested on a few devices with a one-to-one video call. They tried it in Chrome and Safari on Mac, and in Safari on iPad. They both tried the internal speakers and headphones, with the system volume turned to 100%.

In their experience, the volume was less loud than with other (video) calling apps (like Slack or Google Meet).

> A volume slider in the app cannot make the audio louder than the system audio would permit. Plus this doesn't appear to be a feature that is present in other video collaboration apps (like Google Meet, or Jitsi).

I agree that a volume slider might be overkill.

I would say that in a ‘normal’ situation (like a call between two recent Macs or iPads), the in-call volume should be right at around 70–80% of the system volume (so you have a bit of margin left to turn up the volume in special situations). Right now, we feel this is not the case.

Is there a way to increase the overall volume of the audio with Twilio video meetings? If we could just make it 20% louder, I think that would solve the problem.

**Comment by timmydoza** [comment]
Thanks for the info @jhogervorst!!

We are aware of a number of audio issues in iOS Safari. [This bug](https://bugs.webkit.org/show_bug.cgi?id=208134) reports that the volume of remote audio tracks seems to be random when the tracks are attached to the DOM. They even may be silent. This might explain what you are experiencing. 

Another issue that I have encountered has to do with using the app in Safari and Chrome at the same time on a Mac. When audio is being captured in Safari, the audio that is being captured in 
Chome is much quieter than normal. If you close Safari, the volume of the captured audio in Chrome returns to normal. 

Were you testing this app in Chrome and Safari at the same Mac?

In any event, this is a feature that we don't plan on adding to the app. I'd be hesitant to increase the volume across the board. We use this app on a daily basis for meetings here at Twilio, and volume issues have not been observed (aside from the two scenarios above), so I'd be afraid of making the app too loud. 

Additionally, adding an adjustable audio slider (presumably hooked up to a [GainNode](https://developer.mozilla.org/en-US/docs/Web/API/GainNode)) adds lots of complexity to the app. I'd be hesitant to add a feature like this especially when it isn't present in other video applications. I can't seem to find any 'prior art' for this feature.

**Comment by jhogervorst** [comment]
@timmydoza Thanks a lot for your reply! I missed it before, so that’s why I’m replying a bit later 😊

> We are aware of a number of audio issues in iOS Safari. [This bug](https://bugs.webkit.org/show_bug.cgi?id=208134) reports that the volume of remote audio tracks seems to be random when the tracks are attached to the DOM. They even may be silent. This might explain what you are experiencing.

This is good to know. Let’s hope this improves the volume on iOS, and comes soon (iOS 13.6?).

We also have issues with audio streams not working at all sometimes (requiring one or more refreshes). Hopefully that will also be solved by this fix. Unfortunately we haven’t found a cause/pattern yet, that’s why I haven’t opened a separate issue about it.

> Another issue that I have encountered has to do with using the app in Safari and Chrome at the same time on a Mac. When audio is being captured in Safari, the audio that is being captured in
> Chome is much quieter than normal. If you close Safari, the volume of the captured audio in Chrome returns to normal.
> 
> Were you testing this app in Chrome and Safari at the same Mac?

No, we tries with one client per device (so either Chrome or Safari on Mac, and some other device for the other participant).

> In any event, this is a feature that we don't plan on adding to the app. I'd be hesitant to increase the volume across the board. We use this app on a daily basis for meetings here at Twilio, and volume issues have not been observed (aside from the two scenarios above), so I'd be afraid of making the app too loud.
> 
> Additionally, adding an adjustable audio slider (presumably hooked up to a [GainNode](https://developer.mozilla.org/en-US/docs/Web/API/GainNode)) adds lots of complexity to the app. I'd be hesitant to add a feature like this especially when it isn't present in other video applications. I can't seem to find any 'prior art' for this feature.

Clear!

**Comment by git-anshuls** [comment]
@timmydoza 
Hey, 
I know this issue is closed, but we are facing a very similar issue on iPad and want to understand if something has changed in the past few months, since the issue closed. 

For us, the audio at the time of starting the call (on iPad) is random. And, we are not able to control it using the system audio. 

Can you please help us, or provide any workaround for the same.

**Comment by kunjanshah** [comment]
Has there been any update to this issue? This is creating very loud audio when in a twilio room, and the we cannot change it with the iPad volume buttons.
