### ISSUE TITLE
Any plans to package the hooks and context component?

### ISSUE THREAD

**Issue by OliBridgman** [twilio/twilio-video-app-react#155]
Hello, I was wondering if you have any plans to make a package of the video functionality removed from the rest of the application? While this repo is a fantastic reference, and thanks to your team for building and publishing this, if we're trying to integrate video functionality into an already existing react application, this package isn't particularly consumable. It would be great to be able to install the shared hooks and video context provider, allowing a user to quickly get the functionality up and running, while the UI can be implemented however the consumer wants.

**Comment by timmydoza** [comment]
Hey @OliBridgman! Excellent question. This is something that we have been discussing here for some time. It's possible that we may release a packaged version of the hooks and components in this app, but it may take us quite some time to get around to it. There aren't any immediate plans to do so.

That said, as we built this app, we tried our best to keep a clear separation between 'application code', and 'platform code'.  Application code is specific to this application and its UI. Things like `src/state/` and `src/components/MenuBar` are specific to this application. This 'application code' handles how things look, how errors are displayed, and how tokens are fetched, among other things. 

'Platform code' is code that is application-agnostic.  Most of the hooks and `src/components/VideoProvider` (for instance) should continue to function just fine if they were dropped right into any React application. It's these 'platform' components and hooks that should work anywhere, and they are the ones that we would include in a package. 

If you are interested, there is a way to use this app as a component library, but keep in mind that it is not tested or officially supported:

- In `package.json`, remove `react` as a dependency and add it as a peerDependency.
- In `tsconfig.json`, remove the `"noEmit": true` option.
- Run `npx tsc -d` to compile all files to JS

Then, in your own application, you can install this app as a dependency:
- `npm install -S <path to the app directory>`

Now, you can import hooks or components in your own app:
`import usePublications from 'twilio-video-app-react/src/hooks/usePublications/usePublications';` 

Keep in mind, nearly all components must be used within the `<VideoProvider>` component.

**Comment by amok** [comment]
We've been considering switching from Twilio. But then you guys (twilio's team) released this app. And it's a game changer. But better to say - it would be. Since we cannot use it "as is" - yep, we have own styling and BE :) Now it appears to be a bit uneasily - trying to sync our repo with your changes. If you release the app as a lib you'll save us (your users) a lot of effort and money. Hope that will happen ASAP and looking forward to it.

**Comment by nirmal-cs** [comment]
+1

**Comment by timmydoza** [comment]
I've let our project managers know about the interest in this feature, but at the moment this feature is not on our roadmap - so I'll be closing the issue. We'll continue to look at this thread to gauge additional interest. 

Thanks.

**Comment by papuruth** [comment]
Cannot compile it gives error. Unknow compiler options

**Comment by stephenasamoah** [comment]
Looking forward to making this a reality, guys. Your implementation is solid, but that package is gonna save lives, seriously.
