### ISSUE TITLE
twilio rtc:apps:video:deploy --authentication passcode  » Error code 20003 from Twilio: Authentication Error - invalid username. 

### ISSUE THREAD

**Issue by gauravshremayee** [twilio/twilio-video-app-react#156]
**Describe the bug**
       When executing below command:
        $twilio rtc:apps:video:deploy --authentication passcode
        I am getting below error
    » Error code 20003 from Twilio: Authentication Error - invalid username. See 
        https://www.twilio.com/docs/errors/20003 for more info.

**To Reproduce**
1. Go to '...'      Run this command - twilio rtc:apps:video:deploy --authentication passcode

**Expected behavior**
Web App should be deployed

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Ubuntu 19.10]

**Additional context**

**Comment by wcousin** [comment]
I'm guessing you are not using the correct user profile. Run the following command to see your profiles list:
`twilio profiles:list`
Then you need to select the profile you want to use.

Otherwise it could simply be that you are not logged in using:
`twilio login`

**Comment by wcousin** [comment]
I just saw that your error says "invalid username." Since you don't use your username to sign into the API in Terminal then maybe your not entering the keys correctly...?

**Comment by timmydoza** [comment]
Thanks for the issue @gauravshremayee!

The problem likely has to do with how you have authenticated with the Twilio CLI. Please take a look at the possible causes and possible solutions at the following link to see if it helps you solve your problem:

**Comment by gauravshremayee** [comment]
Hi,

Thanks for the quick  response @timmydoza & @wcousin 

I have followed the steps as suggested by @wcousin .

I got the profile list using below command : 
$twilio profiles:list
ID           Account SID                         Active
penguin      ACba7b0a71237527388b15c0be8eaecf9a  true  
penguintech  ACba7b0a71237527388b15c0be8eaecf9a        

then -
i copied the auth token from twilio console web corresponding to ACba7b0a71237527388b15c0be8eaecf9a SID from API Crdentials / Live credentials

$ twilio login ACba7b0a71237527388b15c0be8eaecf9a
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Account or Subaccount, and then forgotten.
? Your Twilio Auth Token for your Twilio Account or Subaccount: [hidden]

? Shorthand identifier for your profile: penguin
? Account credentials are currently stored in environment variables and will take precedence over the "penguin" profile when connecting to Twilio, unless the "penguin" profile is 
explicitly specified. Continue setting up "penguin" profile? Yes
? Overwrite existing profile credentials for "penguin"? Yes
** Message: 20:43:58.818: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues

Please Help.
<img width="1258" alt="Screenshot 2020-04-16 at 8 47 52 PM" src="https://user-images.githubusercontent.com/4831448/79474045-8f9f1680-8023-11ea-8011-8d92d8f59d1b.png">


Regards,
Gaurav

**Comment by timmydoza** [comment]
Thanks for the info @gauravshremayee!

That's an interesting error: `org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection`.  The Twilio-CLI uses a library called `keytar` to store secrets in Ubuntu's keyring.  It requires a dependency called `libsecret-1-dev`. Can you please make sure that you have that installed?

`sudo apt-get install libsecret-1-dev`

If this doesn't solve your issue, there is a workaround. Instead of logging into the Twilio CLI with `twilio login`, you can instead set your Account SID and Auth Token as environment variables before you run `npm run deploy:twilio-cli`.

Like this:
`TWILIO_ACCOUNT_SID=AC00000000000000 TWILIO_AUTH_TOKEN=xxxxxxxxxx npm run deploy:twilio-cli`

**Comment by gauravshremayee** [comment]
Hi,
Thanks for your update .
Still i am getting the issues even after following workaround ,libsecret-1-dev was already installed. 

$sudo apt-get install libsecret-1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsecret-1-dev is already the newest version (0.18.8-2).


$ twilio profiles:list
ID           Account SID                         Active
penguin      ACba7b0a71237527388b15c0be8eaecf9a  true  
penguintech  ACba7b0a71237527388b15c0be8eaecf9a        
(base) penguin@penguin-MS-7B53:~/twilio-video-app-react$ twilio login ACba7b0a71237527388b15c0be8eaecf9a
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Account or Subaccount, and then forgotten.
? Your Twilio Auth Token for your Twilio Account or Subaccount: [hidden]
? Shorthand identifier for your profile: penguin
? Account credentials are currently stored in environment variables and will take precedence over the "penguin" profile when connecting to Twilio, unless the "penguin" profile is 
explicitly specified. Continue setting up "penguin" profile? Yes
? Overwrite existing profile credentials for "penguin"? Yes
** Message: 21:04:24.467: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues



**Workaround**:
(base) penguin@penguin-MS-7B53:~/twilio-video-app-react$ export TWILIO_ACCOUNT_SID=ACXXXXXXX

(base) penguin@penguin-MS-7B53:~/twilio-video-app-react$ export TWILIO_AUTH_TOKEN=f18f0cXXXXXX


$ sudo npm run deploy:twilio-cli

> twilio-video-app-react@0.1.0 deploy:twilio-cli /home/penguin/twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build


> twilio-video-app-react@0.1.0 build /home/penguin/twilio-video-app-react
> node ./scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  262.69 KB  build/static/js/2.672d3985.chunk.js
  12.78 KB   build/static/js/main.b27e6600.chunk.js
  784 B      build/static/js/runtime-main.fa60846a.js

 ›   Warning: twilio-cli update available from 1.12.0 to 2.0.0.
 » Could not find profile "undefined".
 » To create the profile, run:

  twilio profiles:create

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_API_KEY = an API Key created at twil.io/get-api-key
TWILIO_API_SECRET = the secret for the API Key

# OPTION 2
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_AUTH_TOKEN = your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required to move forward with installation.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-17T15_32_40_868Z-debug.log


$ sudo twilio rtc:apps:video:view
 ›   Warning: twilio-cli update available from 1.12.0 to 2.0.0.
 » Could not find profile "undefined".
 » To create the profile, run:

  twilio profiles:create

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_API_KEY = an API Key created at twil.io/get-api-key
TWILIO_API_SECRET = the secret for the API Key

# OPTION 2
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_AUTH_TOKEN = your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required to move forward with installation.



Do ,i need to update it to 2.0.0 , if yes please mention the command .
Else, suggest me another workaround .

**Comment by timmydoza** [comment]
Thanks for the info @gauravshremayee.

I can get the deploy feature to work just fine when I use a version of Ubuntu that has a GUI (such as the version that runs on my laptop).  However, when I try the same steps on a version of Ubuntu without a GUI (such as a version of Ubuntu that runs on AWS, that is only accessed with `ssh`), I encounter problems similar to the one that you are seeing. I think that the `keytar` library relies on GNOME's keyring to store secrets, which is only available when there is a GUI. 

Are you using Ubuntu with a GUI, or are you accessing an Ubuntu instance over `ssh`?

In any event, the "OPTION 1 (recommended)" workaround in your comment above should work for you. Just set the three environment variables that it lists, and then run `npm run deploy:twilio-cli`. Can you please try this workaround and let me know how it works? Thanks!

**Comment by gauravshremayee** [comment]
Hi @timmydoza .

Thank you again for verifying  this case for different scenarios.
I have Ubuntu 19.10 Desktop with me  and i am  accessing it  via ssh ,vnc viewer from my MacBook and i also directly on Ubuntu Desktop.
I run the WORKAROUND 1 on  ssh ,Desktop  as well VNC .
In all the cases i got the same error:
I have attached the screenshot. I created the new API key today( does that matter?) 

<img width="1214" alt="twilio_Error_on_desktop" src="https://user-images.githubusercontent.com/4831448/79857139-f38e5a00-83ea-11ea-977b-5f6d4e2fd33d.png">
<img width="1214" alt="api_keys" src="https://user-images.githubusercontent.com/4831448/79857166-fc7f2b80-83ea-11ea-9fef-10dcb889479f.png">

Thanks

**Comment by timmydoza** [comment]
Thanks for the info @gauravshremayee!

I think I see the issue. You are using `sudo`. When you use `sudo`, commands are executed as another user, specifically the root user. 

I think this is why the Twilio CLI cannot access the environment variables you set. You're setting them as your user, but it's the root user that's running the CLI commands. 

A test:

-Run `env`.  You should see your Twilio environment variables.
-Run `sudo env`. You should not see your Twilio environment variables. 

This could also explain why `twilio login` isn't working for you. 

I would recommend using `npm` without `sudo`. There are a number of articles online about ways to achieve this. Let me know how this works for you!

**Comment by gauravshremayee** [comment]
Hi @timmydoza 

Thanks for your response.

You are right ,regarding use of sudo .

I avoided using sudo this time,but again landed up  org.freedesktop.Secret.Error.IsLocked issue.

$ twilio profiles:list
 ›   Warning: twilio-cli update available from 2.0.0 to 2.0.1.
ID           Account SID                         Active
penguin      ACba7b0a71237527388b15c0be8eaecf9a  true  
penguintech  ACba7b0a71237527388b15c0be8eaecf9a        
(base) penguin@penguin-MS-7B53:~/twilio-video-app-react$ twilio login ACba7b0a71237527388b15c0be8eaecf9a
 ›   Warning: twilio-cli update available from 2.0.0 to 2.0.1.
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Account or Subaccount, and then forgotten.
? Your Twilio Auth Token for your Twilio Account or Subaccount: [hidden]
? Shorthand identifier for your profile: penguin
? Account credentials are currently stored in environment variables and will take precedence over the "penguin" profile when connecting to Twilio, unless the "penguin" profile is 
explicitly specified. Continue setting up "penguin" profile? Yes
? Overwrite existing profile credentials for "penguin"? Yes
** Message: 01:55:43.522: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues

**Comment by timmydoza** [comment]
Hey @gauravshremayee!

The `org.freedesktop.Secret.Error.IsLocked` is an error produced by the Twilio CLI itself, and not by this app. You can report the issue to the Twilio CLI team by posting an issue at https://github.com/twilio/twilio-cli/issues. Please be sure to run the command with the `-l debug` flag so that you can fill out their issue template. 

You can still deploy the video app without logging into the Twilio CLI. Just set the environment variables as described in [Option 1 here](https://www.twilio.com/docs/twilio-cli/general-usage#want-to-use-environment-variables-instead-of-creating-a-profile), and then run `npm run deploy:twilio-cli`.
