### ISSUE TITLE
Request camera and microphone permissions at the same time

### ISSUE THREAD

**Issue by krkrosenbergtech** [twilio/twilio-video-app-react#158]
**What is the feature that you would like to see in the app? Please describe.**
That the app will request both camera and microphone permissions at the same time.

**Is your feature request related to a problem? Please describe.**
On all platforms I have to press accept permissions two times; one time for camera and one time for microphone.
![image](https://user-images.githubusercontent.com/37480046/79470337-8dc45b80-8001-11ea-9e53-0460f27bb8c3.png)

**Describe alternatives you've considered**
Request both camera and microphone permission at the same time.

**Additional context**
Here is an example fra another video app
![image](https://user-images.githubusercontent.com/37480046/79469858-01199d80-8001-11ea-95d2-4bfe49aa109d.png)

**Comment by timmydoza** [comment]
Thanks for the feature request @krkrosenbergtech!

I have a PR up here to add the feature: https://github.com/twilio/twilio-video-app-react/pull/159

**Comment by imarshmultani** [comment]
Hi @timmydoza ... i'm continuesly getting: 

```
Type 'Participant' is not assignable to type 'LocalParticipant | RemoteParticipant'.
  Type 'Participant' is not assignable to type 'RemoteParticipant'.
    Types of property 'audioTracks' are incompatible.
      Type 'Map<string, AudioTrackPublication>' is not assignable to type 'Map<string, RemoteAudioTrackPublication>'.
        Type 'AudioTrackPublication' is not assignable to type 'RemoteAudioTrackPublication'.
          Property 'isSubscribed' is missing in type 'LocalAudioTrackPublication' but required in type 'RemoteAudioTrackPublication'.  TS2322

     9 |     /* audio is disabled for this participant component because this participant's audio 
    10 |        is already being rendered in the <ParticipantStrip /> component.  */
  > 11 |     <MainParticipantInfo participant={mainParticipant}>
       |                          ^
    12 | 
    13 |       <ParticipantTracks participant={mainParticipant} disableAudio enableScreenShare videoPriority="high" />
    14 |       
```

Do you anything about this how we can fix this issue ? ... it was working fine before, i had my friend shared same code and he was getting the same error from start , but i just started getting it ...

**Comment by timmydoza** [comment]
Hey @imarshmultani - that looks like the same error from this issue: https://github.com/twilio/twilio-video-app-react/issues/91

This issue was fixed a few weeks ago. Are you using the most up-to-date version of the codebase? If you are, the version of typescript as specified in `package.json` should be 3.8.3.

**Comment by imarshmultani** [comment]
Thanks for getting back @timmydoza  below is my current package.json : 

```
"dependencies": {
    "@material-ui/core": "^4.9.1",
    "@material-ui/icons": "^4.9.1",
    "@primer/octicons-react": "^9.4.0",
    "@types/fscreen": "^1.0.1",
    "@types/jest": "^24.9.1",
    "@types/lodash.throttle": "^4.1.6",
    "@types/node": "^12.12.26",
    "@types/react": "^16.9.19",
    "@types/react-dom": "^16.9.5",
    "@types/react-router-dom": "^5.1.3",
    "@types/twilio-video": "^2.0.10",
    "concurrently": "^5.1.0",
    "cross-env": "^7.0.2",
    "express": "^4.17.1",
    "fscreen": "^1.0.2",
    "husky": "^3.1.0",
    "lint-staged": "^9.5.0",
    "lodash.throttle": "^4.1.1",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.3.1",
    "redux": "^4.0.5",
    "socket.io-client": "^2.3.0",
    "twilio": "^3.39.3",
    "twilio-video": "^2.2.0",
    "typescript": "^3.7.5"
  },
```

if i pull new updates from, i'm afraid it might override my local changes ? .

**Comment by timmydoza** [comment]
Thanks @imarshmultani. Looks like you are using an older version of the codebase. You can try to merge in new changes if you want, but there still is a way to get this to work.

Are you using `yarn` by any chance? If so, try running `npm install` instead. I explain this solution in the previously linked github issue: https://github.com/twilio/twilio-video-app-react/issues/91#issuecomment-599152224
