### ISSUE TITLE
Uncaught (in promise) Cannot start audio or video In Chrome

### ISSUE THREAD

**Issue by RK-WALTERS** [twilio/twilio-video-app-react#162]
After a lot of trials I was able to deploy this and get the page to show.  However I cannot access the audio or video.  Using the Dev tools I found this:
![errors](https://user-images.githubusercontent.com/63864038/79584221-58fce680-808b-11ea-8e0b-a8672f8fcd6a.PNG)
I am hoping that you can give me some guidance.

**Comment by timmydoza** [comment]
Hi @RK-WALTERS. Thanks for the issue.

Unfortunately, I won't be able to help you without more information. Can you please create a new issue and fill out the provided issue template? The more information you can provide us, the better.  Thanks!!
