### ISSUE TITLE
In setup branch, app comes up blank, console reports a javascript error

### ISSUE THREAD

**Issue by ijt** [twilio/twilio-video-app-react#167]
**Describe the bug**
I tried running this app locally but it came up with a blank web page and an error in the console.

**To Reproduce**
1. `git clone -b setup git@github.com:kimobrian/TwilioReact.git`
2. `cd TwilioReact`
3. Put secrets into .env
4. `npm start`
5. Load `localhost:3000` in a browser

**Expected behavior**
The app should appear.

**Screenshots**
Instead, it comes up blank with an error in the console:
<img width="908" alt="Screen Shot 2020-04-19 at 12 46 49 PM" src="https://user-images.githubusercontent.com/15530/79698313-082cef80-823d-11ea-9f9a-79dfd05be088.png">

**Environment (please complete the following information):**
 - OS: Mac  OS X Mojave
 - Browser: Chrome
 - App Version: 1d478b6d89f8fa8a7b9a733596ab77aced880b31
 - SDK Version: I didn't find it.
 - Node.js version: 13.11.0

A quick fix was to pin react and react-dom to version 16.2.0, based on what I found at https://stackoverflow.com/questions/52251687/uncaught-typeerror-cannot-read-property-injection-of-undefined:
```
[ ~/src/speakeasy/speakeasy-twilio ] git diff
diff --git a/package.json b/package.json
index ff70e9a..00c77c7 100644
--- a/package.json
+++ b/package.json
@@ -11,8 +11,8 @@
     "express": "^4.16.2",
     "faker": "^4.1.0",
     "material-ui": "^0.20.0",
-    "react": "^16.2.0",
-    "react-dom": "^16.2.0",
+    "react": "16.2.0",
+    "react-dom": "16.2.0",
     "react-tap-event-plugin": "^3.0.2"
   },
   "scripts": {
```

**Comment by timmydoza** [comment]
Thanks for the issue @ijt!

Unfortunately I can't help you with this one. It looks like this issue relates a different repository: [kimobrian/TwilioReact](https://github.com/kimobrian/TwilioReact). Please file an issue with that repository:
 
https://github.com/kimobrian/TwilioReact/issues

**Comment by ijt** [comment]
Got it, thanks @timmydoza .
