### ISSUE TITLE
Invalid Access Token issuer/subject. Error Code 20103 on JOIN ROOM click

### ISSUE THREAD

**Issue by ijt** [twilio/twilio-video-app-react#168]
**Describe the bug**
After deploying the app, when I try to join a room, I get error 20103.

**To Reproduce**
1. `export TWILIO_AUTH_TOKEN=...; export TWILIO_ACCOUNT_SID=AC...`
2. `npm run deploy:twilio-cli -- --override`
3. Open the URL displayed, like ` https://video-app-1268-dev.twil.io?passcode=...`
4. Enter Name and Room.
5. Click JOIN ROOM.
6. An error dialog appears.

**Expected behavior**
I expected to enter the video chat room.

**Screenshots**
<img width="608" alt="Screen Shot 2020-04-19 at 9 28 07 PM" src="https://user-images.githubusercontent.com/15530/79714246-0e46be80-8285-11ea-806f-ec98d7b5a34e.png">

**Environment (please complete the following information):**
 - OS: Mac OS X Mojave
 - Browser: Chrome
 - App Version: cb0020525081ba198c4bf6864ca4efb827d91b2b
 - SDK Version: 1.2
 - Node.js version: 13.11.0

**Comment by timmydoza** [comment]
Thanks for the issue @ijt!

I think this issue has to do with the fact that you are providing your Twilio credentials through environment variables. If you run `twilio login` and provide your account credentials when prompted, then the app should work properly when redeployed. Can you please try this and let me know how it works?

Thanks.

**Comment by ijt** [comment]
Hi @timmydoza , thanks for your reply.

Here's what happened, based on your suggestion:
```
$  twilio login
$ twilio plugins:install @twilio-labs/plugin-rtc
$ npm run deploy:twilio-cli

> twilio-video-app-react@0.1.0 deploy:twilio-cli /Users/issactrotts/src/speakeasy/twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build


> twilio-video-app-react@0.1.0 build /Users/issactrotts/src/speakeasy/twilio-video-app-react
> node ./scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  262.9 KB  build/static/js/2.8fea057f.chunk.js
  13 KB     build/static/js/main.059b042d.chunk.js
  784 B     build/static/js/runtime-main.fa60846a.js

 » Error code 20003 from Twilio: Authenticate. See https://www.twilio.com/docs/errors/20003 for more info.
npm ERR! code ELIFECYCLE
npm ERR! errno 35
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
npm ERR! Exit status 35
npm ERR! 
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/issactrotts/.npm/_logs/2020-04-20T21_40_32_491Z-debug.log
```
This is what happened before, and it's why I was using environment variables instead. The only additional info I found in the log was this stack trace:
```
12 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Failed to exec deploy:twilio-cli script
13 verbose stack Error: twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build
&& twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
13 verbose stack Exit status 35
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by timmydoza** [comment]
Thanks for the info @ijt. I'm going to close this issue since you created another one for the `20003` error. No need to have two Github issues for one bug 😄
