### ISSUE TITLE
Is it possible to post a public roadmap, or share what features are currently planned?

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#170]
I've seen several comments about things being/not being on your roadmap. 

Is it possible for to share what's currently on the roadmap & a general time frame?

**Comment by timmydoza** [comment]
Great question @RusseII!

I discussed this one with the team. This demo app is _mostly_ feature complete. Any updates that are coming down the pipeline will be smaller features, bugfixes, or maintenance. 

We would share a list of what is currently on the roadmap, but things can fluctuate and priorities can change (especially now). We wouldn't want to share upcoming features only to change our minds on them as our business priorities change. 

That said, I think it's a good idea to keep track of some features here on github. Feature requests that remain open here are ones that we are interested in (and would welcome community contributions on). We will also continue to welcome feature requests from the community.
