### ISSUE TITLE
twilio-video-react repo name?

### ISSUE THREAD

**Issue by douglasrcjames** [twilio/twilio-video-app-react#175]
I just noticed I have the repo name `twilio-video-react` under my Github account, but am totally willing to change it so your project can use that name. Just let me know and I'll change my repo name so your project can claim it👍

**Comment by imjared** [comment]
while this is a super nice gesture, you having a repo called `twilio-video-react` doesn't affect their ability to have one with the same name under their `twilio/` org.

need more people like you looking out for each other though!

**Comment by douglasrcjames** [comment]
Good point!! Glad to be a good Samaritan for my fellow devs :)
