### ISSUE TITLE
`Invalid Access Token issuer/subject Error Code: 20103` when I attempt to join a room

### ISSUE THREAD

**Issue by robinske** [twilio/twilio-video-app-react#176]
**Describe the bug**
After deploying the app with Twilio Functions, I consistently get a `Invalid Access Token issuer/subject Error Code: 20103` error when I attempt to join a room. 

This may be an issue with the CLI or rtc plugin, I can move this over to that repo if that's confirmed.

**To Reproduce**

Steps to reproduce the **failure state:**
1. Set `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN` as global environment variables
Run the following commands:
```
git clone git@github.com:twilio/twilio-video-app-react.git && cd twilio-video-app-react
twilio login
twilio plugins:install @twilio-labs/plugin-rtc
npm run build && twilio rtc:apps:video:deploy --authentication passcode --app-directory ./build -l debug
# ^ same as npm run deploy:twilio-cli, but supports the debug flags
# [DEBUG] Using profile: ${TWILIO_ACCOUNT_SID}/${TWILIO_AUTH_TOKEN}
# navigate to URL => join room => Invalid Access Token issuer/subject Error Code: 20103
```

Steps to reproduce **success state:**

Unset the environment variables and run the underlying deploy command with a profile
```
unset TWILIO_ACCOUNT_SID && unset TWILIO_AUTH_TOKEN
npm run build && twilio rtc:apps:video:deploy --authentication passcode --app-directory ./build -l debug -p kelley
[DEBUG] Using profile: kelley
```

If I don't unset the variables and try to run with a profile, I get a different error from the rtc plugin and it fails to deploy:
```
npm run build && twilio rtc:apps:video:deploy --authentication passcode --app-directory ./build -l debug -p kelley
...
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/krobinson/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:76:64)
```

**Expected behavior**
I can deploy the video app and join a room with environment variables set and with an active twilio CLI profile. 

If this is expected behavior, would love more helpful error messages to help me uncover the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/3673341/79930314-30237b00-8416-11ea-8f9c-be9b5a6323f5.png)

**Environment (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Browser: Chrome 80 & Firefox 74
 - App Version: 0.1.0
 - SDK Version: `twilio: ^3.39.3`, `twilio-video: ^2.3.0`
 - Node.js version: v10.17.0
 - Twilio CLI version: `twilio-cli/2.0.0 darwin-x64 node-v10.17.0`
 - RTC plugin version: `0.1.4`

**Additional context**
I do have the Twilio CLI installed with Homebrew and not Node, in case that is a known issue. I can run other Twilio CLI commands without issue.

**Comment by timmydoza** [comment]
Hey @robinske, and thanks for the issue!

We have seen the `Cannot read property 'sid' of undefined` error before. The most recent version of the RTC plugin for Twilio CLI has a fix for this problem. Can you try our CLI troubleshooting steps listed in the Readme and let me know if they fix the problem for you?

https://github.com/twilio/twilio-video-app-react#troubleshooting-the-twilio-cli

Also, setting the `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN` for the Twilio CLI won't work with this application. When you run `twilio login` and provide your Account SID and Auth Token, the CLI will create a new API Key, which is required for the token server to run. When you set your Account SID and Auth Token as environment variables, no API Key is created, which is why the token server fails.  Can you try running `twilio login`?

I appreciate the detailed issue report! I definitely agree that there should be some more useful error messages (for instance, deployment should not be allowed without the required API Key). I'll mention this to the team and get some tickets cut.  Thanks!!

**Comment by robinske** [comment]
Thanks @timmydoza!

Sounds like this is semi expected behavior, so +1 for failing the deploy entirely and some additional error messages if those env vars are set.

A couple of other notes:

1. re: running `twilio login` - I did run twilio login and you do get this message, but I missed it the first time, so additional error messages would be helpful if we can detect that the profile isn't being used for the deploy.  I will also read better 😂 🙈.

![image](https://user-images.githubusercontent.com/3673341/79986337-e40a2200-8479-11ea-8690-a4b4caf34cf4.png)

Would it be possible for the shortcut command `npm run deploy:twilio-cli` to also take a `--profile | -p` arg? 

Desired but doesn't work:
```
npm run deploy:twilio-cli -p kelley
.
#  ›   Error: Unexpected argument: kelley
```

I was getting around this by running the underlying command, which was also helpful for running in debug mode:
```
npm run build && twilio rtc:apps:video:deploy --authentication passcode --app-directory ./build -l debug -p kelley
```
I'm still getting the error below but this could also help with some of my confusion there.

2. I'm already  on the latest version of the RTC plugin (0.1.4) - so there may be a lingering bug there. This only happens when I have env variables set and use the profile flag, but I can consistently reproduce:

![image](https://user-images.githubusercontent.com/3673341/79985933-4c0c3880-8479-11ea-8e3a-4f94e9c0aaf9.png)

Thank you for your help!

**Comment by timmydoza** [comment]
Thanks for the info @robinske!

1. You can pass a `-p <profile>` flag when using `npm run deploy:twilio-cli`. NPM requires a special syntax for that though (an extra `--`). 

`npm run deploy:twilio-cli -- -p <profile name>`

2. Have you tried running `twilio rtc:apps:video:delete`? Sometimes the serverless functions can get into a weird state.  Deleting the app (with version 0.1.4 of plugin-rtc) seems to fix things.  Lemme know how this works!

**Comment by robinske** [comment]
1. Ah dope! TIL
2. Blast that works! I definitely had tried this at one point, but perhaps not with the other steps/knowledge I now have 😃

So looks like the lingering problem is lack of an error message/deploy failure if you try to deploy the app with just the Account SID/Auth Token.

Thanks for helping me debug @timmydoza !

**Comment by timmydoza** [comment]
Glad it works!! I've created an internal ticket for the missing error message you mentioned.
