### ISSUE TITLE
Flip camera icon is showing on firefox

### ISSUE THREAD

**Issue by charliesantos** [twilio/twilio-video-app-react#188]
**Describe the bug**
Flip camera icon is showing on firefox

**To Reproduce**
1. Run the app on firefox

**Expected behavior**
Flip camera icon should not show.

**Screenshots**
![Screen Shot 2020-04-29 at 8 34 10 AM](https://user-images.githubusercontent.com/22135968/80616687-0e1d9000-89f6-11ea-9393-eeaedaf57701.png)

**Environment (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Firefox 75.0 (64-bit)
 - App Version: 0.1.0
 - SDK Version: 2.3.0
 - Node.js version: 12.14.1

**Comment by pjuchniewicz** [comment]
Found this issue earlier myself.  This is occurring because FireFox on a Mac, unlike Chrome and Safari, returns a facingMode of user and the FlipCamera button is checking the track's stream for that property.  I do not know if this also occurs on Windows as well or just Mac.

**Comment by timmydoza** [comment]
Fix in https://github.com/twilio/twilio-video-app-react/pull/316
