### ISSUE TITLE
Detecting when participants disconnect can take 45 seconds

### ISSUE THREAD

**Issue by tomas-c** [twilio/twilio-video-app-react#189]
_I've created an issue twilio/twilio-video.js/#986 for this but copying it here in case there are improvements to be done that don't require twilio-video.js changes._

The recommended approach ([ref](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices)) to signal when a participant leaves a room is to ensure that the following is run:

```
window.addEventListener('beforeunload', () => room.disconnect());
window.addEventListener('pagehide', () => room.disconnect());
```

This is not sufficient on Chrome on Android. 

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**How to reproduce the issue:**

1. Start [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react)
2. Join a call from two devices, one of them from Chrome on Android
3. Close the call tab mid-call on the Android device
4. Observe the participant remains on the call for 45 seconds.

**Expected behavior:**

When a participant closes the call tab mid-call, the participant connection state should be marked as disconnected ASAP.

**Actual behavior:**

When a participant closes the call tab mid-call on Chrome on Android, it takes 15 seconds to enter reconnecting state and additional 45 seconds until the participant is removed. 

Other participants on the call can't tell if their peer permanently left the call or is just having connection troubles. This is what it looks like if you're the other participant (Laptop is online, Phone just closed the call tab):

![disconnect-ux](https://user-images.githubusercontent.com/5213953/80817815-0b739400-8bca-11ea-9fa7-461d560590d5.gif)

**Suggestion**

If there was a way to signal disconnection to Twilio via a HTTP request, the [Navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) could be used as a reliable way to send a request before a browser tab is closed.

**Software versions:**

 - [x] Browser(s): Chrome 81.0.4044.117
 - [x] Operating System: Android 10, Pixel XL
 - [x] twilio-video.js: 2.3.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react) commit 1aa65abecbcf90a69bc3472b28edc277a8d95983

**Comment by makarandp0** [comment]
released issue in twilio-video.js: https://github.com/twilio/twilio-video.js/issues/986

**Comment by timmydoza** [comment]
Thanks for the issue @tomas-c. This is something that we are currently looking into. However it may not be possible to detect when a tab closes in iOS Safari. 

Looks like you have had some good discussion in https://github.com/twilio/twilio-video.js/issues/986. I'll be closing the issue here since it is a duplicate.
