### ISSUE TITLE
Firefox media permissions

### ISSUE THREAD

**Issue by douglasrcjames** [twilio/twilio-video-app-react#198]
**Two issues**, both in Firefox, which likely are connected. 

_1st:_ when prompted to Allow mic/camera media devices, user is prompted twice always, on both development and production (SSL) builds. 

_2nd:_ when I check "remember this decision" on the first prompt, the second prompt never shows, and the camera/mic acts as if it was never allowed. I then need to delete the media device permissions so it re-prompts and I can then be able to use my media devices. If I check the remember box on the second prompt, it seems to work as expected.

_Bonus Question:_ how do I listen to whether the user accepted or denied the permissions? I want to conditionally show the Connect button based on this fact.

**Expected behavior**
Firefox browser should only ask for permissions once for devices, and not crash if I check the "remember this decision" box. 

**Environment:**
 - OS: Windows 10
 - Browser: Firefox 76.0
 - App Version: 0.1.0
 - SDK Version: "twilio-video": "^2.4.0"
 - Node.js version: 12.3.1

**Comment by timmydoza** [comment]
Hey @douglasrcjames - thanks for the questions! And apologies about the delay.

I'm also seeing the 1st issue. Firefox seems to behave differently than other browsers when it comes to requesting media permission. Firefox will request permissions for each new device until you click on the 'remember this decision' box. So it looks likes Firefox is requesting permissions once when the `ensureMediaPermissions` function is run, and once when `getLocalVideoTrack` and `getLocalAudioTrack` are called.  I'll think about how to fix this.

For the second issue, I'm not seeing the behavior that you do. Everything works fine when I click on the 'remember this decision' box. Are you still seeing the behavior?

For the bonus question: the promises returned by `getLocalVideoTrack` and `getLocalAudioTrack` will throw a specific error if the user denies permissions. So anywhere those functions are used, you could add a `catch()` to see if the user denied permission. For example, this could go on line 66 of `useLocalTracks.ts`:

```
  useEffect(() => {
    // We get a new local video track when the app loads.
    getLocalVideoTrack()
      .then(() => {
        // The user allowed access
      })
      .catch(err => {
        if (err.name === 'NotAllowedError') {
          // The user denied access
        }
      });
  }, [getLocalVideoTrack]);
```

There's a list of all of the possible errors here: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Exceptions

**Comment by douglasrcjames** [comment]
Thanks for investigating that! The 2nd issue seems to be just be on localhost on PC, but not on my Mac and on my live server seems to work alright, not perfectly, but Firefox does seem to be a bit different on behavior, no biggie for now. 

The bonus question works great, thanks for that too!

**Comment by timmydoza** [comment]
Hey @douglasrcjames - just wanted to let you know that I just merged a PR that fixes the Firefox issue. The way that `useLocalTracks.ts` creates local tracks has been simplified, and now Firefox  requests permissions only once when loaded. 

Thanks for you help on this one! Please let us know if there's anything else.

**Comment by douglasrcjames** [comment]
@timmydoza thanks for fixing and further clarifying that fix! I will update my app with your changes soon and letcha know if I run into issues.
