### ISSUE TITLE
Video and microphone streams are not added after permissions accept

### ISSUE THREAD

**Issue by aevaldas** [twilio/twilio-video-app-react#201]
**Describe the bug**
When a room is already joined, modal video and microphone permissions accept does not add devices streams.

**To Reproduce**
1. Open main page
2. Permission modal will pop up, keep it open
3. Write name, room name and click join room
4. Wait until room will be joined
5. Accept video and microphone permissions on modal

**Expected behavior**
When room is joined, on video and microphone permissions accept it should add these streams.

**Environment:**
 - OS: MacOS Catalina 10.15
 - Browser: Chrome 81.0.4044.138 (Official Build) (64-bit)
 - App Version: 0.1.0
 - SDK Version: 2.4.0
 - Node.js version: 12.12.0

**Additional context**
Name and room name inputs has to be moved to the right to prevent covering by permissions modal

**Comment by arnasledev** [comment]
the issue still exists

**Comment by timmydoza** [comment]
Thanks for the issue @aevaldas!

I've discussed this issue with the team. We feel that the best solution here is to simply prevent the user from joining the room until the browser's permission dialog has been accepted or denied. We have a PR up [here](https://github.com/twilio/twilio-video-app-react/pull/231) to solve the issue.
