### ISSUE TITLE
Nodejs routes has a status 404

### ISSUE THREAD

**Issue by quochungphp** [twilio/twilio-video-app-react#204]
Hello guys.
I have some issues.
After deployed app to twilio serverless by cmd (twilio rtc:apps:video:deploy).
Some defined routes like as (***/check-room-status, ***/delete-room) return status 404, but they work in local environment.
Can i resolve them.
Pls, let share me cause.
Thanks so much

**Comment by krkrosenbergtech** [comment]
I am not 100% sure if this is right, but I think the twilio servers do not support routing. The same issue was there for me, but I found the answer inside the code here
https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MenuBar/MenuBar.tsx

![image](https://user-images.githubusercontent.com/37480046/82011913-ac585980-9676-11ea-869e-50b44b2c44d4.png)

**Comment by quochungphp** [comment]
> I am not 100% sure if this is right, but I think the twilio servers do not support routing. The same issue was there for me, but I found the answer inside the code here
> https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MenuBar/MenuBar.tsx
> 
> ![image](https://user-images.githubusercontent.com/37480046/82011913-ac585980-9676-11ea-869e-50b44b2c44d4.png)

I got it.
Thank you for taking time support.
Have a nice day

**Comment by timmydoza** [comment]
Thanks for the question @quochungphp!

@krkrosenbergtech is right, Twilio Functions do not currently support this kind of routing. The feature is on our roadmap, however!

There is a workaround if you are interested. Take a look at this file in the `plugin-rtc` repo: https://github.com/twilio-labs/plugin-rtc/blob/master/src/helpers.js#L49

There, we add a copy of index.html for each route we want to use. You could clone the repo and do the same. For example, you could use:
```
  assets.push({
    ...indexHTML,
    path: '/',
    name: '/',
  });
  assets.push({
    ...indexHTML,
    path: '/login',
    name: '/login',
  });
  assets.push({
    ...indexHTML,
    path: '/check-room-status',
    name: '/check-room-status',
  });
  assets.push({
    ...indexHTML,
    path: '/delete-room',
    name: '/delete-room',
  });
```

Then, if you install the RTC CLI Plugin for local development [instructions here](https://github.com/twilio-labs/plugin-rtc#install-the-plugin-for-local-development) then you should be able to use routing as you described.  Note, you'll have to call `assets.push` for each route you want to add. This means that wildcard routing is not possible.
