### ISSUE TITLE
iPhone bugs when clicking Home button (on the device itself)

### ISSUE THREAD

**Issue by binary64** [twilio/twilio-video-app-react#205]
**Describe the bug**
On iPhone, you can be in a conference, then click the physical Home button on the iPhone, then navigate back to the conference and the audio resumes, but missing my video (black image).

Additionally, If I press the Home button and wait long enough for the screensaver to kick in, causing me to unlock the phone again, then navigate back to Safari, it then shows "Errror Participant not found Error Code: 53204".

In both cases a simple reload of the page fixes it, but these 2 scenarios work fine on my Android device.

**To Reproduce**
1. Using an iPhone 8, and the Safari browser, load into a conference room
2. Press Home button
3. (optional) Wait until screensaver locks the device
4. Click Safari again

**Expected behavior**
I expected to re-join the conference with video without any user interactions, missing streams, or error messages.

**Screenshots**
Sorry, I hope above is good enough though.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] iphone8 ios
 - Browser: [e.g. Chrome 80, Firefox 72] Safari ios
 - App Version: [e.g. 0.1.0] latest (git master)
 - SDK Version: [e.g 2.1.0]  twilio-video@2.4.0 from npm
 - Node.js version: [e.g. 12.14.1] 12.16.2

**Additional context**
Works on Android (same procedure)

**Comment by timmydoza** [comment]
Thanks for the info @binary64!

I tried to reproduce this issue on an iPhone 8 and an iPhone 11. I was not able to reproduce the issue on either phone. 

I have some questions about the problem you see. For step 3, how long do you have to wait until you open Safari again? A few seconds, or a few minutes? Also, how often does this issue occur for you. Does it happen 100% of the time, or every once in a while?

**Comment by binary64** [comment]
Further investgation reveals this issue is only valid when the user is using the Slack iOS app to click the link that loads the React site.

If it can't be fixed I wonder how we can detect the user is loading site from Slack and say "Sorry, use Safari" or something.

**Comment by timmydoza** [comment]
Hi @binary64!

I tried to reproduce this issue in a Slack WebView and I was unable to do so. 

I do know that backgrounding the native Safari app can cause video disconnections after a long period of time. It's possible that something similar is happening in Slack but over a shorter period of time. Twilio doesn't support (or test with) Safari WebViews, so it isn't guaranteed that this app will function properly there. It's best if users can use native Safari.
