### ISSUE TITLE
Fullscreen not working on iPhone

### ISSUE THREAD

**Issue by binary64** [twilio/twilio-video-app-react#206]
**Describe the bug**
When I click the fullscreen button on iPhone, literally nothing happens. I only see the "ripple" effect from material-ui.

**To Reproduce**
1. Load the site, doesnt matter if you join or not
2. Click fullscreen button

**Expected behavior**
To go fullscreen

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] iPhone 
 - Browser: [e.g. Chrome 80, Firefox 72] Safari
 - App Version: [e.g. 0.1.0] latest
 - SDK Version: [e.g 2.1.0] latest
 - Node.js version: [e.g. 12.14.1] latest ish

**Additional context**
NEITHER of these work on the iphone:
http://fscreen.rafrex.com/
https://davidwalsh.name/demo/fullscreen.php

My suspicion is we are doing document.documentElement.requestFullscreen() but maybe it's document.requestFullscreen().... i'm not sure

They both (and this app) work on Android/PC just fine

**Comment by jhujhul** [comment]
I have the same issue on iPhone. I think it's because the Full Screen API can't be used on iPhone:
https://caniuse.com/#feat=fullscreen

**Comment by binary64** [comment]
I might have more information: it works on iPhone 8, but not iPhone 10. I have no idea what Apple is thinking. Or if there is a viable workaround.

**Comment by timmydoza** [comment]
Thanks for the info @binary64 & @jhujhul!

It looks like the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) may not be supported by all iOS browsers. The solution here is to hide the fullscreen button when the Fullscreen API is not available. I have a PR here to fix the issue: Fix ios fullscreen #212
