### ISSUE TITLE
Mock Twilio room

### ISSUE THREAD

**Issue by ivansivaklepsi** [twilio/twilio-video-app-react#215]
Hello,
this repo is great and we like using parts of it for our own video chat (although it would be a very useful library of hooks 🤞 and `VideoContext`)

I was just wondering if you know of a possibility to create a mocked room to work on call room design and other features, while not using actual Twilio integration, but rather fake video streams maybe?

Thanks

**Comment by timmydoza** [comment]
Thanks for the question @ivansivaklepsi!

It's not currently possible to mock a room to work on new features, although it would be useful. To test or develop features in the UI, I usually just join the room in multiple browser tabs. Sometimes I'll use a Puppeteer script to add virtual participants to a room. This technique is used in our Cypress tests. See [cypress/plugins/index.js](https://github.com/twilio/twilio-video-app-react/blob/master/cypress/plugins/index.js). It's possible to pull that code out and put it in a node script that you run manually. The `'--use-fake-device-for-media-stream'` Chrome flag enables these virtual participants to enter a room with mocked audio and video tracks. Can be useful for development. 

Let me know if you have any other questions. Happy to help!
