### ISSUE TITLE
Add warning on unsupported browsers (IE, non chromium edge) 

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#217]
**What is the feature that you would like to see in the app? Please describe.**
A warning for users when they are using an un-supported browser

**Is your feature request related to a problem? Please describe.**
Users on IE and older versions of edge get generic error messages and are confused why it's not working

**Describe alternatives you've considered**
Adding support for the older browsers (seems impossible) (Adding in checks myself to see if the browser is supported)

**Comment by RusseII** [comment]
https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#browser-support

Found this to see if twilio-video is supported on the users browser, just need to add the actual UI guiding users to fix the issue.

**Comment by timmydoza** [comment]
Thanks for the suggestion @RusseII!

This is a good idea. We have a ticket in our backlog to add something like this. I can try to work on the ticket soon as it should be pretty easy. Thanks for the tip!

**Comment by timmydoza** [comment]
Just merged in this PR: https://github.com/twilio/twilio-video-app-react/pull/241

It adds a warning to the app when the browser is unsupported or when the app is served over an insecure context.
