### ISSUE TITLE
Mobile screen sharing feature

### ISSUE THREAD

**Issue by Orbit-Akhil-Puri** [twilio/twilio-video-app-react#219]
**What is the feature that you would like to see in the app? Please describe.**
Is there any feature to do screen sharing on mobile? 

**Is your feature request related to a problem? Please describe.**

**Describe alternatives you've considered**

**Additional context**

**Comment by timmydoza** [comment]
Thanks for the feature suggestion @Orbit-Akhil-Puri!

Unfortunately, the Screen Capture API is not available in any mobile browsers, so we cannot add this feature. Please see the browser compatibility table for the Screen Capture API here: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API#Browser_compatibility

However, our native Android video app (https://github.com/twilio/twilio-video-app-android) does support screen sharing. Our native iOS video app (https://github.com/twilio/twilio-video-app-ios) doesn't yet have screen sharing, but it is on the roadmap and should be added within a few weeks.
