### ISSUE TITLE
iOS Safari - After user receives a phone call they can no longer be heard

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#223]
**Describe the bug**
If an iOS user is in a twilio-video room & receives a phone call, when they click decline they are disconnected from the room, and when they reconnect from the room they can no longer be heard by others in the room.

The iOS user who can not be heard still has their microphone light up as if they are speaking

**To Reproduce**
1. Join room on iPhone and a second device
2. Talk into iPhone, verify you can be heard
3. Call the  iPhone, click to decline to call
4. Talk in the room, you can no longer be heard

**Expected behavior**
iOS user should always be able to be heard

**Environment (please complete the following information):**
 - OS: iOS Latest
 - Browser: Safari Latest 
 - SDK Version: [2.4.0 ]

**Additional context**
I'm assuming this is related to https://github.com/twilio/twilio-video.js/issues/941 but I wanted to make sure. This is affecting a large percentage of our user base

Does this fall into the category of 
> 2. RemoteParticipants can't hear audio from iOS Safari after using another app (ex. Siri, Youtube etc)

**Comment by timmydoza** [comment]
Thanks for the issue @RusseII!

I can reproduce the issue you describe. It does appear to be the issue that you referenced. 

We are currently testing a workaround for this problem. The workaround can be found in the 2.6.0 release candidate of the twilio-video SDK: https://github.com/twilio/twilio-video.js/tree/2.6.0-rc1

I have run the React App with the 2.6.0 RC and it does appear to fix the issue. I'm not certain about when 2.6.0 will be released, but it ought to be relatively soon. I'll keep you posted!

**Comment by RusseII** [comment]
It looks like turning the phone on do not disturb, and changing do not disturb setting to accept calls from 'no-one' prevents this issue from happening.

**Comment by timmydoza** [comment]
Hey @RusseII - this issue has been fixed! The fix for the iOS Safari issue in included in version 2.6.0 of the twilio-video SDK. 

The fix also requires some changes to this application, which have already been applied. You can see the specific changes (with explanation) in this pull request: https://github.com/twilio/twilio-video-app-react/pull/258

We appreciate your continued participation in helping us improve this app. Please let me know if you have any questions, or if you still encounter issues. Thanks!

**Comment by RusseII** [comment]
Thanks so much @timmydoza! 

It seems to work perfectly with the audio, however it seems that sometimes the video does not automatically start publishing again.

Here is a video example on iOS 13.05 after pulling in all the changes from #258 
https://youtu.be/BhnlvzaUvUA

**Comment by timmydoza** [comment]
Thanks for that info @RusseII! 

I can reproduce that problem as well. It doesn't appear to be a problem that is specific to the React App. It may be a Safari issue or an issue with the Twilio Video SDK. 

I've created an internal bug ticket to track the problem. If you want, you could create an issue in our SDK repo for additional visibility. 

Thanks!

**Comment by timmydoza** [comment]
Hey @RusseII - just wanted to let you know that version 2.7.1 of the twilio-video SDK has been released and it includes a fix for the issue you mentioned above: https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#bug-fixes
