### ISSUE TITLE
Add comments to top of files explaining their purpose and high-level how they interact with other hooks/components

### ISSUE THREAD

**Issue by corysimmons** [twilio/twilio-video-app-react#229]
There are about 700 files that all make use of each other. I see how they're broken up into probably useful hooks, but understanding how they all work together at a slightly higher level would be really helpful for grokking how to use this library.

Right now I just have to reverse engineer what's going on and after several layers of stepping back through hooks I forget half of what I just looked at.

Thanks for your work on this. I just think adding comments to the top of files (so they don't get bloated with comments) would help a lot.

**Comment by timmydoza** [comment]
Thanks for the suggestion @corysimmons!

This sounds like a good idea. However, I don't think that I have the availability to add comments to all of the files in the project. Are there any specific files that you have questions about? I'd be happy to provide some answers here. Also, if you could pick just a handful of files that I could add comments to, what would they be?

**Comment by timmydoza** [comment]
We've captured this request in our backlog - so I'll close the issue. Please do let me know if there are any specific files that would benefit from additional comments. 

Thanks!
