### ISSUE TITLE
Passcode expired

### ISSUE THREAD

**Issue by valaykothari** [twilio/twilio-video-app-react#230]
**Describe the bug**
When i tried to login using following 
https://video-app-6636-dev.twil.io?passcode=XXXXXXXX
url i got below message

![image](https://user-images.githubusercontent.com/58423859/83787685-c7384f80-a6b1-11ea-902b-b92458d2a6b2.png)

**Comment by timmydoza** [comment]
Hi @valaykothari thanks for the issue!

The passcode for the app is supposed to expire after one week. We intentionally added this functionality as a security precaution. Please see the following notice from the project's [README](https://github.com/twilio/twilio-video-app-react#deploy-the-app-to-twilio):

> The Twilio Function that provides access tokens via a passcode should NOT be used in a production environment. This token server supports seamlessly getting started with the collaboration app, and while convenient, the passcode is not secure enough for production environments. You should use an authentication provider to securely provide access tokens to your client applications. You can find more information about Programmable Video access tokens in this tutorial. As a precaution, the passcode will expire after one week. To generate a new passcode, redeploy the app:

> `$ npm run deploy:twilio-cli -- --override`

**Comment by valaykothari** [comment]
Okay. thank you. it's working now.
