### ISSUE TITLE
Mute Unmute causing error and multiple tumbnails

### ISSUE THREAD

**Issue by asyfsaeed** [twilio/twilio-video-app-react#233]
Switching between un mute and mute is causing weird behavior 

Please check attach screen shots

![Screenshot 2020-06-05 at 11 53 28 PM](https://user-images.githubusercontent.com/5968466/83912867-033de400-a788-11ea-824c-8a02fe35f8bf.png)
![Screenshot 2020-06-05 at 11 53 16 PM](https://user-images.githubusercontent.com/5968466/83912873-0638d480-a788-11ea-876e-7cd51cc556c7.png)

**Comment by timmydoza** [comment]
Thanks for the issue @asyfsaeed! Sorry to hear that you are having issues. 

I am unable to reproduce the issue in the screenshot. It is difficult to know what the problem may be without additional information. 

Specifically, it would be very helpful to us if you could provide us with the following information:

- What steps need to be taken to reproduce this issue?
- How quickly are you switching between mute and unmute?
- What operating system and OS version are you using? 
- What browser and browser version are you using? 
- What version of the App are you using? (master branch, specific commit hash)
- What version of Node.js version are you using?

**Comment by asyfsaeed** [comment]
Hi,
1. Joined room and start switching mute and unmute
2. Two seconds between clicking mute and unmute
3. AWS Ubuntu t2.medium
4. Chrome Version 83.0.4103.97 (Official Build) (64-bit)
5. latest master code
6. 10.13.0

**Comment by asyfsaeed** [comment]
And sometime camera  video remains on even toggling camera button

**Comment by asyfsaeed** [comment]
seems like trackUnpublished causing issue when pressed frequently. any help

**Comment by timmydoza** [comment]
Thanks for the additional information @asyfsaeed!

Unfortunately, I'm still not able to reproduce this issue. However, I will soon have a fix available for a related issue that arises when the 'Mute Video' button is pressed frequrently (see https://github.com/twilio/twilio-video-app-react/issues/218). I'll keep you posted. 

Thanks!

**Comment by timmydoza** [comment]
@asyfsaeed I've merged a fix that may help your issue. Please try it out and let me know how it works for you. Thanks!
