### ISSUE TITLE
isVideoEnabled Remote Publications bug / mistake in code simple fix.

### ISSUE THREAD

**Issue by imarshmultani** [twilio/twilio-video-app-react#236]
I'm just writing quickly as i'm very much stuck in some work so not writing it as detailed bug or anything, as this issue might be faced by someone else also so it's better to be here as it's something i was able to debug and fix normally ... Sometimes remote tracks might come with capitalised names such as: 

```
screen -> Screen 
camera -> Camera 
```

in this case the **isVideoEnabled** inside **MainParticipantinfo.tsx** will always be false, so simple fix which i found is changing: 

```
const videoPublication = publications.find(p => p.trackName.includes('camera'));
const screenSharePublication = publications.find(p => p.trackName.includes('screen'));
```

to this: 

```
const videoPublication = publications.find(p => p.trackName.includes('camera') || p.trackName.includes('Camera'));
const screenSharePublication = publications.find(p => p.trackName.includes('screen') || p.trackName.includes('Screen'));
```

**Comment by timmydoza** [comment]
Thanks for the issue @imarshmultani!

I haven't encountered the issue that you describe. 

The track names are set at the following places in the app:

The camera track:
https://github.com/twilio/twilio-video-app-react/blob/master/src/components/VideoProvider/useLocalTracks/useLocalTracks.ts#L58

The screen track:
https://github.com/twilio/twilio-video-app-react/blob/master/src/hooks/useScreenShareToggle/useScreenShareToggle.tsx#L34

As long as the names are lowercase in those spots, there should be no issues. 

Track names can also be set by other apps using the Twilio Video SDK (even on native iOS or Android). Are you encountering this issue when you are in a room with users that are using different apps, or are all users using twilio-video-app-react?

**Comment by timmydoza** [comment]
Thanks for the info @imarshmultani.

Unfortunately, I still cannot reproduce the issue. I don't understand how it's happening. The track names come from hardcoded strings (from the lines of code that I provided in my comment above). It seems that the only way for these names to be capitalized is to change the hardcoded strings.

If you continue to see this issue, can you please create a new issue and fill out the issue template in its entirety? It would be very helpful to know information about your environment, and what exact steps are needed to reproduce the issue. Also, if you have been working on your own fork of the repo, a link to your code would be very helpful so I can look for the issue there. 

Thanks!
