### ISSUE TITLE
Deploying to GitHub Pages

### ISSUE THREAD

**Issue by evgar** [twilio/twilio-video-app-react#249]
Is there any solution to deploy twilio-video-app-react to GitHub Pages or any other hosting?
I was build twilio-video-app-react package locally and update local variables in .env file like this:
```
TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TWILIO_API_KEY_SID=SKXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TWILIO_API_KEY_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
Deploying steps:

```
git clone git@github.com:twilio/twilio-video-app-react.git
cd twilio-video-app-react/
npm install
twilio login
twilio plugins:install @twilio-labs/plugin-rtc
npm run deploy
```

Deploy finished successfully but y got **20101 error** while trying to join room

![Без названия (1)](https://user-images.githubusercontent.com/14876353/84990150-6565f400-b14d-11ea-94a2-70d8ee94892d.png)

**Environment:**

- OS: macOS highSierra 10.13.6
- Browser: Chrome 83.0.4103.97
- App Version: 0.1.0
- Node.js version: 12.13.1

**Comment by BishalSaha** [comment]
how did you login in didn't it ask for passcode

**Comment by BishalSaha** [comment]
<img width="1440" alt="Screenshot 2020-06-18 at 4 20 33 PM" src="https://user-images.githubusercontent.com/24563424/85011810-b68edb80-b17f-11ea-99cc-fc709db3e4be.png">

**Comment by timmydoza** [comment]
Thanks for the question @evgar!

Can you please tell me what your `npm run deploy` script does? Is it different than the `npm run deploy:twilio-cli` script? 

When you deployed your app, where is it deployed? Also, then you see the 20101 error, can you go into the network tab of the browser's development tools and inspect the `/token` request? Is there an error, or does the response payload appear to be valid?

This app needs two things to function correctly:

1. The static application assets (found in the `build/` folder)
2. A token server to dispense video access tokens

When you deploy to Github Pages, you are only able to deploy the static assets. You also will need a token server running somewhere in order for your app to be able to fetch video access tokens from it. This app includes a [token server](https://github.com/twilio/twilio-video-app-react/blob/master/server.js) which dispenses video access tokens _and_ also serves static assets from the `build` folder. You'll need to deploy this app to a platform that allows you to run a node.js server (and you can use our token server if you'd like, or you can just use it as a reference).

Also, I'd advise against deploying this to a publicly accessible site without some kind of authentication mechanism. When this app is hosted publicly without authentication, then anybody can connect to rooms and incur charges on your account. This is why our Twilio CLI quick deploy feature uses a passcode authentication mechanism. 

Good luck! Please let me know if you have any other questions!

**Comment by ellenlowing** [comment]
How about when deploying to Heroku? 
Tried running `node server.js` and `concurrently npm:server npm:react-start` but both returns Invalid Access Token (20101).

**Comment by timmydoza** [comment]
If you're curious @evgar, there is some good discussion in this thread about deploying the app to Firebase: https://github.com/twilio/twilio-video-app-react/issues/187

**Comment by timmydoza** [comment]
Closing issue as question appears answered. I'm happy to continue the discussion if you have more questions!!
