### ISSUE TITLE
Custom login

### ISSUE THREAD

**Issue by noriega2112** [twilio/twilio-video-app-react#261]
Does anyone has implemented a custom login to authorize users?

**Comment by timmydoza** [comment]
Hi @noriega2112 - thanks for the question!

If you're interested, there is some interesting discussion in this thread about adding Firebase authentication: https://github.com/twilio/twilio-video-app-react/issues/187

Near the end of that thread, another github user leaves their solution for how they got things working. 

Additionally, our quick deploy feature lets you authorize users with a passcode. Have you tried that? Here is a youtube video to show you how to get started: https://www.youtube.com/watch?v=pSASQcHrmPg

Please let me know if you have any other questions!
