### ISSUE TITLE
Multiple video tracks

### ISSUE THREAD

**Issue by bojantv** [twilio/twilio-video-app-react#262]
**Describe the bug**
Multiple tracks appear for the same video with a different name and sid.

**To Reproduce**
1. Open app
2. Join room
3. Start clicking on the camera button to turn the video on and off repeatedly
4. Observe new video tracks showing up in the publications list and in HTML

**Expected behavior**
No additional video tracks should appear, it should only be a total of one video track.

**Screenshots**
![image](https://user-images.githubusercontent.com/58706872/86521324-215e3900-be47-11ea-9469-5b97f638e725.png)
![image](https://user-images.githubusercontent.com/58706872/86521376-de509580-be47-11ea-98bc-e50da69c39ea.png)

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome 83
 - App Version: 0.1.0

**Additional context**

**Comment by timmydoza** [comment]
Thanks for the issue @bojantv!

Unfortunately, I am unable to reproduce the issue that you describe. 
One thing that I noticed, is that the `data-cy-participant` attribute outputs a different value than it should. For me, is just lists the participants identity `data-cy-participant="timmydoza"`. For you it lists a whole object. This difference isn't related to your bug, but it makes me wonder if you are running a different version of the code than me.

Just curious, have you made any modifications to the code base? If you have, is it possible for you to leave a link to your repo? I'd be better able to help you if I could see your modifications.  

Thanks!

**Comment by bojantv** [comment]
Hi, @timmydoza thanks for responding. I manually added that JSON string as identity, different reasons. I was using your app clean, no modifications whatsoever. By just clicking on the video on/video off eventually a double video will appear though they will be layered one on top another so it's very hard to notice it until you check HTML. If you switch from absolute to relative position the other video would appear underneath. Give it another go, please. It takes 10-20 clicks, I'm sure the other video will appear.
I've just reproduced it again clean the latest code, "test" as identity. Just go wild on that camera button (obviously we don't use it like that but in some instances, id does happen with normal usage)

![image](https://user-images.githubusercontent.com/58706872/87034705-3557c100-c1e0-11ea-9201-ddcc90647e74.png)

**Comment by timmydoza** [comment]
Thanks for the info @bojantv!

Looks like I can reproduce the issue. I have to click that button as fast as I can for a few seconds before I see the issue. I'll take a look when I get a chance, but this issue will get lower priority since it only seems to occur with more extreme usage of the Mute Video button. 

Thanks again!

**Comment by bojantv** [comment]
Great that you managed to reproduce it. That certainly is extreme usage, the thing is that it started showing in normal use, like when someone refreshes the browser or when then turn the video off and then on again, it's very rare to be fair but it does happen on normal usage. I understand it's a lower priority especially with masking the problem with absolute positioning. I just wanted you to become aware of the issue. Thanks.

**Comment by timmydoza** [comment]
I see. Thanks for that additional info!

**Comment by timmydoza** [comment]
Hey @bojantv - I've increased the throttle interval in the `ToggleVideoButton` component from 200 to 500. This should help with the issue you reported. 

Thanks!
