### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by ciptoj** [twilio/twilio-video-app-react#263]
Hi,
I think I've followed all what you said, running serverless in the cloud is working fine.

But for running in local, when I do npm start, the https://localhost:3000 is just blank
in browser it says "Invalid response"

and running "Npm run start", only resulted in blank page.
What could goes wrong?

**Comment by ciptoj** [comment]
So I guess I can access it by using http://Ipaddress:3000.

but it's asking for passcode.
I don't see that when I did a npm run start locally, it prints out the passcode?

**Comment by ciptoj** [comment]
and then if I deploy a twilio App, it includes server js?
So how do I call the API of deployed in twilio app "/Token"?
I want to create room, and auth user to be able to sign in to that room

**Comment by timmydoza** [comment]
Thanks for the issue @ciptoj!

Sorry to hear that you are having problems running the app. 

To view the app locally, be sure to visit `http://localhost:3000`, not `https://localhost:3000`.  Be sure to use `http` when visiting `localhost`. 

For your other questions - I'm happy to help but I'd need some more information. I would need some more information about your environment, what commands you have tried, and what specific error messages you are seeing. Can you please create a new issue and use our Bug Report template? Please fill out that template with as much information that you can.

Thanks!
