### ISSUE TITLE
Join/Start call without presssing "Join Now" Button

### ISSUE THREAD

**Issue by faiyaz-ergo** [twilio/twilio-video-app-react#264]
Hi,
Is it possible to start/join a call without pressing "Join Now" button in the Twilio react app?

In my application, I'm providing a "Call Now" button linked with my Twilio react application instance along with their name and room id/name in URL parameter. i.e. <twilio_react_app_domain>?name=john&room=1213
When users click on the "Call Now" button in my application it takes users to the twilio react app's landing page. Then users need to click "Join Now" button to start the call, which collects participant's name and room id from URL param and joins them to that room where other have joined in the same process.

Now I want to remove this additional "Join Now" button click in Twilio react app landing page. The expectation is to,  Upon clicking "Call Now" button users will redirect to my twilio react app instance join the room automatically and start talking with others available in the room. 

Thanks in advance.

**Comment by timmydoza** [comment]
Hi @faiyaz-ergo - thanks for the question!

It is possible to do this, but it is not recommended. 

Browsers have an autoplay policy which requires a user interaction (such as clicking on the page) before audio elements can start to play sound. When a users joins a room immediately, audio elements are added to the DOM before there has been any user interaction, and thus no sound can be heard. This may or may not cause issues - it depends on your [Media Engagement Index](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

An additional problem is that the user may join a room before they have granted permissions to the app to use their microphone and camera. This means that they join a room without publishing any audio or video to the room. Once they are in the room and grant access to their mic and camera, the app doesn't know to then publish those tracks to the room. This app assumes that it will have access to the user's mic and camera before the user clicks the 'Join Room' button, so we'd have to update some logic in the app to handle this auto-join scenario.

Also, we feel that it's a good user experience to have users join a room by clicking a Join Room button. For example, users may like to first look at their video preview to make sure their hair looks good before they join a call. It's a good practice to have users preview their input devices before they join a room.

Please let me know if you have any other questions! Happy to help!
