### ISSUE TITLE
Twilio Video call Notifications

### ISSUE THREAD

**Issue by rustam11323** [twilio/twilio-video-app-react#265]
Hi there,

I couldn't find the documentation for building a video call with Twilio. I want to build a video call option for the users and when the users click to video call icon agents will receive notifications in order to answer or decline the call. Could you please help me?

Thanks,

**Comment by timmydoza** [comment]
Thanks for the question @rustam11323!!

Unfortunately, there is no functionality in our Twilio-Video Javascript SDK for providing notifications to agents. This is something that you would have to build using whichever tools that fit your needs. 

One Twilio feature that may be useful is the [Status Callbacks](https://www.twilio.com/docs/video/api/status-callbacks) feature of our [Programmable Video REST API](https://www.twilio.com/docs/video/api). This feature allows you to specify a URL that will receive HTTP requests whenever Video Rooms are created, ended, and many other things.
