### ISSUE TITLE
Requirement should be node engine >=10.19.0 and not 10+, as the serverless-api dependency requires the later version of NodeJS

### ISSUE THREAD

**Issue by adamchasetaylor** [twilio/twilio-video-app-react#270]
**Describe the bug**

When trying to install this plugin, I run into an incompatible Node version message.

It looks like this is because the serverless-plugin which this has a dependency on, has a dependency on a later version of Node.

The docs her say the requirement is Node 10, but it actually is >=10.19.

C02ZG1USLVDT:~ adtaylor$ twilio plugins:install @twilio-labs/plugin-rtc
warning @twilio-labs/plugin-rtc > @twilio-labs/serverless-api > @types/form-data@2.5.0: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.
error got@11.5.0: The engine "node" is incompatible with this module. Expected version ">=10.19.0". Got "10.17.0"
error Found incompatible module.
Installing plugin @twilio-labs/plugin-rtc... !
    Error: yarn add @twilio-labs/plugin-rtc@latest --non-interactive --mutex=file:/Users/adtaylor/.twilio-cli/yarn.lock --preferred-cache-folder=/Users/adtaylor/.twilio-cli/yarn --check-files exited with code 1

**To Reproduce**
1. nvm use 10.17.0
2. twilio plugins:install @twilio-labs/plugin-rtc

**Expected behavior**
plugin-rtc should be installed

**Environment (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Node.js version: 10.17.0

**Comment by timmydoza** [comment]
Hey @adamchasetaylor - thanks for the info! I'll take a look at this and update the docs accordingly.

**Comment by mgiorgi-github** [comment]
Same issue
