### ISSUE TITLE
Passcode has expired

### ISSUE THREAD

**Issue by talktojoegee** [twilio/twilio-video-app-react#273]
I've been facing this issue for a while now. After going through the all process of setting up a video app as instructed. When I enter the passcode I receive this message: Passcode has expired. Something I just created a moment ago. I learnt it expires after 7 days. What's the issue here?

**Comment by timmydoza** [comment]
Thanks for the question @talktojoegee!

The passcodes used for our quick deploy solution expire after 7 days. It's a security feature. It is possible to generate a new passcode if you'd like.

If you already have a video app deployed, you can run `npm run deploy:twilio-cli -- --override`. This will re-deploy the app to the same url as before, but with a new passcode. 

Give this a try and let me know how it works!

**Comment by aaalaniz** [comment]
We will close this issue for now @talktojoegee 

Thank you for reporting the issue. Please reopen if you have any additional questions or comments.

**Comment by marcelcunha1991** [comment]
How can I generate a new passcode?

**Comment by ikkisoft** [comment]
`npm run deploy:twilio-cli -- --override`
