### ISSUE TITLE
Status Callback

### ISSUE THREAD

**Issue by binary64** [twilio/twilio-video-app-react#277]
**What is the feature that you would like to see in the app? Please describe.**
I'm trying to find where I can set the `status_callback` and `status_callback_method` for joining of the room.

**Describe alternatives you've considered**
I looked for a global callback for the whole account on the Twilio site, but I could only find one where it triggers on a threshold, rather than per each room event globally.

**Additional context**
I notice in @types/twilio-video there is some error handlers for `StatusCallback`, but nothing else that calls it.

**Comment by timmydoza** [comment]
Hi @binary64 thanks for the question!

The status callback and method cannot be set with the React App or Javascript SDK. It can be set in the Twilio Console if you go to Programmable Video > Rooms > Settings:

![image](https://user-images.githubusercontent.com/12685223/88860178-724c1d80-d1b8-11ea-8ac9-4d51091457e9.png)

Additionally, if you are using the REST API to create rooms, you can set the status callback there: https://www.twilio.com/docs/video/api/status-callbacks

Please let me know if you have any other questions! Thanks.
