### ISSUE TITLE
Guidance on deploying to different environments

### ISSUE THREAD

**Issue by BenMiriello** [twilio/twilio-video-app-react#284]
The given deploy scripts have worked for me, though I ran into a lot of trouble when I tried to set up multiple environments for the same app. I want to be able to deploy to different environments for the usual reasons.

The script `deploy:twilio-cli` which runs the command `twilio rtc:apps:video:deploy` creates a new hosted service, environment, function, function version, build, and deployment. That's great at the start. But the twilio rtc commands don't give us control over which url or 'environment' we're posting to.

To set up a new environment, I followed the instructions in the [docs](https://www.twilio.com/docs/runtime/functions-assets-api/api/service). Eventually I was able to create new environments with new urls and their own builds and deployments, but those urls only show me 'Not found'. 

There are a few places along the way where I may have made mistakes. For one: When setting a new function version, as described [here](https://www.twilio.com/docs/runtime/functions-assets-api/api/function-version), you need to give it 'Content' and a 'path'. Is the content supposed to be the whole React app? I don't have any 'functions' in my version of the app, since I'm using my own custom external token server. I tried setting content to '.', hoping that would reference the whole app from the root directory. I wouldn't be surprised if this was incorrect but I've found no no guidance on how it should be done when deploying a whole react app. I also set the path to '/'.

Ultimately what I'd love is to be able to write my own deploy scripts so I can deploy to different environments without having to repeatedly work through the many layers of the twilio cli and keep track of heaps of sids, though if I could get it working at all that would be a great start.

Sorry for the long description, but I've been working on this for hours and I'm pretty lost and wanted to be clear on where the issue is and what I've tried so far. Thanks for your time reading and responding!

**Comment by timmydoza** [comment]
Thanks for the question @BenMiriello!

If we built some new features into our CLI tool used for deploying the video app, I'm curious about what you'd like to see. Would it be helpful if we added command-line arguments that let you change the service name and/or environment? For example, would this be useful?

If you ran
`npm run deploy:twilio-cli -- --app-name my-awesome-test-app`
it could deploy to `https://my-awesome-test-app-1234-5678-dev.twil.io`

Or you could add an `--environment` argument to change environments:
`npm run deploy:twilio-cli -- --app-name my-awesome-test-app --environment stage`
it could deploy to `https://my-awesome-test-app-1234-5678-stage.twil.io`

Would these features be useful to you? I'm not sure if we'll add them to the roadmap, but we're trying to gauge community interest. 

Looking forward to hearing your thoughts.  Thanks!

**Comment by BenMiriello** [comment]
Hi Timmy thanks for your response and your suggestion. Yes that's exactly what I was hoping for. I understand you don't have time build in every feature but for me that would be massively helpful. For now we've switched to hosting elsewhere since I don't know a way to deploy a staging version through Twilio. I'd still like to use Twilio serverless hosting and would be happy to switch back if such a script were available. Without it, though, I don't know how I could be confident deploying new versions.

If there is a currently suggested way to deploy to different environments, please let me know. If there really isn't any working method currently then I have to assume I'm not the only one having this issue.

I'll leave this issue open for the moment in case there is a current suggested method, but otherwise feel free to close it. Thanks again.

**Comment by timmydoza** [comment]
Thanks for the feedback @BenMiriello!

I'll let my team know that there's some community interest in this feature. 

If we do implement this feature, it might not happen for a few weeks. So I'm happy to hear that you were able to get this app hosted elsewhere. 

Our quick-deploy solution (`npm run deploy:twilio-cli`) that we ship with this app isn't intended to be used for any long-term or production deployments. It's really for demo purposes only, which is why the passcode expires after one week. Also, this quick deploy solution needs to also work with our [iOS](https://github.com/twilio/twilio-video-app-ios) and [Android](https://github.com/twilio/twilio-video-app-ios) video apps. So if you deploy a token server to a different Twilio service or environment, it will not work with our mobile apps because the token server URL will have different format. 

Just wanted to shed some color on our quick deploy solution. But I will share your feedback with the team to see if there's anything we can come with.

**Comment by timmydoza** [comment]
Closing this issue as this feature isn't on our roadmap. 

However, if you want to change the service name or environment that you deploy with, that can be done with the following steps:

- Uninstall plugin if installed from NPM `twilio plugins:uninstall @twilio-labs/plugin-rtc`
- Clone the plugin-rtc repo `git clone https://github.com/twilio-labs/plugin-rtc.git`
- Run `npm install` inside repo directory
- Install local twilio plugin `twilio plugins:install <path_to_repo>`. See: https://github.com/twilio-labs/plugin-rtc#install-the-plugin-for-local-development

Now when you run plugin commands, it will use the locally installed plugin. You can change the code in the plugin-rtc repo and the changes will take effect immediately. You won't need to reinstall the plugin. 

You can change the service name and token expiry here: https://github.com/twilio-labs/plugin-rtc/blob/master/src/constants.js
And you can change the serverless environment here: https://github.com/twilio-labs/plugin-rtc/blob/master/src/helpers.js#L174
