### ISSUE TITLE
Implementing Video Filters (Blur, VIrtual Background) 

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#287]
**What is the feature that you would like to see in the app? Please describe.**
Are options for blur / virtual background something you have considered adding into twilio-video-app-react ? 

**Is your feature request related to a problem? Please describe.**
Many of our users are requesting a way to have a blurred or virtual background.

**Related Threads:**
https://github.com/twilio/video-quickstart-ios/issues/409  
https://github.com/twilio/twilio-video.js/issues/953

**Comment by jzombie** [comment]
Use TensorFlow.js or something of the like.  I seriously doubt they're going to implement it in this demo app.

**Comment by timmydoza** [comment]
Hey @RusseII!

Thanks for the feature request. Unfortunately this feature is not on the roadmap for this app, but I'll let the team know that there is community interest in this feature. 

As for implementing the feature, I've seen other apps use this [drawBokehEffect](https://github.com/tensorflow/tfjs-models/tree/master/body-pix#bodypixdrawbokeheffect) function from this library: https://github.com/tensorflow/tfjs-models/tree/master/body-pix

**Comment by timmydoza** [comment]
Closing this - as this feature is not on our roadmap.

**Comment by nithingeorge3** [comment]
Hi Team, I would like to integrate Virtual background for video call in iOS app side. Could you please help me on this
