### ISSUE TITLE
How to use mobile view in desktop browser

### ISSUE THREAD

**Issue by pravishanth** [twilio/twilio-video-app-react#295]
Hi,
Twilio video renders video in two views, desktop and mobile, based on the device.
Due to space constraints on my desktop application I would like to render the video similar to that of a mobile on desktop, Is this possible? Is there a variable that I could set to allow me to do this ? I would like Twilio video to think that I am running the app on the mobile

**Comment by timmydoza** [comment]
Thanks for the question @pravishanth!

Fortunately, this is easy to accomplish. We are using the [Material UI](https://material-ui.com/) library in this app, and this library lets you easily change the breakpoints that are used to change the styling at smaller screen widths. You can customize these breakpoints in `src/theme.ts`. Just add this object to the `createMuiTheme` function:

```
  breakpoints: {
    values: {
      xs: 0,
      sm: 600,
      md: 960,
      lg: 1280,
      xl: 1920,
    },
  },
```

We use the `sm` breakpoint to show the mobile view. So with the above object, you'll see the mobile view in browsers that have a width of 600px or less. You can increase that number to show the mobile view at larger browsers widths. This is what the `createMuiTheme` would look like if you want to show the mobile view in browsers that have a width of 1200 pixels or less:

```
export default createMuiTheme({
  breakpoints: {
    values: {
      xs: 0,
      sm: 1200, // <-- edit this one
      md: 960,
      lg: 1280,
      xl: 1920,
    },
  },
  palette: {
    type: 'dark',
    primary: {
      main: '#F22F46',
    },
  },
  sidebarWidth: 260,
  sidebarMobileHeight: 90,
});
``` 

Note that typescript requries all values to be present, even though we only want to change `sm`. If you want to see the mobile view in all desktop browsers, you can just make this number very high: `sm: 10000`.

More information about breakpoints here: https://material-ui.com/customization/breakpoints

**Comment by pravishanth** [comment]
I tried it out in Twilio-Video-App-React app with the breakpoints but the view doesn't change. Does it work for you ?
