### ISSUE TITLE
How to set the group room type for small group (upto 4 participants)

### ISSUE THREAD

**Issue by pravishanth** [twilio/twilio-video-app-react#296]
How to set the group room type to small group (upto 4 participants), the app is currently defaulting to group room (50 participants), I came to realise this after I was billed 1 cent/participant minute.

**Comment by timmydoza** [comment]
Hi @pravishanth - thanks for the question!

The default room type, which is used to determine the room type of ad hoc rooms (rooms created without the Rooms Rest API) can be changed in the Twilio Console. Go to Video > Rooms > Settings > Room Topology, and make your selection in the Room Type dropdown menu. 

Also if you are using our quick deploy feature with `npm run deploy:twilio-cli`, you can now specify the room type with the `--room-type` argument. To deploy a video app that uses small group rooms, run this command: 

`npm run deploy:twilio-cli -- --room-type group-small`

(note the extra `--` that's needed)

This will deploy a new video app that uses small group rooms. This doesn't change your default room type, so only this deployed video app will use small group rooms.  

Also this is a new feature of our CLI tool, so you may need to update your CLI plugin in order for this feature to work. To upgrade, run `twilio plugins:update`.
