### ISSUE TITLE
javascript version hope?

### ISSUE THREAD

**Issue by manishoctal** [twilio/twilio-video-app-react#297]
**What is the feature that you would like to see in the app? Please describe.**
This is a good repo, but in typescript, Maybe everyone does no know typescript just like me, Can we have a native javascript version of this?

**Is your feature request related to a problem? Please describe.**
I need a normal javascript code for this repo.

**Describe alternatives you've considered**
Create react app with javascript

**Additional context**

**Comment by timmydoza** [comment]
Thanks for the question @manishoctal!

Unfortunately we do not plan on releasing a javascript version of this application. 

However, I do want to encourage you to give typescript a try! If you use VSCode, it should be very easy (and I'm sure other editors support TypeScript as well). If you use VSCode and have TypeScript installed (you can install it with `npm install -g typescript`), then you should be able to edit and run this app with no problems. More information here: https://code.visualstudio.com/docs/languages/typescript

Good luck!
