### ISSUE TITLE
Twilio-video not working in firefox

### ISSUE THREAD

**Issue by chaudharidpka** [twilio/twilio-video-app-react#298]
Can someone help with this error in console form twilio video js sdk. I am using
 "twilio": "^3.48.0",
  "twilio-video": "^2.7.0"
2020-09-02 22:15:59.072Z | ERROR in [connect #1]: createAndOffer() failed: TypeError: this._peerConnection.addTransceiver is not a function
Stack trace:
_addOrUpdateTransceiver@webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/peerconnection.js:499:14
addMediaTrackSender@webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/peerconnection.js:1326:27
_getOrCreate@webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/peerconnectionmanager.js:220:9
createAndOffer/<@webpack-internal:///./node_modules/twilio-video/es5/signaling/v2/peerconnectionmanager.js:265:16
![Screen Shot 2020-09-02 at 3 21 19 PM](https://user-images.githubusercontent.com/13144397/92042895-fd788000-ed2f-11ea-9b0b-ac61c48b0ef9.png)

**Comment by timmydoza** [comment]
Thanks for the issue @chaudharidpka. Unfortunately, I don't have enough information about your issue to help out. Can you please create a new issue and fill out our issue template in full? It would be very helpful if you could provide information such as:

- What browser version you are using
- What software are you running in the browser (is it our React App?)
- What steps can be taken to reproduce the issue

There are more prompts in the issue template, so please use that as your guide. Thanks!!!
