### ISSUE TITLE
How to detect which participant - local or remote goes to "reconnecting" state.

### ISSUE THREAD

**Issue by rachnaban** [twilio/twilio-video-app-react#303]
I am working on showing a page to the either side  of one to one room if either of the participant goes to reconnecting state. I observed that as soon as any one participant goes to reconnecting state, useRoomState() gives the roomState as reconnecting almost immediately but as we have to identity which participant is reconnecting so we added the hooks below but still they take around 3-4 seconds to give the result, so this gives the other side a blank screen which is not a good experience.

In case of local Participant, I am using the hook below:

```
export default function useIsLocalParticipantReconnecting() {
    const [isReconnecting, setIsReconnecting] = useState(false);
    const { room } = useVideoContext();
    useEffect(() => {
        if (room.localParticipant) {
            const handleReconnecting = () => setIsReconnecting(true);
            const handleReconnected = () => setIsReconnecting(false);

            room.localParticipant.on('reconnecting', handleReconnecting);
            room.localParticipant.on('reconnected', handleReconnected);
            return () => {
                room.localParticipant.off('reconnecting', handleReconnecting);
                room.localParticipant.off('reconnected', handleReconnected);
            };
        }
    }, [room]);
    return isReconnecting;
}
```
In case to detect remote participant reconnection:

```
const [isReconnecting, setIsReconnecting] = useState(false);
    useEffect(() => {
        const handleReconnecting = () => setIsReconnecting(true);
        const handleReconnected = () => setIsReconnecting(false);

        room.on('participantReconnecting', handleReconnecting);
        room.on('participantReconnected', handleReconnected);
        return () => {
            room.off('participantReconnecting', handleReconnecting);
            room.off('participantReconnected', handleReconnected);
        };
    }, [room]);
```

@timmydoza  , Can you please  help here and let me know if I am missing something here?  Request your help to let me know if this is not the correct way to identity this state. Thanks !

**Comment by timmydoza** [comment]
Thanks for the question @rachnaban! Your implementation looks like it will do the trick. Unfortunately, it does take a few seconds for our signaling servers to detect that that a remote participant is reconnecting. I don't think there's any way around the 3-4 second delay that you mentioned. 

Your first hook is basically the same as the `useRoomState()` hook, with one small difference:

The `useRoomState()` will change to `reconnecting` when there has been an interruption in the localParticipant's signaling or media. 

Your top hook will change to `reconnecting` when there has been an interruption in the localParticipant's signaling (but not media). 

They are pretty similar. Our React App uses `useRoomState()` to detect a local reconnection. 

The second hook looks good too, but if you want to detect which participant is reconnecting, then you can use the argument provided in the `participantReconnecting` event:

```
room.on('participantReconnecting', participant => {
  console.log(participant.identity + ' is reconnecting to the Room');
});
```

Also, be sure to look at our `useIsParticipantIsReconnecting` hook: https://github.com/twilio/twilio-video-app-react/blob/master/src/hooks/useParticipantIsReconnecting/useParticipantIsReconnecting.ts

It accepts a `participant` as an argument, and then uses `participant.on('reconnecting', () => {})`. It's basically the same as your second hook - it's just an alternative way of doing things. This hook is used by our `ParticipantConnectionIndicator` component: https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ParticipantInfo/ParticipantConnectionIndicator/ParticipantConnectionIndicator.tsx

**Comment by rachnaban** [comment]
Thank you so much, @timmydoza . What i observed is RoomState goes to reconnecting not only when localParticipant goes for reconnection but remoteParticipant as well. I mean if my remote Participant goes for reconnection then roomState is showing as "reconnecting" at both the ends. Is this expected or I am missing something here.

**Comment by timmydoza** [comment]
Hmm, that's not the expected behavior of `useRoomState()`. This hook should only change to `reconnecting` when the localParticipant is having a connection interruption. 

https://media.twiliocdn.com/sdk/js/video/releases/2.7.0/docs/Room.html#event:reconnecting__anchor

Just curious, but are you doing something to test these hooks? Are you doing something to trigger the `reconnecting` state in order to test the application.

**Comment by rachnaban** [comment]
Thanks for your response @timmydoza , If my remote Participant is interrupting his connection , in his console logs , he is getting roomState as reconnecting and at my end also, I am getting "reconnecting" in my console log.  Currently I am testing in this way only.

**Comment by timmydoza** [comment]
Sorry about the delay @rachnaban. Are you still experiencing this issue?

I was curious about how you are triggering the `reconnecting` state. Are you turning off your wifi and then turning it back on? Or are you using a network throttling tool?

**Comment by rachnaban** [comment]
I am closing this issue now as after changing the room type to small group, my issue is resolved. Thanks @timmydoza !
