### ISSUE TITLE
Capture a frame of the videotrack

### ISSUE THREAD

**Issue by VinnyFuelhq** [twilio/twilio-video-app-react#305]
I would like to access and download a frame of the videotrack, similar to this fiddle: https://jsfiddle.net/gkkzvt4x/

**Is your feature request related to a problem? Please describe.**
During a conversation, or in the LocalVideoPreview, I would like to enable a person to take a screenshot of the video, from a button in MenuBar.tsx.

**Describe alternatives you've considered**
https://github.com/niklasvh/html2canvas works perfectly for images, but not with videos, so far. https://jsfiddle.net/gkkzvt4x/ looks promising, I just don't need how to access the Twilio video frame.

**Comment by K12AZ** [comment]
I am also trying to capture frames, but unable to do.

**Comment by timmydoza** [comment]
Thanks for the feature request @VinnyFuelhq!

This feature isn't on our roadmap, so we won't be adding it to the app. But I have some code for you that will hopefully help!

I made some functions:

```
function captureVideoFrame(video) {
  const canvas = document.createElement('canvas');

  canvas.width = video.videoWidth;
  canvas.height = video.videoHeight;

  canvas.getContext('2d').drawImage(video, 0, 0);

  const dataUri = canvas.toDataURL('image/jpeg', 0.92);
  const data = dataUri.split(',')[1];
  const mimeType = dataUri.split(';')[0].slice(5);

  const bytes = window.atob(data);
  const buf = new ArrayBuffer(bytes.length);
  const arr = new Uint8Array(buf);

  for (let i = 0; i < bytes.length; i++) {
    arr[i] = bytes.charCodeAt(i);
  }

  const blob = new Blob([arr], { type: mimeType });
  return { blob: blob, dataUri: dataUri };
}

function saveBlob(blob, filename) {
  const a = document.createElement('a');
  document.body.appendChild(a);
  a.style = 'display: none';

  url = window.URL.createObjectURL(blob);
  a.href = url;
  a.download = filename;
  a.click();
  window.URL.revokeObjectURL(url);
}
```

These functions can be used to capture a video frame as a blob or dataUri and save a jpg to your computer. You can use them like this:

This app adds `data-` attributes to certain elements for testing purposes. Here we can use these attributes to select the video of certain participants. For example, if I (timmydoza) was in a room, you could get a video frame like this:
```
const videoEl = document.querySelector('[data-cy-participant="timmydoza"] video');
const { blob, dataUri } = captureVideoFrame(videoEl);
saveBlob(blob, 'shapshot.jpg');
```

This should download a file called `snapshot.jpg` to your computer.

If you want to capture a video frame of the main participant, then you can use this to get the video element: 
```
const videoEl = document.querySelector('[data-cy-main-participant] video');
const { blob, dataUri } = captureVideoFrame(videoEl);
saveBlob(blob, 'snapshot.jpg');
```

Let me know how this works out for you!
