### ISSUE TITLE
Override trackName of remoteTracks, encountered blank small preview remote tracks

### ISSUE THREAD

**Issue by masterbater** [twilio/twilio-video-app-react#307]
Hello I encountered some issues where I made a call from PC to an android app. 
The remote tracks have different trackName  and you use this code
 `const videoPublication = publications.find(p => p.trackName.includes('camera'));`
to check if videoEnabled or not. And this affects the preview window of remote if the trackname does not start with a trackname camera-
I change the code to
 `const videoPublication = publications.find(p => p.trackName && !p.trackName.includes('screen'));`

But I notice that this kind of expected substrings in a trackName could cause some issues with the state of video. Screenshare also has an issue where in the receiving android app cause glitch between of the video feed and the screen share feed.
I am still looking on why does the web sends both the video and screen share feed to the receiving end in android app or ios app. The expected substrings that exist in trackName might be the cause of this.

**Comment by timmydoza** [comment]
Thanks for the question @masterbater!

I think there's one important thing to know here: the `trackName` field is always populated. 

When you create a new track and _don't_ specify a name, then the SDK automatically creates a random ID to use for the `trackName` property. So in your code:

`const videoPublication = publications.find(p => p.trackName && !p.trackName.includes('screen'));`

This will always be `true`, unless the `trackName` includes `'screen'`. 


>why does the web sends both the video and screen share feed to the receiving end

Our app sends both tracks (camera and screen) at the same time. When the user is sharing their screen, we will display their camera track as a thumbnail in the participant list, and we will display their screen track in the main video area. 

This pattern of using `trackName` to differentiate between `screen` and `camera` tracks is also used in our iOS and Android video apps. I recommend taking a look at them if you haven't yet:

https://github.com/twilio/twilio-video-app-ios
https://github.com/twilio/twilio-video-app-android

Please let me know if this helps solve your issue!
