### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by hsavit1** [twilio/twilio-video-app-react#310]
**Describe the bug**
Does this application support samsung internet? If no, why not?

**Comment by hsavit1** [comment]
update: it doesn't - [see](https://github.com/twilio/twilio-video.js#browser-support)

**Comment by timmydoza** [comment]
Thanks for the question @hsavit1!

As you found out - we don't officially support the Samsung browser. It's possible that this app may work in it, but since we don't test with this browser, we cannot make any guarantees.
