### ISSUE TITLE
Audio Output Devices is empty on cellphone browser(both android and iPhone, happens on Chrome and Firefox), but pc browser is good

### ISSUE THREAD

**Issue by cengit** [twilio/twilio-video-app-react#311]
**Describe the bug**
Audio Output Devices list is empty on cellphone browsers(both android and iPhone, happens on Chrome and Firefox), but pc browser is good.

**To Reproduce**
1. open the site using chrome/ Firefox in your cellphone, plugin your headphone
2. Click setting option in the menu, you can see setting popup layer is visible
3. Check the Audio Output dropdown
4. No Audio Output devices found, it just display "Default"

**Expected behavior**
all available Audio Output devices should be list in the dropdown

**Screenshots**
http://demo.cenday.com/twilio-output-device-none.jpg
http://demo.cenday.com/twilio-output-device.jpg

**Environment (please complete the following information):**
 - OS: android 10
 - Browser: [Chrome 85.0.4183.121 (64bit)] Firefox and iPhone safari also reproduce
 - SDK Version: twilio-video-2.7.0

**Additional context**
this issue only happen on cellphone, when open it pc browsers, it's fine though.

**Comment by cengit** [comment]
in this case: **when the output devices is default, the phone speaker is using as the audio output.**
even though I have plugin the headphone, but I can NOT switch the output to the headphone or bluetooth headset

**Comment by PeagaOS** [comment]
@cengit seems like I am having the same problem. When I tried to use directly in browsers, sounds to work. When I set it inside a webview on React Native, the audio from mobile devices does not come out.

**Comment by timmydoza** [comment]
Thanks for the issue @cengit!

I think that what you describe is expected behavior. This app can only display a list of audio output devices when `navigator.mediaDevices.enumerateDevices()` returns more than one audio output device. When I run the following code on mobile chrome:

```
  navigator.mediaDevices.enumerateDevices().then(deviceList => {
    const audioOutputDevices = deviceList.filter(device => device.kind === 'audiooutput');
    console.log(audioOutputDevices);
  });
```
it displays an array that contains one audio output device, even though I actually have multiple devices available on the phone. 

Unfortunately, mobile browsers limit the number of devices that are available to this app. There's nothing that we can do to fix this since the browser doesn't let the app 'see' more than one audio output device.

**Comment by cengit** [comment]
thanks for the comment, @timmydoza

**Comment by xeiaaa** [comment]
@timmydoza so how are we going to allow the users to change their audio device if there's nothing retrieved?

**Comment by timmydoza** [comment]
Hi @xeiaaa - thanks for the question. 

In this case, it unfortunately isn't possible for users to change their output device. This app can only knows what the browser is telling it, and the browser is telling it that there is only one audio output device. With that, it isn't possible to change devices. It's a limitation we face with mobile browsers, unfortunately.
