### ISSUE TITLE
Memory leaks from timeout w/o time

### ISSUE THREAD

**Issue by nionis99** [twilio/twilio-video-app-react#315]
Getting memory leak after room.disconnect , cause there is setTimeOut w/o time. 

useRoom.tsx

SS
![image](https://user-images.githubusercontent.com/27200994/94712578-5a2c8200-0352-11eb-90f8-1e856d3fc23b.png)

**Comment by timmydoza** [comment]
Thanks for the comment @nionis99.

To the best of my knowledge, calling `setTimeout` without a delay parameter is not a a sign of a memory leak. In fact, according to the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout), calling `setTimeout(myFunction)` is the same as calling `setTimeout(myFunction, 0)`.
