### ISSUE TITLE
Group chatting Functionality

### ISSUE THREAD

**Issue by rajkumar73443** [twilio/twilio-video-app-react#326]
Can you Add group chatting functionality this project.

**Comment by timmydoza** [comment]
Thanks for the feature suggestion @rajkumar73443!

We are considering adding a chat feature to the app. We're still discussing it, so I don't think the feature will be added until 2021. 

In the meantime, I wrote a blog post about how to use DataTracks to add simple chat functionality to this app. You can see the blog post here: https://www.twilio.com/blog/open-source-video-app-reactjs-datatrack-snack-chat

And you can see the code that the blog post references here: #317 

Note: The "Snack Chat" feature that is described in the blog post uses DataTracks to send chat messages to other participants in a room. The messages sent over DataTracks are ephemeral. This means that you will be unable to see any messages that were sent before you joined the room. Next year, we will likely use the [Twilio Conversations API](https://www.twilio.com/conversations-api) to add more robust chat functionality that will allow users to see messages that were send before they enter a room.

**Comment by aaalaniz** [comment]
We are considering this feature, but it's not currently on our roadmap. I will close for now.

Thank you!
