### ISSUE TITLE
How to Record a Group Video Session

### ISSUE THREAD

**Issue by papuruth** [twilio/twilio-video-app-react#329]
**Question**
My use case is that I want to record a video meeting session as same as Google Meet but with the click of a button. But I don't have any idea on how to achieve this.
Basically, our web app contains two types of video meetings.
1. 2 participant video meet (Recording not required)
2. A group video meets basically a group session. (Recording required).

Any help would be appreciated.

**Comment by RusseII** [comment]
You will need to create the rooms via the API vs initiating the room creation on the client side. 

When creating the room, you can specify if the room is recorded or not VIA the api. 

https://www.twilio.com/docs/video/api/rooms-resource -`https://www.twilio.com/docs/video/api/rooms-resource`


I did something similar to this, I modified the token lambda function to create the room as well - https://gist.github.com/RusseII/a0ad81cbe71045ba4602b748d104f4d9

**Comment by RusseII** [comment]
Also - the Twilio team said that there will be an API added soon with new options around recording. https://github.com/twilio/twilio-video.js/issues/1178 

This should give the ability to stop/start the recording in the middle of the video room once it's out.

**Comment by timmydoza** [comment]
Thanks for the question @papuruth!! (and thanks for the help @RusseII!)

As seen in the twilio-video.js thread - this functionality will be added to the twilio-video.js library soon (likely this quarter). 

Once it's in the SDK, we'll be adding a button to this app that will let you start and stop recordings during a portion of a video call. I'll be sure to keep you in the loop. 

Thanks!

**Comment by dezmunt1** [comment]
> I'll be sure to keep you in the loop.

Has this functionality appeared?

**Comment by timmydoza** [comment]
Hi everyone! This functionality has now been released in the video app. There is a new button that allows users to start and stop recording at any point during the video call. Please see the [changelog](https://github.com/twilio/twilio-video-app-react/releases/tag/v0.4.0) for more details. 

The button can be found in the "More" menu when in a room:

![image](https://user-images.githubusercontent.com/12685223/118516249-60118080-b6f3-11eb-916a-b152e140dfe4.png)
