### ISSUE TITLE
Easily create adhoc 1-on-1 video calls (room name/participant name optional)

### ISSUE THREAD

**Issue by krali** [twilio/twilio-video-app-react#334]
**What is the feature that you would like to see in the app? Please describe.**
A clear and concise description of the proposed feature.

**Is your feature request related to a problem? Please describe.**

**Describe alternatives you've considered**

**Additional context**

**Comment by timmydoza** [comment]
Thanks for the feature request @krali!

Could you please fill out our feature request template in full? It would give us a better idea of the feature you want to see in the app. 

Thanks!

**Comment by timmydoza** [comment]
Closing this feature request as it is incomplete. Please feel free to submit a new feature request that provides more detail. Thanks!
