### ISSUE TITLE
Azure Deployment of twilio-video-app-react:

### ISSUE THREAD

**Issue by Wajeehkhan123** [twilio/twilio-video-app-react#340]
@philnash @markandrus @makarandp0 @manjeshbhargav I tried to deploy twilio-video-app-react on azure, but when I enter the room name and the identity, it is showing the error:
**I'm getting: Invalid Access Token. Please make sure you are using the correct credentials.  Error Code: 20101.** Moreover, I have deployed it to **heroku**, and also there I got this error, but through this below mentioned link I were able to resolve it.
The Link: **https://github.com/twilio/twilio-video-app-react/issues/187**
But I am not being able to resolve it on azure. Is there any help available for azure deployment.

**Comment by philnash** [comment]
Hi @Wajeehkhan123, it sounds as though you perhaps haven't set your credentials in environment variables in Azure. Without the correct credentials in the environment, the token will not be generated correctly.

Can you describe the steps you took to deploy this to Azure?

**Comment by Wajeehkhan123** [comment]
Hi @philnash,  the credentials including **api_key, api_secret, and account_sid** are already provided in the .env file in the react application. What are the other environment variables that need to be stored ?

**Comment by philnash** [comment]
Ah, so you're saying that you have deployed an `.env` file with your account credentials to Azure?

Can you capture one of the access tokens the application creates and check that it has the right credentials by decoding it at https://jwt.io.

**Comment by Wajeehkhan123** [comment]
Yes, I have already checked it. The same issue was encountering when I tried to deploy it on Heroku. Moreover, at that time also, I checked the token and there was no problem. Then, I found the solution from the link which I already have mentioned in my question.
Now, the same issue is here, but I really don't know what other things need to be done in order to deploy it to azure?

**Comment by philnash** [comment]
There is a lot of advice in #187, what did you do to fix your Heroku deployment?

Can you describe what you have done to deploy to Azure so far?

**Comment by Wajeehkhan123** [comment]
@philnash I picked the below mentioned detail from #187 link and I replaced my server.js file with the code mentioned in the link. In addition to that, I also made some changes to package.json file as given below, and then it was working fine with no token error.
Modify your server.js file as follows:
const express = require('express');
const app = express();
const path = require('path');
const AccessToken = require('twilio').jwt.AccessToken;
const VideoGrant = AccessToken.VideoGrant;
require('dotenv').config();
const MAX_ALLOWED_SESSION_DURATION = 14400;
const twilioAccountSid = process.env.TWILIO_ACCOUNT_SID;
const twilioApiKeySID = process.env.TWILIO_API_KEY_SID;
const twilioApiKeySecret = process.env.TWILIO_API_KEY_SECRET;
app.use(express.static(path.join(__dirname, 'build')));
if (process.env.NODE_ENV === 'production') {
// Set static folder
app.use(express.static(path.join(__dirname, 'build')));
app.get('/token', (req, res) => {
const { identity, roomName } = req.query;
const token = new AccessToken(twilioAccountSid, twilioApiKeySID, twilioApiKeySecret, {
ttl: MAX_ALLOWED_SESSION_DURATION,
});
token.identity = identity;
const videoGrant = new VideoGrant({ room: roomName });
token.addGrant(videoGrant);
res.send(token.toJwt());
console.log(issued token for ${identity} in room ${roomName});
});
app.get('*', (_, res) => res.sendFile(path.join(__dirname, 'build/index.html')));
}
const port = process.env.PORT || 8081;
app.listen(port, () => console.log(token server running on ${port}));
Then modify your package.json script to this:
"scripts": {
"client-install": "npm install",
"start": "node server.js",
"dev": "concurrently npm:server npm:dev",
"build": "node ./scripts/build.js",
"test": "jest",
"eject": "react-scripts eject",
"lint": "eslint src/**/*.{ts,tsx}",
"server": "nodemon server.js",
"test:ci": "jest --ci --runInBand --reporters=default --reporters=jest-junit --coverage",
"cypress:open": "cypress open",
"cypress:run": "cypress run --browser chrome",
"cypress:ci": "cross-env CYPRESS_baseUrl=http://localhost:8081 start-server-and-test server http://localhost:8081 cypress:run",
"deploy:twilio-cli": "cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build",
"heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm run install-client && npm run build"
},
You will need to set up your environment variables within Heroku. I have this running on heroku using the firebase login - not the passcode.
Also, you should probably install ncu and update the dependencies with that before deploying.

That was it.

**Now, the process of deplying to azure is given below:**

We have a single repository for both voice services infrastructure and for the application code.
When you want to make a change, you need to create a new ‘branch’, make your changes and then commit \ sync those changes to the repository in Azure DevOps.
The act of merging your new code into master, is done so by creating a Pull Request. The pull requests is made up of two parts. The Pull Request validation – which validates the application can compile, and that the infrastructure is syntactically correct. This validation is purely to confirm if the application compiles correctly – it does not check for configurations or potential configuration issues.
Once the Pull Request validation completes successfully, then another process is initiated which is the “Continuous Integration” – its at this point the newly created code is merged into the master branch.
After the master branch has been updated, the deployments (or release) occur. A trigger known as “Continuous Deployment” is activated and the new code \ changes are automatically deployed to our Development environment.
Below are some screenshots to assist with write-up above.
Repository:

![image002](https://user-images.githubusercontent.com/44812661/97775814-61c78c80-1b85-11eb-9eba-d469be346c07.png)

Pull Request \ Validation:
** Note here, validations need to be updated once we’ve settled on and identified what resources are truly needed for the implementation of voice services.

![image (3)](https://user-images.githubusercontent.com/44812661/97775835-989da280-1b85-11eb-8ccf-07c3a6c8f4e4.png)

Continuous Integration \ Merge into Master \ Artifacts creation:
*Note: Artifacts are the files later used during the deployment phase.

![image (4)](https://user-images.githubusercontent.com/44812661/97775852-bec34280-1b85-11eb-8753-01f780c08bad.png)

Here are screenshots specifically of the NPM tasks:

![image (5)](https://user-images.githubusercontent.com/44812661/97775868-e7e3d300-1b85-11eb-8730-8f419df34d54.png)

![image (6)](https://user-images.githubusercontent.com/44812661/97775877-f500c200-1b85-11eb-842c-2ac0c13e5290.png)

Continuous Deployment
*Note here, the only environment currently being deployed is Dev.

![image (7)](https://user-images.githubusercontent.com/44812661/97775903-2a0d1480-1b86-11eb-9537-b542ad30d67c.png)

Screenshot of the task to deploy the voice services application:

![image (8)](https://user-images.githubusercontent.com/44812661/97775909-385b3080-1b86-11eb-8f4a-420b374532d7.png)

Another point to note, the voice services web application azure resources does not have any “App Settings” configured.

That's all.

**Comment by philnash** [comment]
Thanks for the detail.

I can't help but notice that in your repo screenshot there is no `.env` file and at the end you tell me that there are no "App Settings" configured. So, my guess is that you do not have any environment variables configured and that since you are using Azure Apps you should configure your `TWILIO_ACCOUNT_SID`, `TWILIO_API_KEY_SID` and `TWILIO_API_KEY_SECRET` in the [App Settings](https://docs.microsoft.com/en-us/azure/app-service/configure-common).

Let me know how you get on with that.

**Comment by Wajeehkhan123** [comment]
What If I set my TWILIO_ACCOUNT_SID, TWILIO_API_KEY_SID , and TWILIO_API_KEY_SECRET in server.js file directly? It will work or not ?

**Comment by philnash** [comment]
Yes, that would work, but we never recommend checking in your secrets with your code.

What should work is setting your `TWILIO_ACCOUNT_SID`, `TWILIO_API_KEY_SID` and `TWILIO_API_KEY_SECRET` in your App Settings. Have you tried that yet?

**Comment by Wajeehkhan123** [comment]
@philnash I had tried setting the credentials in server.js file temporarily to make sure it would work or not, but it did not work. As far as setting the credentials in App Settings is concerned, they are already set in App Settings file. So basically, we have tried both.

**Comment by philnash** [comment]
Can you send me an example token generated by your application? You can email it to me at philnash [at] twilio.com.

**Comment by Wajeehkhan123** [comment]
I have sent the access token to your email. Kindly have a look please.

**Comment by aaalaniz** [comment]
Hey @Wajeehkhan123 and @philnash 

It looks like support for this issue has moved to an external channel. I will close for now, but please feel free to share any findings on this issue.

Thanks!

**Comment by yellowstripe-io** [comment]
I have the same question of deployment with firebase but hosted as a twilio function. I am still unable to deploy a build with a firebase auth on twilio. IF someone has any layman explanation of setup, I would pay for it. :)
