### ISSUE TITLE
Share Screen from Iphone or Ipad

### ISSUE THREAD

**Issue by m1kjh43l2020** [twilio/twilio-video-app-react#343]
Its possible to share screen on IPAD, ?

For example to share excel sheet or some PDF files.

The button on ths devices appears disbaled

Thanks!
Alejandro

**Comment by timmydoza** [comment]
Thanks for the question @m1kjh43l2020!

Unfortunately, screen sharing is not supported on iPad or any other iOS device. The API that we use to capture the screen (`navigator.mediaDevices.getDisplayMedia`) is not available on any mobile device. See the 'Browser Compatibility' chart at the bottom of the `getDisplayMeida` documentation: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia
