### ISSUE TITLE
Regarding BEST PRACTICES for VIDEO on mobile browser 

### ISSUE THREAD

**Issue by helloneeraj** [twilio/twilio-video-app-react#351]
**Question**
Hi Team,
    I came across your link which talks about "Best Practices for Twilio Video on Mobile Browsers". It mentioned few ideas like "Perform pre-call microphone and camera tests" etc....

My Question is - Are you guys taking care of it in this App? 

**Additional context**
https://www.twilio.com/blog/best-practices-video-mobile-browsers

**Comment by timmydoza** [comment]
Thanks for the question @helloneeraj!

Yes - this is taken care of in this app. On the following screen, users are given a chance to verify that their video is correct (in the preview), that their audio is working (the little microphone icon indicates audio volume), and that their network connection is good. Any device errors are shown to the user in a message up in the corner:  
![image](https://user-images.githubusercontent.com/12685223/98903182-5113f200-2474-11eb-8d90-ac8a95b0532a.png)

However, I did just find a bug that prevents this error message from being displayed to the user. I have a PR here (#363) that will fix it. 

Thanks again for the question. Please let me know if you have any more. I'm happy to help!
