### ISSUE TITLE
Unable to change audio inputs using Firefox

### ISSUE THREAD

**Issue by idallas** [twilio/twilio-video-app-react#356]
**Describe the bug**
Changing audio inputs does not work in firefox due to a MediaStreamError

**To Reproduce**
1. Connect to app with a computer that has more than one audio input
2. Put in your name and room name and click Continue button
3. Click on Settings button
4. Select Audio and Video Settings from the Settings menu
5. Try to change the Audio Input
6. The audio input doesn't change, and there is an error in the console.log.

**Expected behavior**
The audio input should change to what was selected.

**Environment (please complete the following information):**
 - OS: macOS 10.15.7 and Windows 10
 - Browser: Firefox 82
 - App Version: 0.2.1 
 - SDK Version: 2.8.0-beta.2
 - Node.js version: 12.18.4

**Additional context**
Console.log errors:

2020-11-06 19:52:04.776Z | ERROR in [LocalAudioTrack #3: {7b6cc5f0-df45-c840-bb3d-cf660da5580d}]: Failed to re-acquire the MediaStreamTrack: 
MediaStreamError { name: "NotReadableError", message: "Concurrent mic process limit.", constraint: "", stack: "" }
 
Object { deviceId: {…} }

Uncaught (in promise) 
MediaStreamError { name: "NotReadableError", message: "Concurrent mic process limit.", constraint: "", stack: "" }

**Comment by timmydoza** [comment]
Thanks for the issue @idallas!

Unfortunately, I'm not able to reproduce this issue. I tried switching audio devices in Firefox 82 and it seemed to work fine.

I have seen the `Concurrent mic process limit` error before. Firefox won't let you start a new audio stream if an existing stream (or clone of a stream) is still active. We take care to stop the audio tracks that are cloned in the [AudioLevelIndicator](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/AudioLevelIndicator/AudioLevelIndicator.tsx#L39) component.

I wonder if you would still encounter the error if you commented out [this line](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/PreJoinScreens/DeviceSelectionScreen/LocalVideoPreview/LocalVideoPreview.tsx#L76) of code and then tried to switch devices before you join a room. If this works for you, then it means that there is still some issue in the AudioLevelIndicator component.

I'm also curious about the devices that are connected to your machine. What device are you switching away from when you see this error? I wonder if there is some kind of problem stopping the track (`audioTrack.stop()` must be called on the existing track before a new one is started). 

Sorry I couldn't find the cause of your error, but maybe some of these ideas will yield us some clues. Let me know what you think. Thanks!

**Comment by idallas** [comment]
Thanks for taking a look!  I was able to reproduce it on a third computer (another macOS Catalina) by just adding the virtual ZoomAudioDevice, used for sharing computer audio over Zoom.  Maybe it only happens when virtual audio devices are present?  I have multiple virtual audio devices on my Windows machine as well, but not the Zoom audio device.  I'll get a test going with only physical audio devices and see if it still happens.

For extra context, the virtual audio devices I currently see on my Windows setup are an Oculus Virtual Audio Device (part of the Oculus Rift software), Steam Streaming Microphone, Virtual Desktop Audio, and Bigscreen Audio Stream.  Those might all be VR software related.

**Comment by idallas** [comment]
Ok, this was my mistake and the issue is resolved.  I thought I had the latest version of your code, but I downloaded it again just to be sure and now I can't reproduce the issue.  Sorry to use up your time!

**Comment by timmydoza** [comment]
Not a problem @idallas - I'm happy to hear you got it working!
