### ISSUE TITLE
A pause button is displayed on top of the video when using safary on iOS

### ISSUE THREAD

**Issue by hantonelli** [twilio/twilio-video-app-react#359]
**Describe the bug**
When someone joins the call, for the participants using iOS a stop button is displayed on top of the video.

**To Reproduce**
When a participant join a meeting, a pause button appear in the video.
It happen randomly on the participants that are using safary on iOS.

**Expected behavior**
We expect that the pause button to not be displayed.

**Screenshots**
![Pause issue 1](https://user-images.githubusercontent.com/18269845/98562737-486bc200-22a2-11eb-9225-1068da335784.png)
![Pause issue 2](https://user-images.githubusercontent.com/18269845/98562748-4b66b280-22a2-11eb-9bb1-b4739febf69d.png)

**Environment (please complete the following information):**
 - OS: iOS
 - Browser: Safary
 - App Version: 0.2.1
 - SDK Version: 2.8.0-beta.2
 - Node.js version: 14.1.0

**Additional context**
No

**Comment by timmydoza** [comment]
Thanks for the issue @hantonelli!

Unfortunately - I cannot reproduce the issue that you described. I have a couple questions about it:

- What version of Safari are you using?
- Did you do anything special to get the play/pause icon to appear? Did you tap something, receive a phone call, talk to Siri, or background the app?
- Does the play/pause icon go away eventually, or does it stay around forever?

Any additional context for this problem would be appreciated. Thanks!!

**Comment by hantonelli** [comment]
Hi @timmydoza , thanks for the aswer.

- What version of Safari are you using? 14
- Did you do anything special to get the play/pause icon to appear? No, when someone enters the call, it is displayed as in the images
- Did you tap something, receive a phone call, talk to Siri, or background the app? No, none of them
- Does the play/pause icon go away eventually, or does it stay around forever? It usually stays, but there were times when it went away

The pause icon is displayed just in iOS, it was never displayed on Android. And it was displayed as soon as other participant joined the call.

Hope this help.

Kind regards,
Horacio

**Comment by timmydoza** [comment]
Thanks for the extra information @hantonelli!

Unfortunately, I'm a little stumped as to why this could be happening. I do have some ideas though:

- Can you verify that the `controls` attribute has not been added to the `<video>` element? This attribute could cause video controls (play/pause buttons) to appear on the video track. 
- If you upgrade iOS from version 14 to version 14.2 (which will also upgrade Safari), does it fix the issue?

Also, just curious, what iOS device is this being run on?

Thanks again!

**Comment by hantonelli** [comment]
Hi @timmydoza ,

The <video> doesn't have the controls attribute.
To run this test we used the code of this repo. I changed the code to the the authentication, nothing else.

The iOS version is actually 14.1

Kind regards,
Horacio

**Comment by timmydoza** [comment]
Thanks for the info @hantonelli!

I found the issue. It appears that iOS Safari will add these play/pause buttons to video elements when the phone is running in Low Power Mode. This issue can be reproduced by going to Settings > Battery > Low Power Mode, and turning the switch to on. 

In your screenshots, I see that your battery is nearly empty. If you charge your phone and try again, do these buttons go away?

**Comment by hantonelli** [comment]
Hi @timmydoza, thanks for finding the issue.

We where able to reproduce the issue following your instractions.
If the battery is fully charged and we change to the Low Power Mode, the pause button is displayed. Then if we revert that Setting, the pause button is not displayed.

Do you know if there is anything that can be done to solve this?

**Comment by timmydoza** [comment]
Hi @hantonelli!

I'm not sure that this can be solved. I saw this (https://stackoverflow.com/questions/8911247/hide-iphone-html5-video-play-button), and it seems that there may be a way to use CSS to hide the shadow-dom play button. It's possible that it may not work though. 

My guess is that iOS is choosing to pause the video elements in this app when it is low on battery as it will likely use less CPU (and less electricity). This is why we see play and pause icons. 

Even if CSS can be used to remove the icons, there's still a bigger problem - which is that the phone doesn't have enough power for this app to function correctly. The best course of action would be to charge the phone. 

I'm glad we could find the root cause!

**Comment by hantonelli** [comment]
Hi @timmydoza,

Yes, it's great you found the root cause!

As you suggested, the best solution will be to recommend the user to plug the phone.
I will try to see if I can add something to detect when the user has low battery, so I can display a message to the user recommending to plug the phone.
https://stackoverflow.com/questions/46670150/low-power-mode-detection-in-javascript-for-ios11

Thanks for your time, analysis and recommendations.

**Comment by Luco4444** [comment]
I had the same problem in my React app. here is my video tag that works fine
    <video
                    ref={videoEl}
                    controls={false}
                    muted={true}
                    loop
                    playsInline
                    controlsList="nodownload"
                    disablePictureInPicture
                    disableRemotePlayback
                    className="streamVideo w-full max-w-full rounded-lg object-cover sm:h-full"
                  />, so I just removed autoPlay={true}
