### ISSUE TITLE
Chat text with URL's?

### ISSUE THREAD

**Issue by gregarican** [twilio/twilio-video-app-react#368]
I am looking to utilize something very much like this project, for retail virtual sales. The goal would be for a salesperson and a customer to be on a video chat where the salesperson would display items the customer is interested in. Then if the customer wishes to purchase an item, the salesperson would push them a purchase URL through the Snackbar chat.

Is there an existing function in the Snackbar library that automatically formats URL's so they are messaged as hyperlinks? I realize with the minimalist angle that Snackbar is created for this might be contrary to the intent...

**Comment by gregarican** [comment]
Would something like this added in work? https://github.com/gregjacobs/Autolinker.js/

**Comment by gregarican** [comment]
So I am now able to display the URL's locally for the DataTrack sender. I placed this in the ChatInput.tsx file.

`// Render the message locally so the local participant can see that their message was sent.
        enqueueSnackbar(<a href={message}>{message}</a>);`

But when I am trying to push the message out to the remote users I cannot get this to appear correctly on their end. Since the localDataTrackPublication.track.send(message) call in the ChatInput.tsx file is enforcing the message to always be a string.

Here is what I see in the DataTrack.tsx file.

`import { useEffect } from 'react';
import { DataTrack as IDataTrack } from 'twilio-video';
import { useSnackbar } from 'notistack';

export default function DataTrack({ track }: { track: IDataTrack }) {
  const { enqueueSnackbar } = useSnackbar();

  useEffect(() => {
    const handleMessage = (message: string) => enqueueSnackbar(message);
    track.on('message', handleMessage);
    return () => {
      track.off('message', handleMessage);
    };
  }, [track, enqueueSnackbar]);

  return null; // This component does not return any HTML, so we will return 'null' instead.
}
`

I am assuming this is where the enqueueSnackBar is being triggered when there are DataTrack elements to display for the remote users. Any suggestions as to how I can present this message as a clickable URL?

**Comment by timmydoza** [comment]
Hey @gregarican - Thanks for the question!

I think that the text that is sent over a DataTrack can be left as is. I don't think that it needs to be modified. 

When the text is received, we can look for any URLs inside them, and then convert those URLs into `<a></a>` components. It's a little tricky to do, but I found a library that does all this for us. It's called [react-linkify](https://github.com/tasti/react-linkify).

I was able to get this feature working with that library. First I installed it with `npm i -S react-linkify @types/react-linkify`. Then, I changed my `DataTrack.ts` file to the following (note: I had to also change the filename to `DataTrack.tsx`):

```
import React from 'react';
import { useEffect } from 'react';
import { DataTrack as IDataTrack } from 'twilio-video';
import { useSnackbar } from 'notistack';

import Linkify from 'react-linkify';

export default function DataTrack({ track }: { track: IDataTrack }) {
  const { enqueueSnackbar } = useSnackbar();
  useEffect(() => {
    const handleMessage = (message: string) =>
      enqueueSnackbar(
        <Linkify
          componentDecorator={(decoratedHref, decoratedText, key) => (
            <a target="_blank" rel="noopener" href={decoratedHref} key={key}>
              {decoratedText}
            </a>
          )}
        >
          {message}
        </Linkify>
      );
    track.on('message', handleMessage);
    return () => {
      track.off('message', handleMessage);
    };
  }, [track, enqueueSnackbar]);

  return null; // This component does not return any HTML, so we will return 'null' instead.
}
```

Thats it! The `componentDecorator` stuff that you see in there is needed to add the `target="_blank" rel="noopener"` attributes to the anchor element, which allows links to be opened in a new window (opening them in the same window would end the call). 

Let me know how this works out for you! I'll close this issue for now, but please do let me know if you have any other questions!

Note: one downside of this approach is that the `react-linkify` repository looks like it may be abandoned. It hasn't been updated in a while, and it looks like there be some outstanding bugs. I didn't encounter any bugs myself, but it's something to keep in mind.

**Comment by gregarican** [comment]
Thank you SO much for this! Works like a champ. I appreciate you taking the time to look at this.

**Comment by timmydoza** [comment]
Happy to help!

**Comment by tech4her** [comment]
Please how can implement this. The chat feature. Will appreciate sharing the steps.

**Comment by gregarican** [comment]
This project itself contains all of the particulars. You can review the source code to see how the Twilio API's DataTrack (remote and local) is implemented using Snackbar. It works quite well and has helped me get my head around how React works.
