### ISSUE TITLE
TrackSwitchOffMode not showing last frame

### ISSUE THREAD

**Issue by dannnnthemannnn** [twilio/twilio-video-app-react#370]
**Describe the bug**
It suggests in the documentation that the last frame will be shown when a track is switched off: https://www.twilio.com/docs/video/tutorials/using-bandwidth-profile-api#track-switch-offs

I have seen that any time a track is switched off it just shows the users' display name instead.

**Comment by timmydoza** [comment]
Thanks for the issue @dannnnthemannnn!

>the last frame will be shown when a track is switched off

This is correct. When a video track is switched off, the `<video>` element will continue to display the last frame that was received. 

This means that a participant's video will appear to be frozen when the track is switched off. In this app, however, we did not want the participant's video to appear frozen, so we display a black background (and avatar icon) over the `<video>` element when the track is switched off.

This behavior can be disabled by removing the following lines of code from `ParticipantInfo.tsx`: https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ParticipantInfo/ParticipantInfo.tsx#L201-L205
