### ISSUE TITLE
Missing ToggleFullScreenButton ?

### ISSUE THREAD

**Issue by baj84** [twilio/twilio-video-app-react#371]
The Fullscreen button is missing and the file ToggleFullScreenButton.tsx has been removed.

**Comment by timmydoza** [comment]
Thanks for the issue @baj84!

The full screen button was intentionally removed from the app. 

The app can still be run in a full screen window. You can press **command + shift + F** in MacOS, or **F11** in Windows.

Alternatively you can click on this button in the Chrome menu:

<img width="364" alt="Screen Shot 2020-11-19 at 1 06 24 PM" src="https://user-images.githubusercontent.com/12685223/99720012-4eb02a00-2a6a-11eb-9449-7a74cce40057.png">

**Comment by baj84** [comment]
Thanks @timmydoza - Can I check why it was removed? Getting users to click into a Chrome menu or use a keyboard shortcut unfortunately isn't an option.

**Comment by timmydoza** [comment]
It was removed to make room for other things - and because it's possible to make the app fullscreen using the methods I listed above. 

Just curious - why is using the chrome menu or keyboard shortcuts not an option for you?

**Comment by baj84** [comment]
Ah! Do you know which commit it was removed from? I'd like to put it back in.

It's not an option purely because of the user experience. All our customers are non-tech (maybe even 60+), so trying to put instructions for shortcuts or chrome menus will be confusing to them. I'd much rather just a single icon they can click.
