### ISSUE TITLE
MB used in 1 minute of connection?

### ISSUE THREAD

**Issue by m1kjh43l2020** [twilio/twilio-video-app-react#375]
I need to check one plan of AT&T, for that i have this question: How many mega bytes are used on one minute of connection(one user)?
Thanks

**Comment by timmydoza** [comment]
Thanks for the question @m1kjh43l2020!

Unfortunately, the answer to this question is "it depends". 

The amount of data that this app uses varies widely based on a number of factors. Such factors include:
- The number of participants in a room
- The number of audio and video tracks that you are subscribed to
- The audio and video codecs used
- The resolution of the video tracks
- The available bandwidth (when bandwidth is low, track resolution decreases accordingly)

My best suggestion is to run a test for your specific use case. Simply run the app on your phone, and use a third party data monitoring app to look at how much data is used. 

Sorry that I couldn't give you a better answer - unfortunately there are just too many variables at play here to give you a definitive answer.
