### ISSUE TITLE
Facing issue in deploying twilio cli for programmable video

### ISSUE THREAD

**Issue by rakeshkk16** [twilio/twilio-video-app-react#384]
After running npm run deploy:twilio-cli, optimized production build compiles successfully, chunk.js file gets created. However after this starts giving network connectivity error, although there isn't any internet issue. 
![Screenshot from 2020-12-14 14-08-12](https://user-images.githubusercontent.com/68590642/102058738-f7f20200-3e15-11eb-8d45-6378bc1fdebd.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome 
 - Node.js version:15.0.1

**Additional context**
Twilio login command asks for account sid and auth token,after being added cannot find any profiles using command twilio profiles:list.So have added account sid, api key and api secret in .env file.

**Comment by timmydoza** [comment]
Thanks for the issue @rakeshkk16!

We have an article that has resources that can help you diagnose the issue: https://support.twilio.com/hc/en-us/articles/360007199494-Resources-for-Diagnosing-Connection-Issues-to-the-Twilio-REST-API

Let's double check and make sure that your machine can access Twilio's APIs. Can you please run the `dig` and `curl` commands as specified in that article and let me know what the output is? Thanks.

**Comment by rakeshkk16** [comment]
![Screenshot from 2020-12-15 14-23-31](https://user-images.githubusercontent.com/68590642/102192823-4b7d5200-3ee1-11eb-9814-c006b9dc9578.png)
![Screenshot from 2020-12-15 14-23-42](https://user-images.githubusercontent.com/68590642/102192829-4ddfac00-3ee1-11eb-8c8d-258331409a4d.png)

**Comment by timmydoza** [comment]
Thanks for the info @rakeshkk16! 

Everything looks good there. 

What if you run another twilio-cli command just to test that it is working properly. For instance:

`twilio phone-numbers:list`

This will display any twilio phone numbers you have purchased (if any). If you run this command, does it succeed, or do you see the same error as before?

**Comment by rakeshkk16** [comment]
This command givind me error as could not find profile (scrrenshot for your reference). Although I can see TWILIO_ACCOUNT_SID when I runs echo $TWILIO_ACCOUNT_SID command as I already have set these values in environment variables.
![Screenshot from 2020-12-16 00-41-42](https://user-images.githubusercontent.com/68590642/102261545-d5580a00-3f37-11eb-90bb-0e70e27ac49a.png)

**Comment by timmydoza** [comment]
Thanks for the screenshot @rakeshkk16!

I think I see the issue. You are using sudo. When you use sudo, commands are executed as another user, specifically the root user.

I think this is why the Twilio CLI cannot access the environment variables you set. You're setting them as your user, but it's the root user that's running the CLI commands.

A test:

-Run `env`. You should see your Twilio environment variables.
-Run `sudo env`. You should not see your Twilio environment variables.

This could also explain why `twilio login` isn't working for you.

I would recommend using npm without sudo. There are a number of articles online about ways to achieve this. You may need to uninstall node and npm, and then install node with a tool like [nvm](https://github.com/nvm-sh/nvm). Let me know how this works for you!

**Comment by rakeshkk16** [comment]
Thanks for your support @timmydoza I got the issue. My nodu_module folder was assigned under root permission also was facing proxy issue due to which these all errors were coming. Now things are working fine. :+1:

**Comment by timmydoza** [comment]
Great to hear @rakeshkk16!!
