### ISSUE TITLE
Any SDK function/property that gives us connection time in real time

### ISSUE THREAD

**Issue by rachnaban** [twilio/twilio-video-app-react#388]
**Question**
Please let me know if there is a function/property at SDK level that gives us the connection time to the room in real time for the local participant.

**Additional context**
Something to show at the user interface level that gives the connection time in minutes:seconds.

**Comment by timmydoza** [comment]
Thanks for the question @rachnaban!

Unfortunately, the SDK does not have this property. You'll have to log the start time of the room when you connect to it:

```
connect('token', options).then(room => {
  window.twilioConnectTime = Date.now();
});
```

Then, you can calculate the number of seconds that the local participant has been connected to the room with this:

```
const secondsInRoom = (Date.now() - window.twilioConnectTime) / 1000;
```
