### ISSUE TITLE
Stop Video then try to change Video Input - Crash

### ISSUE THREAD

**Issue by mapolyakov** [twilio/twilio-video-app-react#389]
**Describe the bug**
When on the deviceSelectionStep if you stop the video and then go to Settings > Video Input and try to choose a camera, it will crash with.

When video is stopped it also doesn't show the currently selected device in that menu but rather has it blank.

**To Reproduce**
1. Go to 'Join a Room' page
2. Join the room to get to the Device Selection page (deviceSelectionStep)
3. Click on Stop Video
4. Go to Settings > Audio and Video Settings > Video Input.
5. Select a video input device and you will get a crash

**Expected behavior**
- Show current device even though video is stopped (current device meaning the video that will be used if you start video)
- Allow selecting device even though video is stopped so it will be used next time video is started (this one is maybe more correct)

**Screenshots**
When video is stopped, it shows no device selected:
![image](https://user-images.githubusercontent.com/39071959/102722794-63295180-42b8-11eb-92a1-a0014ff5dbc9.png)

When clicking dropdown it shows your available devices:
![image](https://user-images.githubusercontent.com/39071959/102722800-6fadaa00-42b8-11eb-8c1a-91a7d9097813.png)

Error page:
![image](https://user-images.githubusercontent.com/39071959/102722722-ded6ce80-42b7-11eb-9dda-9e0b16b34ecf.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge (Chromium) v89.0.731.0
 - App Version: 0.2.1 (current master)

**Additional context**

**Comment by timmydoza** [comment]
Thanks for the bug report @mapolyakov!

I can reproduce this bug. It seems to happen in any browser, but only when there are multiple video inputs available.  I'll start working on a fix. 

Thanks again!
