### ISSUE TITLE
bring autosave back

### ISSUE THREAD

**Issue by haveaguess** [twilio/twilio-video-app-react#390]
we have removed, but can't we make it safe quickly?

**Comment by timmydoza** [comment]
Thanks for the issue @haveaguess!

Can you please open a new Feature Request and fill out the feature request template in full? I'm interested to hear more about the autosave feature. Some more detail about your idea would help me understand it better.

Thanks!

**Comment by haveaguess** [comment]
Haha thanks @timmydoza submitted this issue into the wrong repo apologies (playing with GH chrome extensions / terminal scripts)
