### ISSUE TITLE
Hosting the app on a subdirectory

### ISSUE THREAD

**Issue by pranjal-goswami** [twilio/twilio-video-app-react#394]
**Question**
How can we host the app on a subpath or sub-directory?

**Additional context**
We are using nginx but a simple proxy_pass does not work since the app looks for static resource at `/static` and not `/subdir/static`.  If you set additional rules for `/static` the app redirects to `/` automatically on load.

**Comment by VGordillo-Resulto** [comment]
Hi @pranjal-goswami,

In package.json file add
```
"homepage": "/subdir/static",
```

**Comment by timmydoza** [comment]
Thanks for the question @pranjal-goswami, and thank you for the tip @VGordillo-Resulto!

@VGordillo-Resulto is correct - you can add the `"homepage"` property to package.json. More information is available in the the documentation for create-react-app: https://create-react-app.dev/docs/deployment#building-for-relative-paths

Please let me know if you are still having problems and I can repopen this issue. Thanks!

**Comment by pranjal-goswami** [comment]
@VGordillo-Resulto @timmydoza 
Thanks for the quick help 🙂
