### ISSUE TITLE
Session Data

### ISSUE THREAD

**Issue by arpanghoshal** [twilio/twilio-video-app-react#396]
Is there any way to get data about when the call started/ended and room/name associated with the call?

**Comment by timmydoza** [comment]
Thanks for the question @arpanghoshal!

This information can be found in the Video dashboard in the Twilio Console: https://www.twilio.com/console/video/dashboard

Just click on a room to view information about it.

Also, you can use the Video Log Analyzer to look at additional room details: https://www.twilio.com/console/video/logs/rooms

Please let me know if you have any additional questions!
