### ISSUE TITLE
Getting error while trying to deploy video App

### ISSUE THREAD

**Issue by shuklasnehil** [twilio/twilio-video-app-react#400]
Followed steps from this URL and getting issue in the last step i.e deployment :
@instance-1:~/twilio-video-app-react$ npm run deploy:twilio-cli
npm WARN npm npm does not support Node.js v10.23.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
> twilio-video-app-react@0.2.1 deploy:twilio-cli /home/shuklas/twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build
npm WARN npm npm does not support Node.js v10.23.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
> twilio-video-app-react@0.2.1 build /home/shuklas/twilio-video-app-react
> node ./scripts/build.js
Creating an optimized production build...
The provided app-directory does not appear to be a valid app. There is no index.html found in the app-directory.

Its not getting deployed and says no index.html found.NO url and secret key generated .
Please advise.

**Comment by timmydoza** [comment]
Thanks for the issue @shuklasnehil!

Can you please let me know what version of npm you are using?

This command will tell you the version:
`npm -v`

Looks like the current version of npm is 6.14.11. If you are using an earlier version, can you please try running the following command to update npm to the most recent version?

`npm install -g npm`

Please let me know how this works out for you. Thanks!

**Comment by timmydoza** [comment]
Please let me know if you are still running into issues and I'll be happy to reopen this issue.
