### ISSUE TITLE
Any plans for supporting WebViews in mobile apps?

### ISSUE THREAD

**Issue by alinberce** [twilio/twilio-video-app-react#403]
**Question**
As you may know, webview on android supports webRTC and the latest release of iOS 14.3 adds support for webRTC in the WKWebView. Do you have any plans to have this app working in webviews?

**Additional context**
Given mobile cross development, for instance xamarin forms, could run the video app with bypass the browser check by making use of renderers inside a webview, with these observations:
- on android it works fine once the user grants permissions
- on iOS WKWebView it allows to ask for permissions, can see the camera preview and mic working, it connects to a room and the camera preview is shown, but once another app joins the room, the video and audio is not being transferred between the two. On Android for instance shows a play icon over a black scren, on iOS shows a black screen with a generic person icon
- on iOS using SFSafariViewControler works but is not as ergonomic as a WKWebView would be.

So as a secondary question, any idea why on WKWebView the video and audio isn't transferred between the two parts?
As this may be related more to the video-js than the app, please delete the issue if it doesn't suit this repo.

Thank you for your time.

**Comment by timmydoza** [comment]
Thanks for the question @alinberce!

I think this would be a good question for the [twilio-video.js repo](https://github.com/twilio/twilio-video.js), but I can say that Twilio Video is not currently supported in any webview browsers. We only support the browsers in [this table](https://www.twilio.com/docs/video/javascript#supported-browsers). It's possible that some webkit browsers can work (as you have found), but they may contain issues or work in an unpredictable fashion. We don't do any testing or debugging in webkit browsers, so unfortunately I am unable to answer the questions that you posted.
