### ISSUE TITLE
fixed presenter screen always full screen

### ISSUE THREAD

**Issue by m1kjh43l2020** [twilio/twilio-video-app-react#407]
How can I fix a single person on full screen as if they were a presenter and everyone else on small screens?
Thanks

**Comment by timmydoza** [comment]
Thanks for the question @m1kjh43l2020!

In this app, you can click on the video thumbnail of a participant. This will 'pin' their video, and it make it so their video is always full screen. Additionally, if a user is sharing their screen, then their screen share will take up the whole window for all participants. 

If you wanted a participant to always be full screen no matter what, this would require that this app be modified. If this is what you are looking for, can you please provide more details about your use case? The more details that you provide, the better I will be able to help you. 

Thanks!

**Comment by m1kjh43l2020** [comment]
Hi Timmy, yes i want  a participant will always be full screen no matter what, no matter how many participants enter to the room. Have you a idea how to do this? ( sorry my bad english and greets from mexico)

________________________________
De: timmydoza <notifications@github.com>
Enviado: Tuesday, February 2, 2021 8:32:52 PM
Para: twilio/twilio-video-app-react <twilio-video-app-react@noreply.github.com>
Cc: Alejandro Figueroa <afigueroa@metrix-networks.net>; Mention <mention@noreply.github.com>
Asunto: Re: [twilio/twilio-video-app-react] fixed presenter screen always full screen (#407)


Thanks for the question @m1kjh43l2020<https://github.com/m1kjh43l2020>!

In this app, you can click on the video thumbnail of a participant. This will 'pin' their video, and it make it so their video is always full screen. Additionally, if a user is sharing their screen, then their screen share will take up the whole window for all participants.

If you wanted a participant to always be full screen no matter what, this would require that this app be modified. If this is what you are looking for, can you please provide more details about your use case? The more details that you provide, the better I will be able to help you.

Thanks!

**Comment by timmydoza** [comment]
Hey @m1kjh43l2020 - thanks for the additional details! 

So in order to do this, we will need a way to determine which participant should be full screen all the time. I'm not sure how you would want to do this, but I have an idea:

Let say that we wanted the participant whose name ends in `-presenter` to be full screen. With this, everyone would enter the room with their regular names, but the person that adds `-presenter` to their name (like `timmydoza-presenter`) would be full screen. 

For this, we just need to modify the `useMainParticipant.tsx` file. This is the file that determines which participant will be full screen. Try adding these changes:

```diff
import useVideoContext from '../useVideoContext/useVideoContext';
import useDominantSpeaker from '../useDominantSpeaker/useDominantSpeaker';
import useParticipants from '../useParticipants/useParticipants';
import useScreenShareParticipant from '../useScreenShareParticipant/useScreenShareParticipant';
import useSelectedParticipant from '../../components/VideoProvider/useSelectedParticipant/useSelectedParticipant';

export default function useMainParticipant() {
  const [selectedParticipant] = useSelectedParticipant();
  const screenShareParticipant = useScreenShareParticipant();
  const dominantSpeaker = useDominantSpeaker();
  const participants = useParticipants();
  const {
    room: { localParticipant },
  } = useVideoContext();
  const remoteScreenShareParticipant = screenShareParticipant !== localParticipant ? screenShareParticipant : null;

+ const presenterParticipant = participants.find(participant => /-presenter$/.test(participant.identity));

  // The participant that is returned is displayed in the main video area. Changing the order of the following
  // variables will change the how the main speaker is determined.
-  return selectedParticipant || remoteScreenShareParticipant || dominantSpeaker || participants[0] || localParticipant;
+  return selectedParticipant || presenterParticipant || remoteScreenShareParticipant || dominantSpeaker || participants[0] || localParticipant;
}

```

This should do the trick! The app should work the same for the `-presenter` participant, but everyone else will see the `-presenter` in full screen. Also, with the code above, other users would still be able to pin other participants to make them full screen. 

Let me know if you have any questions about this. We're happy to help!

**Comment by m1kjh43l2020** [comment]
Thanks Timmy, 

I am sending a variable as "presenter = 1" by the Url (? presenter = 1). This is the trigger to know that the one who enters is the one that will always be seen in full screen, apart from the solution you gave me, how could I use this variable only to discriminate and know that the one who entered is the presenter?

 

 

 

 

Ing. Alejandro Figueroa Sánchez

Contacto: 5550723608

 



 

De: timmydoza <notifications@github.com> 
Enviado el: miércoles, 3 de febrero de 2021 03:28 p. m.
Para: twilio/twilio-video-app-react <twilio-video-app-react@noreply.github.com>
CC: m1kjh43l2020 <afigueroa@metrix-networks.net>; Mention <mention@noreply.github.com>
Asunto: Re: [twilio/twilio-video-app-react] fixed presenter screen always full screen (#407)

 

Hey @m1kjh43l2020 <https://github.com/m1kjh43l2020>  - thanks for the additional details!

So in order to do this, we will need a way to determine which participant should be full screen all the time. I'm not sure how you would want to do this, but I have an idea:

Let say that we wanted the participant whose name ends in -presenter to be full screen. With this, everyone would enter the room with their regular names, but the person that adds -presenter to their name (like timmydoza-presenter) would be full screen.

For this, we just need to modify the useMainParticipant.tsx file. This is the file that determines which participant will be full screen. Try adding these changes:

import useVideoContext from '../useVideoContext/useVideoContext';
import useDominantSpeaker from '../useDominantSpeaker/useDominantSpeaker';
import useParticipants from '../useParticipants/useParticipants';
import useScreenShareParticipant from '../useScreenShareParticipant/useScreenShareParticipant';
import useSelectedParticipant from '../../components/VideoProvider/useSelectedParticipant/useSelectedParticipant';
 
export default function useMainParticipant() {
  const [selectedParticipant] = useSelectedParticipant();
  const screenShareParticipant = useScreenShareParticipant();
  const dominantSpeaker = useDominantSpeaker();
  const participants = useParticipants();
  const {
    room: { localParticipant },
  } = useVideoContext();
  const remoteScreenShareParticipant = screenShareParticipant !== localParticipant ? screenShareParticipant : null;
 
+ const presenterParticipant = participants.find(participant => /-presenter$/.test(participant.identity));
 
  // The participant that is returned is displayed in the main video area. Changing the order of the following
  // variables will change the how the main speaker is determined.
-  return selectedParticipant || remoteScreenShareParticipant || dominantSpeaker || participants[0] || localParticipant;
+  return selectedParticipant || presenterParticipant || remoteScreenShareParticipant || dominantSpeaker || participants[0] || localParticipant;
}

This should do the trick! The app should work the same for the -presenter participant, but everyone else will see the -presenter in full screen. Also, with the code above, other users would still be able to pin other participants to make them full screen.

Let me know if you have any questions about this. We're happy to help!

**Comment by timmydoza** [comment]
> I am sending a variable as "presenter = 1" by the Url (? presenter = 1). This is the trigger to know that the one who enters is the one that will always be seen in full screen, apart from the solution you gave me, how could I use this variable only to discriminate and know that the one who entered is the presenter?

Thanks for the question @m1kjh43l2020!

I've thought about this more, and I think that we still need to add something like `-presenter` to the end of the participant that should be full screen. Right now, there is no way to add metadata about a participant when they connect to a room, (see [this issue](https://github.com/twilio/twilio-video.js/issues/864)). So the only way for other participants to know which one should be full screen is to alter the participant identity in some way. 

But I think we can make this work with your idea too (adding `presenter=1`). We can add some code so the `-presenter` suffix is added to the participant's identity when the `presenter=1` parameter is present. We can change [this code here](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx#L65-L67) to do this:

```
  const handleJoin = () => {
    const participantName = window.location.search.includes('presenter=1') ? name + '-presenter' : name;
    getToken(participantName, roomName).then(token => connect(token));
  };
  ```
  
  Then, we can also add some code so that the other participants don't see the `-presenter` suffix that is added to the participant's name. We can update [this line](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MainParticipantInfo/MainParticipantInfo.tsx#L114) to look like this:
``` 
participant.identity.replace('-presenter', '')}
```
  
  And the same thing can be done [on this line](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ParticipantInfo/ParticipantInfo.tsx#L193) too.
  
  With these changes, we can choose a participant to be full screen with the `presenter=1` query parameter in the URL, and the other participants won't see that the full screen participant's identity has been changed. Please let me know if you have any questions about this idea. I hope it works out for you!

**Comment by m1kjh43l2020** [comment]
Yesss! Works! Thanks Timmy. Works like a charm 😀

________________________________
De: timmydoza <notifications@github.com>
Enviado: Friday, February 12, 2021 12:22:04 PM
Para: twilio/twilio-video-app-react <twilio-video-app-react@noreply.github.com>
Cc: Alejandro Figueroa <afigueroa@metrix-networks.net>; Mention <mention@noreply.github.com>
Asunto: Re: [twilio/twilio-video-app-react] fixed presenter screen always full screen (#407)


I am sending a variable as "presenter = 1" by the Url (? presenter = 1). This is the trigger to know that the one who enters is the one that will always be seen in full screen, apart from the solution you gave me, how could I use this variable only to discriminate and know that the one who entered is the presenter?

Thanks for the question @m1kjh43l2020<https://github.com/m1kjh43l2020>!

I've thought about this more, and I think that we still need to add something like -presenter to the end of the participant that should be full screen. Right now, there is no way to add metadata about a participant when they connect to a room, (see this issue<https://github.com/twilio/twilio-video.js/issues/864>). So the only way for other participants to know which one should be full screen is to alter the participant identity in some way.

But I think we can make this work with your idea too (adding presenter=1). We can add some code so the -presenter suffix is added to the participant's identity when the presenter=1 parameter is present. We can change this code here<https://github.com/twilio/twilio-video-app-react/blob/master/src/components/PreJoinScreens/DeviceSelectionScreen/DeviceSelectionScreen.tsx#L65-L67> to do this:

  const handleJoin = () => {
    const participantName = window.location.search.includes('presenter=1') ? name + '-presenter' : name;
    getToken(participantName, roomName).then(token => connect(token));
  };


Then, we can also add some code so that the other participants don't see the -presenter suffix that is added to the participant's name. We can update this line<https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MainParticipantInfo/MainParticipantInfo.tsx#L114> to look like this:

participant.identity.replace('-presenter', '')}


And the same thing can be done on this line<https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ParticipantInfo/ParticipantInfo.tsx#L193> too.

With these changes, we can choose a participant to be full screen with the presenter=1 query parameter in the URL, and the other participants won't see that the full screen participant's identity has been changed. Please let me know if you have any questions about this idea. I hope it works out for you!

**Comment by timmydoza** [comment]
Great to hear! Please let me know if you need anything else.

**Comment by m1kjh43l2020** [comment]
Hy Timmy, I have a problem that I had not seen, do you remember that you helped me to leave the video of the fixed presenter ?, Well everything is super good, but I realize that in the case of the presenter always puts the presenter also in the windows as if it were a More user, I attach an image showing what I comment, eye, that only apsa in the presenter window, will there be any way that it does not appear? Since it seems that there are more users when it is the same in the list of participants?(prese-Presentador its twice!!!
I am attaching an image, if it does not appear, tell me to upload it directly to github.
Thank you

***@***.***D7226F.857FF9F0]


De: timmydoza ***@***.******@***.***>
Enviado el: miércoles, 3 de febrero de 2021 03:28 p. m.
Para: twilio/twilio-video-app-react ***@***.***>
CC: Alejandro Figueroa ***@***.***>; Mention ***@***.***>
Asunto: Re: [twilio/twilio-video-app-react] fixed presenter screen always full screen (#407)


Hey @m1kjh43l2020<https://github.com/m1kjh43l2020> - thanks for the additional details!

So in order to do this, we will need a way to determine which participant should be full screen all the time. I'm not sure how you would want to do this, but I have an idea:

Let say that we wanted the participant whose name ends in -presenter to be full screen. With this, everyone would enter the room with their regular names, but the person that adds -presenter to their name (like timmydoza-presenter) would be full screen.

For this, we just need to modify the useMainParticipant.tsx file. This is the file that determines which participant will be full screen. Try adding these changes:

import useVideoContext from '../useVideoContext/useVideoContext';

import useDominantSpeaker from '../useDominantSpeaker/useDominantSpeaker';

import useParticipants from '../useParticipants/useParticipants';

import useScreenShareParticipant from '../useScreenShareParticipant/useScreenShareParticipant';

import useSelectedParticipant from '../../components/VideoProvider/useSelectedParticipant/useSelectedParticipant';



export default function useMainParticipant() {

  const [selectedParticipant] = useSelectedParticipant();

  const screenShareParticipant = useScreenShareParticipant();

  const dominantSpeaker = useDominantSpeaker();

  const participants = useParticipants();

  const {

    room: { localParticipant },

  } = useVideoContext();

  const remoteScreenShareParticipant = screenShareParticipant !== localParticipant ? screenShareParticipant : null;



+ const presenterParticipant = participants.find(participant => /-presenter$/.test(participant.identity));



  // The participant that is returned is displayed in the main video area. Changing the order of the following

  // variables will change the how the main speaker is determined.

-  return selectedParticipant || remoteScreenShareParticipant || dominantSpeaker || participants[0] || localParticipant;

+  return selectedParticipant || presenterParticipant || remoteScreenShareParticipant || dominantSpeaker || participants[0] || localParticipant;

}

This should do the trick! The app should work the same for the -presenter participant, but everyone else will see the -presenter in full screen. Also, with the code above, other users would still be able to pin other participants to make them full screen.

Let me know if you have any questions about this. We're happy to help!

**Comment by timmydoza** [comment]
Hi @m1kjh43l2020 - good to hear from you again!

I'd happy to help you solve this issue. Looks like the screen shot didn't come through though. Can you please try uploading it directly to github? Thanks.

**Comment by m1kjh43l2020** [comment]
Hi Timmy, thanks i upload again
![ee](https://user-images.githubusercontent.com/73363188/113591735-e9fd0280-95f9-11eb-9173-581b243b2534.png)

**Comment by timmydoza** [comment]
Thanks for the image @m1kjh43l2020. I see what you mean!

To remove the extra thumbnail from the sidebar, we can filter the list of participants to remove the `-Presentador` participant.

This can be done inside [ParticipantList.tsx](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ParticipantList/ParticipantList.tsx):
```diff
 
   if (participants.length === 0) return null; // Don't render this component if there are no remote participants.
 
+  const filteredParticipants = participants.filter(participant => !/-Presentador$/.test(participant.identity));
+
   return (
     <aside
       className={clsx(classes.container, {
@@ -62,7 +64,7 @@ export default function ParticipantList() {
       <div className={classes.scrollContainer}>
         <div className={classes.innerScrollContainer}>
           <Participant participant={localParticipant} isLocalParticipant={true} />
-          {participants.map(participant => {
+          {filteredParticipants.map(participant => {
             const isSelected = participant === selectedParticipant;
             const hideParticipant =
               participant === mainParticipant && participant !== screenShareParticipant && !isSelected;
```

Please try this out and let me know how it works!

**Comment by timmydoza** [comment]
Let me know if there are any more questions! I'm happy to reopen the issue and continue the discussion.
