### ISSUE TITLE
Published track is "black screen" when hardware acceleration is disabled

### ISSUE THREAD

**Issue by NoahFisher** [twilio/twilio-video-app-react#408]
**Describe the bug**
When a user joins a video room with hardware acceleration is disabled on their browser, their video track is a published to other participants as a black screen.

**To Reproduce**
1. Assume there are two participants, Participant1 and Participant2. Disable hardware acceleration in Chrome browser for Participant1.
2. Participant1 and Participant2 join room
3. From Participant2's point of view, Participant1's video stream is a black screen. No errors are reported in the console, or in the Video logs.

**Expected behavior**
Participant1's track should be a non-black screen or an error should be raised that browser requires hardware acceleration to be enabled.

**Screenshots**
N/A, but available upon request. 

**Environment (please complete the following information):**
 - OS: MacbookPro, OS 10.15.7
 - Browser: Chrome Version 88.0.4324.96 
 - SDK Version: [e.g 2.10.0]

**Additional context**

Potentially related chromium issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1168948

**Comment by timmydoza** [comment]
Thanks for the issue @NoahFisher!

We were able to reproduce the issue. It seems to occur with both VP8 and H264 codecs. 

The problem that you describe does appear to be related to the Chromium bug that you shared. At this point, we aren't aware of any workarounds, so we will have to wait for that Chromium bug to be fixed.

**Comment by timmydoza** [comment]
Hey @NoahFisher. Looks like the above-referenced Chromium bug has been fixed. I have also verified that the app works as expected when hardware acceleration is disabled. 

Thanks again for raising the issue. Please let us know if there's anything else we can take a look at!
