### ISSUE TITLE
Where is the deployed link

### ISSUE THREAD

**Issue by nifty-coder** [twilio/twilio-video-app-react#413]
Please send me the deployed link. I want to see the demo

**Comment by timmydoza** [comment]
Hi @nifty-coder thanks for the question!

Unfortunately, we do not have a publicly available demo of this application. Instead, you can quickly deploy this app yourself and share the link with friends!

Here is a youtube video on how to deploy this app: https://www.youtube.com/watch?v=pSASQcHrmPg
And here is a Twilio blog post with a tutorial: https://www.twilio.com/blog/open-source-video-apps-reactjs-ios-android

Additionally, the steps to quickly deploy this app are described in the app's [README](https://github.com/twilio/twilio-video-app-react).

Good luck! Please let me know if you have any additional questions.
