### ISSUE TITLE
Chat integration including plain text and media / files

### ISSUE THREAD

**Issue by hoponaillc** [twilio/twilio-video-app-react#414]
Do you have a sample available for integrating Twilio chat with this react app?

**Comment by timmydoza** [comment]
Hi @hoponaillc - thanks for the feature request!

We currently don't have sample code for adding chat to this app. However, this feature is currently under development, and it will be released in a few weeks. I'll leave this issue open and let you know when the feature has been released.

**Comment by olipyskoty** [comment]
Hey @hoponaillc! We are excited to inform you that support for the Twilio Conversations feature has officially been added to this app! Be sure to check out the `README.md` for more information on how to get set up. Please do not hesitate to reach out if you have any questions and/or feedback. Enjoy!
