### ISSUE TITLE
Change simulcast on the fly

### ISSUE THREAD

**Issue by alex-konoval** [twilio/twilio-video-app-react#419]
**Question**
Is there a way to change simulcast enabled/disabled on the fly?
**Additional context**
We are using group rooms, and in most cases, there are two participants, so there is no need for simulcast. But in some cases, there can be more participants. It sounds like a good idea to change the simulcast option on the fly if there are more than two participants in the room. But I don't see how to do it, or even is it possible to change without room reconnection.
Thank you for any advice.

**Comment by timmydoza** [comment]
Thanks for the question @alex-konoval!

This is a great question! Unfortunately, there is no way to change the simulcast setting while in a room. The simulcast preference can only be set when connecting to a room.

You raise a great point though - it would be very useful to be able to change these things on the fly. This is something that we are looking into on our side. In the coming months, we hope to release some features in the [twilio-video.js](https://github.com/twilio/twilio-video.js) that will help developers better optimize their applications in a manner similar to what you describe.

In the meantime, be sure to check out the [twilio-video.js](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md) every once in a while. This is where we will announce the new features.

**Comment by alex-konoval** [comment]
Sorry if I asked it in the wrong place. And **thank you** for the answer!

**Comment by timmydoza** [comment]
Not a problem - happy to help!
