### ISSUE TITLE
control buttons are not rendering as shows in the readme

### ISSUE THREAD

**Issue by sowsan** [twilio/twilio-video-app-react#422]
How can I see the media buttons like in the Github readme file screenshots?

![image](https://user-images.githubusercontent.com/11544153/108285461-20b7b000-7155-11eb-8c07-143bba3181e1.png)

I am always getting the below buttons in desktop and mobile

![image](https://user-images.githubusercontent.com/11544153/108285419-0c73b300-7155-11eb-81b3-a16ed84e6dbe.png)

**Comment by timmydoza** [comment]
Thanks for the question @sowsan!

The buttons that you see in the picture belong to our mobile video apps. Be sure to check out our mobile apps for [iOS](https://github.com/twilio/twilio-video-app-ios) and [Android](https://github.com/twilio/twilio-video-app-android). 

Unfortunately, the style of buttons that you see in that picture is not available in this repository.
