### ISSUE TITLE
Camera turned off default if we have user.UserName and RoomName by default

### ISSUE THREAD

**Issue by artem-gorokhovskii** [twilio/twilio-video-app-react#423]
We have already a room name and a user name (external) and we want to reuse them in Twilio app. We want to skip a step by entering userName and room name and we want to start from the second screen:

![a4](https://user-images.githubusercontent.com/45370857/108392495-d5b89e00-7223-11eb-84d0-00c06f9b34ee.PNG)

With passing user name and room name we're skipping the first step, but we don't ask permission for the camera (by default) in this case. We're asking only for microphone permission.

We need to use the camera by default ( and request camera permission by default ).

**To Reproduce**
1. Use mock user.displayName and roomName (pass it in PreJoinScreens.tsx)
2. Open app, skip the first step and see the screen with choosing devices (turn on\off camera, turn on\off microphone).

**Expected behavior**
Permissions for camera and microphone were requested, the camera turned on by default.

**Current behavior**
Permissions requested only for the microphone. The camera turned off by default.

**Screenshots**
Case 1 [Problem]
Used mocked user.displayName and URLRoomName
No request for Camera permissions:

![a1](https://user-images.githubusercontent.com/45370857/108392014-55923880-7223-11eb-958b-bedc7dfede02.PNG)

Case 2 [Ok]
Used default code, displayName and roomName entered by hand in the 1st screen
Permission for camera was requested: 

![a2](https://user-images.githubusercontent.com/45370857/108392110-6e025300-7223-11eb-8a2e-e4077fdb8475.PNG)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome Version 88.0.4324.150 (Official Build) (64-bit)
 - App Version: 0.2.1
 - Twilio-video: 2.9.0
 - Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the detailed bug report @artem-gorokhovskii!

I've seen this issue myself - and I merged in a fix for it in a previous pull request: #401

Looks like you are on version 0.2.1 of the app, and the fix is in version 0.2.2. Can you please try using the newer version of the app to see if it resolves the issue for you?

**Comment by artem-gorokhovskii** [comment]
@timmydoza  thank you for your response.

As I can see - currently we have only **0.2.2-prerelease** tag (which was created on Dec 8, 2020).
Could you please say when you're going to create release 0.2.2?

**Comment by timmydoza** [comment]
Hey @artem-gorokhovskii!

Sorry about that. Looks like I never made a release for 0.2.2. I created one today: https://github.com/twilio/twilio-video-app-react/releases/tag/v0.2.2

I hope it does the trick for you!

**Comment by artem-gorokhovskii** [comment]
@timmydoza thanks for response!
I checked it in 0.2.3 version and it asks for camera permission also [OK].
Thank you!

![image](https://user-images.githubusercontent.com/45370857/108587453-a9586b00-7364-11eb-9c3a-d033da967874.png)

**Comment by artem-gorokhovskii** [comment]
Didn't reproduce in 0.2.3
