### ISSUE TITLE
Source of video doesn't change

### ISSUE THREAD

**Issue by artem-gorokhovskii** [twilio/twilio-video-app-react#425]
**Describe the bug**
When you're changing video input with turned off camera (but permission for the camera - allow) - value in select changes, but the video is capturing from the previous device.

**To Reproduce**
1. Open the **browser in incognito**
2. Go to main page
3. Move to the second step (with choosing devices to join)
![image](https://user-images.githubusercontent.com/45370857/108488790-d6981100-72b1-11eb-82d3-b44b069567f6.png)
4. Check, that camera permission is Allowed
5. See a picture from your camera (your camera turned on)
6. Turn off your camera (you will see a button "Start video" and crossed out the camera)
![image](https://user-images.githubusercontent.com/45370857/108488910-fe877480-72b1-11eb-8257-173d9b885fff.png)
7. Open Settings -> Audio and video settings
8. Change one video input to another and press "Done"
9. Turn on your camera and see. You've chosen another source of your video input, but your receive picture from the first video device

**Expected behavior**
Camera picture is from selected device in video input.

**Real behavior**
Camera picture is from the first device, but we chose another video input device

**Screenshots**
selected video input: HP HD Camera (black screen - covered camera, it's ok):
![image](https://user-images.githubusercontent.com/45370857/108489973-40fd8100-72b3-11eb-9737-810f6b80a930.png)

turned off camera:
![image](https://user-images.githubusercontent.com/45370857/108489740-faa82200-72b2-11eb-906d-0e10638928fe.png)

opened audio and video settings.
**note, that initially we don't have video input device:**
![image](https://user-images.githubusercontent.com/45370857/108490099-65595d80-72b3-11eb-82a9-2cc27a56f957.png)

chosen another video input device: OBS Virtual Camera
and pressed "Done"
![image](https://user-images.githubusercontent.com/45370857/108490138-6f7b5c00-72b3-11eb-9470-1d432c16b548.png)

Start your video.
You will see the previous source of the video (what is incorrect, expected another video source):
![image](https://user-images.githubusercontent.com/45370857/108490221-8cb02a80-72b3-11eb-8333-027a81c5ef5c.png)

Environment:

OS: Windows 10
Browser: Chrome Version 88.0.4324.150 (Official Build) (64-bit)
App Version: 0.2.1
Twilio-video: 2.9.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the issue @artem-gorokhovskii!

I can confirm this issue. I think was also fixed is [version 0.2.3](https://github.com/twilio/twilio-video-app-react/releases/tag/v0.2.3). Can you please try this newer version and let me know if it helps?

Thanks again!

**Comment by artem-gorokhovskii** [comment]
@timmydoza Thanks for your response!
Unfortunately, this problem also reproduces in 0.2.3.

**Comment by timmydoza** [comment]
Hey @artem-gorokhovskii!

Looks like 0.2.3 only partially fixed the issue. I can confirm that there is still a bug to fix in 0.2.3.  It looks like it only happens the first time a user grants permission to the application. All other times a user visits this app it seems to work ok. 

I'll start working about a fix. Stay tuned!
