### ISSUE TITLE
Can't change source of video

### ISSUE THREAD

**Issue by artem-gorokhovskii** [twilio/twilio-video-app-react#426]
Behavior looks like https://github.com/twilio/twilio-video-app-react/issues/423.

We need to use our external user.displayName and roomName. We can't change the video input device in that case.

**To Reproduce**

We can use mocked data (in src\components\PreJoinScreens\PreJoinScreens.tsx):
![image](https://user-images.githubusercontent.com/45370857/108493011-e2d29d00-72b6-11eb-849f-2257b382a746.png)

1. Go to page with choosing device:
![image](https://user-images.githubusercontent.com/45370857/108493285-31803700-72b7-11eb-959b-9b6b64239336.png)
2. Check, that your video is turned off.
3. Open Settings -> Audio and Video settings.
4. You will no initial value in video input device:
![image](https://user-images.githubusercontent.com/45370857/108493610-9045b080-72b7-11eb-879d-ca1ea6eb1d51.png)

5. Changing video device is useless, we can't change it:
![image](https://user-images.githubusercontent.com/45370857/108493567-8623b200-72b7-11eb-9373-dbe5f84248c9.png)

**Expected behavior**
We have an initial value in the video input device.
We can change the value in the video input device.

**Real behavior**
We have no initial value and we can't change it.

**Environment:**

OS: Windows 10
Browser: Chrome Version 88.0.4324.150 (Official Build) (64-bit)
App Version: 0.2.1
Twilio-video: 2.9.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the question @artem-gorokhovskii!

I can confirm the issue that you described. I just released version [0.2.3](https://github.com/twilio/twilio-video-app-react/releases/tag/v0.2.3) of this app which contains a fix that should help you out. The fix lets users change their video device while their camera is off. 

More information (and a gif) in the pull request here: #412

I hope it fixes your issue! Please let me know. Thanks!

**Comment by artem-gorokhovskii** [comment]
@timmydoza thank you for your response!

Tested in 0.2.3.

Initially, it doesn't have a pre-selected device:
![image](https://user-images.githubusercontent.com/45370857/108587508-f6d4d800-7364-11eb-8dc9-87b379af755d.png)

We can make a choice (previously we can't):
![image](https://user-images.githubusercontent.com/45370857/108587520-15d36a00-7365-11eb-97c3-1e9b59c925c5.png)

Start video - video from another video input (not one which I've chosen):
![image](https://user-images.githubusercontent.com/45370857/108587538-300d4800-7365-11eb-9a0c-e13f515950cc.png)

We don't have a pre-selected video input device, but we can change it, but it doesn't change the real video input source.

But we also have the behavior of the next bug, which also reproducing on 0.2.3: https://github.com/twilio/twilio-video-app-react/issues/425

**Comment by timmydoza** [comment]
Thanks for the additional information @artem-gorokhovskii! 

I'm going to close this issue. It is very similar to #425, so this issue feels like a duplicate. We will be working on a fix though (just look at #425 for the status of the fix).
