### ISSUE TITLE
Can't access audio if camera is not enabled

### ISSUE THREAD

**Issue by artem-gorokhovskii** [twilio/twilio-video-app-react#428]
Allow access to the microphone and block access to the camera.
In that case, we can't choose Audio input:
![image](https://user-images.githubusercontent.com/45370857/108500466-dd7a5000-72c0-11eb-9a2f-abd94c237a1a.png)

**How to reproduce**

1. Move to the page with choosing devices
![image](https://user-images.githubusercontent.com/45370857/108500548-000c6900-72c1-11eb-8602-869725a01d36.png)
2. Block camera and allow microphone
![image](https://user-images.githubusercontent.com/45370857/108500605-14e8fc80-72c1-11eb-95e8-b131a1f3191a.png)
3. Open Settings -> Audio and Video Settings
There we don't have selected audio input
![image](https://user-images.githubusercontent.com/45370857/108500683-3a760600-72c1-11eb-9e50-2ba0f137eed9.png)
4. Try to change audio input (it stays empty after changing)
![image](https://user-images.githubusercontent.com/45370857/108500753-51b4f380-72c1-11eb-85e4-9f88418023d7.png)

**Expected behavior**
We have an initial audio input device.
We can change the audio input device.

**Real behavior**
We don't have an initial audio input device.
We can't change the audio input device.

**Screenshots**
![cdeefb70-d77d-4273-b602-56f556f6a6ac](https://user-images.githubusercontent.com/45370857/108500219-7fe60380-72c0-11eb-9c1b-c5dec8bfe88b.gif)

**Environment:**
OS: Windows 10
Browsers: Chrome Version 88.0.4324.150 (Official Build) (64-bit), Edge Version 88.0.705.68 (Official build) (64-bit)
App Version: 0.2.1
Twilio-video: 2.9.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the issue @artem-gorokhovskii!

I can reproduce the issue that you describe. We don't have a fix at the moment - I'll have to work on one. I've created an internal ticket for this bug and I've added it to our backlog.

Thanks again!

**Comment by Snugg-App** [comment]
@timmydoza any timeline on the fix or should I go down the rabbit hole? :-)
