### ISSUE TITLE
Simplified version or detailed documentation

### ISSUE THREAD

**Issue by sowsan** [twilio/twilio-video-app-react#435]
I am new to TypeScript and React. Need to develop an app using these framework with Twilio. Got this sample using react hook https://github.com/philnash/twilio-video-react-hooks but it is written JS not using TSX. If there is a simplified version or a good documentation on this sample project in this repo would be very helpful!

**Comment by timmydoza** [comment]
Thanks for the question @sowsan!

Unfortunately we don't have a simplified version of this app. We do have the [video quickstart](https://github.com/twilio/video-quickstart-js) application, which is simpler than this one, but it is not written in React. I do recommend taking a look at it though as it has many useful code examples. 

Are you trying to build a new app from scratch? Or are you trying to modify this app? If you can let me know more about your use case, perhaps I can help to point you in the right direction.

**Comment by timmydoza** [comment]
Closing this issue, but please let me know if you have any other questions. We're always happy to help!
