### ISSUE TITLE
UnsupportedBrowserWarning does not display on some unsupported devices

### ISSUE THREAD

**Issue by LucaProvencal** [twilio/twilio-video-app-react#439]
**Describe the bug**
On iPhone 6 Chrome and other unsupported devices, the UnsupportedBrowserWarning does not display.

**To Reproduce**
1. Try to load the app on iPhone 6, Chrome

**Expected behavior**
UnsupportedBrowserWarning displays

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/25271943/109358481-d370c800-7851-11eb-8d7b-20e87aa224e6.png)

**Environment (please complete the following information):**
 - OS: iOS 12.5.1
 - Browser: Chrome 87.0.4280.77
 - App Version: 0.2.3
 - SDK Version: 2.11.0
 - Node.js version: 15.8.0

**Additional context**
I created a branch for this with fixes. Happy to push if you'd like and are able to grant access.

**Comment by timmydoza** [comment]
Thanks for the issue @LucaProvencal!

It looks like the twilio-video SDK may be returning `true` for `isSupported` here, when it should be returning `false`. 

Can you do me a favor and send me the user agent that is used on the iPhone running Chrome? With this we will be able to test how the SDKs `isSupported` function responds to the user agent, and make changes accordingly.

**Comment by LucaProvencal** [comment]
UA:
`Mozilla/5.0 (iPhone; CPU iPhone OS 12_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1`

and some more info:

![unnamed](https://user-images.githubusercontent.com/25271943/109529682-f682be00-7a83-11eb-8cec-a326ffaad6fa.jpg)

**Comment by timmydoza** [comment]
Thanks for the extra info @LucaProvencal!

I'm trying to determine in there is an issue in this video app, or if there is an issue in the twilio-video.js library. Can you please visit this page on your iPhone 6 in Chrome and let me know what it says? It should say that `Video.isSupported` is `false`. 

https://twilio-video-is-supported.glitch.me/

Thanks!

**Comment by timmydoza** [comment]
Hey @LucaProvencal - never mind my previous comment. I found the issue.

The `<UnsupportedBrowserWarning`> was set up in such a way that the app still tried to access `navigator.mediaDevices` even when `Video.isSupported` is `false`. I have created this [pull request](https://github.com/twilio/twilio-video-app-react/pull/447) to fix the issue, which I'm going to merge in now. 

Please let me know if this doesn't fix your issue. Thanks again for pointing it out!

**Comment by LucaProvencal** [comment]
@timmydoza Nice! Looks good. Thanks.
