### ISSUE TITLE
Not seeing video of a mobile participant from the react web app

### ISSUE THREAD

**Issue by rodriguezc** [twilio/twilio-video-app-react#442]
Hi, 
I'm not sure if this is a bug from this react app example, but:

When creating a small group room 
ex: 2 mobile participants and 2 web participants

From the react web app:
- When a mobile join a video (flutter app), we don't see the video of the mobile participant from the web app
- But we see the videos of others web participants

From the mobile app:
- We see all videos participants (web **& mobiles**)

Sound is working.

**To Reproduce**
1. Create a room
2. Have two or more participants in it (at least 1 mobile and 1 web)
3. Join the room
4. In the web app the video of the mobile participant is not displayed: it is like if the mobile stopped his video)
5. In others mobile we see all participants video.

**Expected behavior**
We see the video of the mobile participant from the webapp

**Screenshots**
N/A

**Environment (please complete the following information):**
-  MacOS (chrome & safari last versions)
- Current master 

**Additional context**
N/A

**Comment by timmydoza** [comment]
Thanks for the issue @rodriguezc!

It's hard to say what the problem might be without seeing the code to the Flutter app, but I have a guess.

In order for the React app to differentiate between a user's camera track and a user's screen share track, we give the tracks names before they are published to the room. Then, this app renders the track named 'camera' in the participant thumbnails, and it renders any screen share track (with name 'screen') in the main window. 

In your flutter app, can you try naming a user's camera track "camera" before publishing it to the room? I'm not sure how this would work in flutter, but in JS, we can pass a `name` property in the `CreateLocalTrackOptions` object: https://media.twiliocdn.com/sdk/js/video/releases/2.12.0/docs/global.html#CreateLocalTrackOptions

Let me know how this works out for you. Thanks!

**Comment by rodriguezc** [comment]
Hi @timmydoza ,

Thank you for your answer. You were right. We had to specify "camera" as track name in the flutter app. For my understanding, why do you look for the track name instead of track kind for the video in this react app ? 
Thank you,

Best regards,

**Comment by timmydoza** [comment]
Great question @rodriguezc!

We look at `track.name` instead of `track.kind` because it is possible for a user to be publishing multiple video tracks. When a user is sharing their screen while their camera is on, they are publishing two video tracks to the room. Since both of these tracks have `track.kind` equal to `'video'`, we need to look at the `name` property in order to distinguish them. For example:

```
const cameraTrack = tracks.find(track => track.name.includes('camera'));
const screenShareTrack = tracks.find(track => track.name.includes('screen'));
```

I'll close this issue since it sounds like your flutter app is working as expected, but please let me know if you have any other questions. We're always happy to help!
