### ISSUE TITLE
'You are sharing your screen' message is shown after reconnection to the room

### ISSUE THREAD

**Issue by Viktar-krauchyk** [twilio/twilio-video-app-react#444]
**Describe the bug**
User who shared his screen and was disconnected from the room while joining this room again receives 'You are sharing your screen' message. However sharing stops after disconnection.

**To Reproduce**
1. Join the room
2. Start sharing the screen
3. Disconnect from the internet
4. Wait 1 minute
5. Connect internet
6. Join the room

**Expected behavior**
User doesn't see 'You are sharing your screen' message

**Real behavior**
'You are sharing your screen' message with 'Stop Sharing' button is displayed.

**Screenshots**
![stop sharing2](https://user-images.githubusercontent.com/79318949/109773547-63c35a00-7c10-11eb-8b67-2659b1af4780.gif)

**Environment (please complete the following information):**
OS: Windows 10
Browser: Chrome Version 88.0.4324.190 (Official Build) (64-bit)
App Version: 0.2.3
Twilio-video: 2.11.0
Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the detailed bug report @Viktar-krauchyk!

I can confirm that this bug exists. I have created a ticket in our backlog to fix the issue.

**Comment by timmydoza** [comment]
Thanks again for the issue @Viktar-krauchyk! I've merged the bugfix into `master`. I also found that the local audio and video tracks weren't being stopped on a network disconnection, so I added in a fix for that too.

**Comment by artem-gorokhovskii** [comment]
@timmydoza hello, when you are going to create v0.2.4 release?
Thanks

**Comment by timmydoza** [comment]
Hi @artem-gorokhovskii - I'll try to release a new version early next week. I'd like to try and get some more bug fixes in if I can. 

In the meantime, you can still download the `master` branch (with this screen share fix) with this command:

`git clone https://github.com/twilio/twilio-video-app-react.git`.

Or if you'd prefer, you can use the "Code" menu on the main page to download a zip file of the repository:

![image](https://user-images.githubusercontent.com/12685223/111010432-c2e14700-8353-11eb-9718-ca2d99952ed0.png)
