### ISSUE TITLE
Issue with the twilio conversation service. Client is not getting created.

### ISSUE THREAD

**Issue by mohitpd** [twilio/twilio-video-app-react#449]
**The app is popping up an error that states "There was a problem connecting to Twilio's conversation service." and the chat feature is not working.**
In the \twilio-video-app-react-feature-conversations\src\components\ChatProvider\index.tsx file the chatClient is not getting created and hence it is giving an error.

**To Reproduce**
Run the app on localhost and after giving the input parameters and joining the room. Error pops up.

**Expected behavior**
chatClient should be created and chat feature should be working properly.

**Screenshots**
![Screenshot (731)](https://user-images.githubusercontent.com/47710928/110215541-6227b980-7ed0-11eb-8f84-56c802071dcf.png)
![Screenshot (732)](https://user-images.githubusercontent.com/47710928/110215547-66ec6d80-7ed0-11eb-87cb-b6455ba923fe.png)

**Additional context**
The error occurred is **"Uncaught (in promise) SyncError: Transport failure: UNKNOWN_ACTIVE_PRODUCT (status: 0, code: 0)
    at mapTransportError"**. it doesn't have any reference on Google as much researched by me.

**Comment by timmydoza** [comment]
Thanks for the issue @mohitpd - and thanks for trying out the `feature/conversations` branch!

Unfortunately, the conversations feature isn't finished. It is still under active development, so it may break in its current state. 

We hope to be done with the feature in a week or two. When it's finished, we'll merge it into the `master` branch, and create a new release for it. So keep an eye on our [releases](https://github.com/twilio/twilio-video-app-react/releases) page or our [CHANGELOG](https://github.com/twilio/twilio-video-app-react/blob/master/CHANGELOG.md) for updates!

**Comment by Mars-2030** [comment]
Hi @timmydoza 
is this feature active now ,, I am still facing the same error msg?
