### ISSUE TITLE
Is this example app expected to ever run a Preflight test?

### ISSUE THREAD

**Issue by martinblostein** [twilio/twilio-video-app-react#463]
**Question**: 
Should I ever expect `PreflightTest` to render in the current state of this example app? Is there further configuration needed to enable this? It seems to me that this component will never render, and so a preflight test will never happen.

**Context**:
The below applies to the latest commit on master: `a6fc6c982`, as well as the latest release: [v0.2.3](https://github.com/twilio/twilio-video-app-react/releases/tag/v0.2.3).

The only place that a preflight test seems like it could be invoked is in the `PreflightTest` component. But it seems to me this component will never render, because the only place it is referenced is in `PreJoinScreens`:
https://github.com/twilio/twilio-video-app-react/blob/a6fc6c9826bdb39fe9cb5be423bdb17a44286180/src/components/PreJoinScreens/PreJoinScreens.tsx#L58
where is it only rendered if `Video.testPreflight` is truthy, where `Video` is the default export from `twilio-video`. However, the version of `twilio-video` in `package-lock.json`, `v2.11.0`, does not seem to define such a function in its default export.

Confusingly, this export is explicitly declared on the `twilio-video` package in `types.ts`:

https://github.com/twilio/twilio-video-app-react/blob/a6fc6c9826bdb39fe9cb5be423bdb17a44286180/src/types.ts#L4-L16

So it appears, at least from the Typescript compilers point of view, that `PreflightTest` should _always_ render. (TSC says about the above line from `PreJoinScreens`: `This condition will always return true since the function is always defined. Did you mean to call it instead?`) But in all of my testing this is never the case, and digging through the code and that of the installed version of `twilio-video` I don't see how it could ever be.

I'm not sure if this is a bug, or if am I misunderstanding something.

Note: There is a test that checks that `PreJoinScreens` renders `PreflightTest`, but in this test the `Video.testPreflight` is mocked, so of course the component is rendered.

**More Digging**:
It seems that `PreflightTest` was introduced in [v0.52](https://github.com/twilio/twilio-video-app-react/releases/tag/v0.52). Checking out this version, it seems that it is using version `2.8.0-beta.1` of `twilio-video`, which _does_ export a `testPreflight` function, so maybe this is a "regression" caused by a feature depending on a beta feature of `twilio-video` that was never released? I don't see any mention of preflight tests in the [change log for `twilio-video`](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md). 

If it is the case that preflight video is not enabled in the core `twilio-video` library, I would suggest removing the related components from the example library, or at least removing the type declaration that makes it appear that `twilio-video` exports a preflightTest function. If seems like something that should be on a different branch with a beta version of the core library installed.

**Comment by timmydoza** [comment]
Thanks for the question @martinblostein!

This is a very good question that you raise. In short, yes - this app will have a preflight test implemented in it in the future. 

This app did run the preflight test that was found in the 2.8.0-beta version of the twilio-video SDK, but that preflight test was just a beta feature and it didn't make it into the current version of the SDK. We collected customer feedback about this beta preflight test, and we will be developing a new preflight test that will be included in future versions of the video SDK as a feature that is generally available. This could be months away, so for the time being, we will update this app to remove the preflight test functionality until it is available in the SDK again. 

Thanks for bringing this to our attention!

**Comment by olipyskoty** [comment]
Hi @martinblostein! The `master` branch has been updated and no longer includes the preflight test. As mentioned in the previous comment, we will be developing a new preflight test in the future, and the UI will be added back once the preflight API is released. So be on the lookout for that 🙂 . Please let us know if you have any other questions!
