### ISSUE TITLE
Is Track Switch Off Mode configuration taken into consideration?

### ISSUE THREAD

**Issue by coreymaher** [twilio/twilio-video-app-react#474]
**Question**
The track switch off mode is configurable in the `ConnectionOptionsDialog` component, but this setting does not appear in the `useConnectionOptions` hook. Does this mean this configuration is ignored and the default track switch off mode is always used instead?

**Additional context**
N/A

**Comment by timmydoza** [comment]
Hey @coreymaher!

I think you are right. It looks like the `settings.trackSwitchOffMode` property never actually makes its way to the `connectionOptions` object. Sorry about that! This looks to be a bug to me, so I'll make a ticket and queue it up. I think this fix is easy enough that we should be able to complete it within the next week or two. 

Thanks for bringing it to our attention!

**Comment by coreymaher** [comment]
Ah, that makes sense. Thanks for looking into this for me!

**Comment by olipyskoty** [comment]
Hi @coreymaher, this fixed has been merged into the `master` branch! 🎉  Please let us know if you have any additional questions.

**Comment by coreymaher** [comment]
Thanks again @olipyskoty!
