### ISSUE TITLE
Few Questions (P2P Room quality, implementing a shared timer, & Chat via Firebase token server)

### ISSUE THREAD

**Issue by ruggierom** [twilio/twilio-video-app-react#483]
I've been using the video app code for a few days and think it's great! I do have a few questions.

Context
I'm using Firebase for Auth & have a custom Token server as a Firebase Cloud Function. My scenario supports a "guest" as an anonymous user and a "host" who must be logged in.

1) For my scenario I want to limit each video call to 15 min. Two people only. I don't want the timer to start until both parties are connected. if one person rejoins after a disconnect I want the timer synced up with the other person. I DO have this working now by saving a "meetingStartTime" key in browser local storage where the key is partially based on a unique "meetingId" I generate.  However, this does not seem like a great solution to me. Is there any shared state that both parties have access to where I can set "meetingStartTime"? Any suggestions on how you would implement this?

2) Settings & Room Types.  
I've been experimenting with Go & P2P rooms as well as small group rooms. The quality of the small group rooms has been consistently great but P2P not so much. I assume this is because of the nature of P2P but wondering are there any suggestions on how to optimize P2P? I see in the code that the Connection Settings menu is not shown if the room type is p2p/go - not sure why this is? Are there any ways to tune/tweak Constraints & statistics to try and optimize for P2P? Any suggestions or things I should research more? 

3) Connecting chat to the room. 
In my Twilio hosted token server, I see how the conversation is connected to the room via getTwilioClient(). However, in my Firebase Token server I can't see how I'd get the context object? I've pasted my code below.

Thanks!!  

import * as functions from 'firebase-functions';
import { Request, Response, Application } from 'express';
import express = require('express');
import * as path from 'path';
import admin = require('firebase-admin');

const cors = require('cors')({ origin: true });
const AccessToken = require('twilio').jwt.AccessToken;
const ChatGrant = AccessToken.ChatGrant;

var app: Application = express();
app.use(cors);

admin.initializeApp({
    credential: admin.credential.applicationDefault()
});

const VideoGrant = AccessToken.VideoGrant;
const MAX_ALLOWED_SESSION_DURATION = 180; //30 min
const twilioAccountSid = 'xxx';
const twilioApiKeySID = 'xxx;
const twilioApiKeySecret = 'xxx';
const twilioConversationsServiceSid = '';

app.use(express.static(path.join(__dirname, 'build')));

app.get('/token', (req: Request, res: Response) => {
    const { identity, meetingId } = req.query;
    var retVal = false;

    const db = admin.firestore();
    const docRef = db.collection('xxx').doc(meetingId!.toString());
    var roomName = "";

    docRef.get()
        .then(doc => {
            if (!doc.exists) {
                console.log('No such document!');
                retVal = false;
            } else {
                roomName = doc?.data()!.roomName.toString();
                retVal = true;

                if (retVal) {
                    const token = new AccessToken(twilioAccountSid, twilioApiKeySID, twilioApiKeySecret, {
                        ttl: MAX_ALLOWED_SESSION_DURATION,
                    });

                    token.identity = identity;
                    token.roomName = roomName;
                    const videoGrant = new VideoGrant({ room: roomName });
                    const chatGrant = new ChatGrant({ serviceSid: twilioConversationsServiceSid });
                    token.addGrant(videoGrant);
                    token.addGrant(chatGrant);

                    res.set('Cache-Control', 'no-cache');
                    res.send(token.toJwt());
                    console.log('Issued token for: ' + { identity } + ' in room: ' + { roomName });
                } else {
                    res.send("");
                    console.log('unable to create token');
                }
            }
        })
        .catch(err => {
            console.log('Error getting document', err);
        });
});

app.get('*', (_, res) => res.sendFile(path.join(__dirname, 'build/index.html')));
app.listen(8081, () => console.log('token server running on 8081'));
exports.app = functions.https.onRequest(app);

**Comment by timmydoza** [comment]
Hi @ruggierom - thanks for the questions. Below are my answers to them:

1 - There isn't any 'shared state' that is offered by the Twilio Video SDK. So I think your solution seems fine. If it works, it works! I can't really think of any way to do this that would be simpler or easier than what you have already implemented. 

2 - For P2P rooms, we recommend disabling simulcast. This is done on this line here: https://github.com/twilio/twilio-video-app-react/blob/master/src/utils/useConnectionOptions/useConnectionOptions.ts#L38

You may see that the `roomType` variable is being used to determine whether or not to enable simulcast. The `roomType` variable is populated when the app receives the token from the token server. When using the Twilio Serverless functions, there is a `roomType` property on the response object (see [here](https://github.com/twilio-labs/plugin-rtc#success-responses)). But if you don't have the room type on your response object, then simulcast will default to enabled. 

I don't think you need to specify room type in your server responses. Instead you can just hardcode it in the app if you know what type of room you'll be using. For P2P and Go rooms, simulcast should be disabled:
`preferredVideoCodecs: [{ codec: 'VP8', simulcast: false }],`

And for Group and Small Group rooms, simulcast should be enabled:
`preferredVideoCodecs: [{ codec: 'VP8', simulcast: true }],`

3 - To set up Conversations in your Firebase Functions, you'll need to create a Twilio Client. This is the same kind of client that is returned by `context.getTwilioClient()`, like on [this line](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L65) for example. 

To create the same kind of client, you'll need to first install the twilio helper library:
`npm i -S twilio`

Then, in your Firebase Function, you can instantiate the client like this:
```
const Twilio = require('twilio');
const client = Twilio(twilioApiKeySID, twilioApiKeySecret, {
  accountSid: twilioAccountSid,
});
```

Then you can use this new `client` object to set up rooms and conversations in the same way that is done in the [token.js](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js) file in our Twilio token server.

I hope this helps with all your questions! Please feel free to let me know if you have any followup questions. I'm happy to reopen this issue to continue the discussion.

**Comment by ruggierom** [comment]
Thanks! This is great info & all makes sense.
