### ISSUE TITLE
Network quality level for main participant

### ISSUE THREAD

**Issue by coreymaher** [twilio/twilio-video-app-react#490]
**Question**
I was looking through the network quality level logic and noticed that the `NetworkQualityLevel` component only seems to be used in the `ParticipantInfo` component and not in the `MainParticipantInfo` component. Unless I'm missing something, this means you can't see the network quality level on the main participant. Is there a reason we can't, or wouldn't want to, display the network quality on the main participant?

**Additional context**
See https://github.com/twilio/twilio-video-app-react/blob/master/src/components/MainParticipantInfo/MainParticipantInfo.tsx#L111 vs https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ParticipantInfo/ParticipantInfo.tsx#L182

**Comment by timmydoza** [comment]
Hi @coreymaher - thanks for bringing this to our attention!

You are correct - there is no NetworkQualityLevel component for the Main Participant, and there isn't any reason why the Main Participant can't have one. So we added a ticket to our backlog to address this. It's a pretty easy fix, so I'd expect to see a pull request in a week or two to get this fixed. 

Thanks again!

**Comment by coreymaher** [comment]
Thanks for looking into this for me @timmydoza!

**Comment by olipyskoty** [comment]
Hi @coreymaher! This fix has been merged into the `master` branch. Please let us know if you have any questions or run into any issues! 🙂

**Comment by coreymaher** [comment]
Great, thanks @olipyskoty!
