### ISSUE TITLE
How to skip Name Input screen?

### ISSUE THREAD

**Issue by Gr8z** [twilio/twilio-video-app-react#505]
How can I skip this name selection screen, and just simply get the room id and the user name through URL params?

![image](https://user-images.githubusercontent.com/4633243/116805480-6c53e600-ab16-11eb-90cd-5b51ea67e8cd.png)

So the user can directly get into a call without inputting any details. Is this possible to do easily?

Thanks

**Comment by timmydoza** [comment]
Hey @Gr8z - thanks for the question!

It's not too hard to do this. I have a quick solution below. Note that this solution just takes the user to the device selection screen. It doesn't automatically connect them to the room. 

To automatically populate the Name and Room Name fields from query parameters, we can add this `useEffect` hook to the [preJoinScreens component](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/PreJoinScreens/PreJoinScreens.tsx#L25) at line 25:

```
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const name = params.get('name');
    const roomName = params.get('roomName');

    if (name && roomName) {
      setName(name);
      setRoomName(roomName);
      setStep(Steps.deviceSelectionStep);
    }
  }, []);
  ```
  
  That's it! It just grabs the name and roomName from query parameters, and sets them if they exist. Please let me know how this works out for you, and if you have any other questions!
