### ISSUE TITLE
session length

### ISSUE THREAD

**Issue by Mars-2030** [twilio/twilio-video-app-react#522]
**Question**
Ask a question about the video app here.
Hi,
after the session is ended I would like to know how long was the session is it 20 min, 30 min more or less. is there a function or API that get this value?

**Additional context**
Add any other context or screenshots about the your question here. The more detail, the better.

**Comment by Mars-2030** [comment]
in another word I want to get the room duration, how long the two participants were in a session?

**Comment by seancoleman2** [comment]
Hi @Mars-2030, thanks for the question!

You can retrieve the Room / Participant duration and other relevant info using the Video Log Analyzer API: https://www.twilio.com/docs/video/video-log-analyzer/video-log-analyzer-api 

You can also view this information from the Twilio Console: https://www.twilio.com/docs/video/video-log-analyzer

Let me know if you have any additional questions!
