### ISSUE TITLE
PHP token server

### ISSUE THREAD

**Issue by BenjaminKobjolke** [twilio/twilio-video-app-react#535]
**Question**
What is the correct way to setup a token server in php that also supports conversations?

My token server in php `looks` like this:
`<?php
require __DIR__ . '/Twilio/autoload.php';

use Twilio\Rest\Client;
use Twilio\Jwt\AccessToken;
use Twilio\Jwt\Grants\VideoGrant;
use Twilio\Jwt\Grants\ChatGrant;

$twilioAccountSid = 'XXX';
$twilioApiKey = 'XXX';
$twilioApiSecret = 'XXX';

$token = "XXX";
$twilio = new Client($twilioAccountSid, $token);

// A unique identifier for this user
$identity = "Random_" . rand(11111,99999);
$roomName = 'Test';

$chatServiceSid = 'ISXXX';

// Create access token
$token = new AccessToken(
    $twilioAccountSid, 
    $twilioApiKey, 
    $twilioApiSecret, 
    3600, 
    $identity
);

$videoGrant = new VideoGrant();
$videoGrant->setRoom($roomName);
$token->addGrant($videoGrant);

$chatGrant = new ChatGrant();
$chatGrant->setServiceSid($chatServiceSid);
$token->addGrant($chatGrant);

$returnArray = array();
$returnArray['token'] = $token->toJWT();
$returnArray['room_type'] = "group";
echo json_encode($returnArray);`

Video works but the conversations always fails with "There was a problem getting the Conversation associated with this room."
[https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ChatProvider/index.tsx#L75](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/ChatProvider/index.tsx#L75)

I also tried to replace getConversationByUniqueName with getConversationBySid and use the Sid I can see on the twilio console: [Screenshot](https://screens.xida.de/ShareX_O6sNbf5C4U.jpg)

What am I missing to create a valid token that also works for conversations in php?

**Comment by timmydoza** [comment]
Hey @BenjaminKobjolke - thanks for the question!

Thanks for sharing your code! There are a few extra steps that are needed, but they can be accomplished with the PHP Twilio helper library that you are already using. 

A good point of reference might be the token server that is used by this app. It's in javascript, but it has comments which should make it easy to follow along: https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js

But to sum it up, the steps required (with links to the corresponding lines in our JS token server) for the conversations feature are as follows:

1. [Find a video room by name](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L70) (or [create one if it doesn't exist](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L74))
2. [Find a conversation with a uniqueName equal to the room SID from step 1](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L92) (or [create a conversation using the room SID if it doesn't exist](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L99))
3. [Add a participant to the Conversation](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L114). `50433` errors (participant already exists) can be ignored here. This is to handle the case where a participant leaves a room and joins again. 

Also, when creating a Conversation, the `timersClosed` property should [be set](https://github.com/twilio-labs/plugin-rtc/blob/master/src/serverless/functions/token.js#L99) to `P1D`.  Here's [information](https://www.twilio.com/docs/conversations/states-timers?code-sample=code-create-timers-for-a-conversation&code-language=PHP&code-sdk-version=6.x) on how to set Conversations timers in PHP.  There is a limit of active conversations that you can have, to it's best to close these conversations automatically after 24 hours (this is the maximum length of a video room). 

I hope this helps! Please let me know if you have any other questions!

**Comment by BenjaminKobjolke** [comment]
Thanks for your detailed explanation.
I got it working.
Here is my code for anyone who has the same problem
`<?php
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Methods: *");
header("Access-Control-Allow-Headers: *");

// Require the bundled autoload file - the path may need to change
// based on where you downloaded and unzipped the SDK
require __DIR__ . '/Twilio/autoload.php';

use Twilio\Rest\Client;
use Twilio\Jwt\AccessToken;
use Twilio\Jwt\Grants\VideoGrant;
use Twilio\Jwt\Grants\ChatGrant;
use Twilio\TwiML\Video;

$token = "XXX";
$twilioAccountSid = 'XXX';
$twilioApiKey = 'XXX';
$twilioApiSecret = 'XXX';
// Required for IP messaging grant
$ipmServiceSid = 'XXX';

$roomName = 'Test';

$client = new Client($twilioAccountSid, $token);

$room = null;
try {
    $room = $client->video->rooms($roomName)->fetch();
} catch (Exception $e) {
    $options = array("UniqueName"=>$roomName, "Type"=>"group");
    $room = $client->video->rooms->create($options);
}

$conversationClient = $client->conversations->services($ipmServiceSid);
$conversation = null;
try {
    $conversation = $conversationClient->conversations($room->uniqueName)->fetch();
} catch (Exception $e) {

    try {
        $conversation = $conversationClient->conversations
            ->create([
                    "UniqueName" => $room->uniqueName
                ]
            );
    } catch (Exception $e) {
        echo $e;
        die;
    }
}

$conversation->update([
            "timersClosed" => "P1D"
        ]
    );

$identity = "Random_" . rand(11111,99999);

$participant = $conversation->participants
    ->create([
            "Identity" => $identity
        ]
    );


// Create access token
$accessToken = new AccessToken(
    $twilioAccountSid, 
    $twilioApiKey, 
    $twilioApiSecret, 
    3600, 
    $identity
);

// Create Video grant
$videoGrant = new VideoGrant();
$videoGrant->setRoom($roomName);
// Add grant to token
$accessToken->addGrant($videoGrant);

// Create IP Messaging grant
$ipmGrant = new ChatGrant();
$ipmGrant->setServiceSid($ipmServiceSid);
$accessToken->addGrant($ipmGrant);



// render token to string
$returnArray = array();
$returnArray['token'] = $accessToken->toJWT();
$returnArray['conversation'] = $conversation->sid;
$returnArray['room_type'] = "group";
echo json_encode($returnArray);`

**Comment by timmydoza** [comment]
Thanks @BenjaminKobjolke - glad it's working for you!!
