### ISSUE TITLE
New release for Firefox fix?

### ISSUE THREAD

**Issue by coreymaher** [twilio/twilio-video-app-react#537]
**Question**
It looks like a Firefox bug that prevents capturing input from the microphone has found its way into v0.3.2 and v0.4.0.
Fortunately, it looks like you've already fixed this bug: https://github.com/twilio/twilio-video-app-react/pull/526
Are there any plans to release a new version soon that contains this fix?

**Additional context**
N/A

**Comment by olipyskoty** [comment]
Hi @coreymaher! We just published a new [release](https://github.com/twilio/twilio-video-app-react/releases/tag/v0.4.1) that contains #526 along with some other bug fixes 🎉. Please let us know if you have any questions or run into any issues!

**Comment by coreymaher** [comment]
That is great news, thanks!
