### ISSUE TITLE
Is there any ETA for custom background feature?

### ISSUE THREAD

**Issue by SanjayBikhchandani** [twilio/twilio-video-app-react#542]
I've already posted this question over here:
https://github.com/twilio/twilio-video-app-react/issues/453

But not sure how to implement it with VideoProcessor API.
https://github.com/twilio/twilio-video.js/issues/1413

Is anyone have implemented the custom background feature or can someone pls guide me on how to implement it?

**Comment by timmydoza** [comment]
Hi @SanjayBikhchandani - thanks for the question!

We don't have a set release date for this feature, but it is in active development. We recently released the video-processor library, which can be used to add virtual backgrounds to video tracks: https://www.twilio.com/blog/introducing-virtual-backgrounds-browser-based-video-applications

Soon, we will add a user interface to this app that will let users choose a virtual background. Stay tuned!

**Comment by timmydoza** [comment]
Hi @SanjayBikhchandani - just wanted to let you know that our virtual background feature has been released in version 0.5.0:
https://github.com/twilio/twilio-video-app-react/releases/tag/v0.5.0
Enjoy! Please let us know if you have any questions about it.
