### ISSUE TITLE
Feature request: stand-alone chat widget

### ISSUE THREAD

**Issue by radukg** [twilio/twilio-video-app-react#551]
Is it possible to raise a widget request here? As I see there is already chat functionality (via Conversation API) exists within video app, but I can’t find standalone chat widget (the one which use Conversation API and not  Programmable Chat API). We are looking to have few major components there: chat history with ability to return to previous conversations (like in MS Teams), online/offline indicators, smiles/emojis, media upload and chat itself. If this is not right place to raise this request - please share where it should go (Twilio Support asked me to raise it here)

**Comment by seancoleman2** [comment]
Hi @radukg - thanks for the feature request!

If you haven't discovered it yet, here is a demo application from the Conversations team: 

- Tutorial here: [https://www.twilio.com/docs/conversations/quickstart#configure-the-conversations-demo-application-using-codesandboxio](https://www.twilio.com/docs/conversations/quickstart#configure-the-conversations-demo-application-using-codesandboxio)
- Code sandbox here: [https://codesandbox.io/s/github/TwilioDevEd/conversations-demo](https://codesandbox.io/s/github/TwilioDevEd/conversations-demo)

Also if you have a Programmable Chat widget in mind that meets your needs, the migration is fairly straightforward as the products are very similar. Here is a guide for that: [https://www.twilio.com/docs/conversations/migrating-chat-conversations](https://www.twilio.com/docs/conversations/migrating-chat-conversations). 

Hopefully that helps and please let me know if you have any other questions!
