### ISSUE TITLE
syntax error import './bootstrap-globals';

### ISSUE THREAD

**Issue by Mars-2030** [twilio/twilio-video-app-react#553]
**Describe the bug**
 I am receiving this error ..
although the only thing I changed is the .env

```
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
/home/videoa/public_html/video/server/index.ts:1
import './bootstrap-globals';
^^^^^^
```

**To Reproduce**
1. npm install
2. npm start
3. See error in the logs
4.Note: I am using CPanle nodejs installation

the file bootstrap-globals is found under the folder server

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

 - Node.js version: [14]

**Additional context**

**Comment by olipyskoty** [comment]
Hi @Mars-2030, thank you for the issue!

We are sorry that you are having trouble starting the application. I tried reproducing your issue by following the steps below, and unfortunately was unable to do so:

1.  entered `git clone git@github.com:twilio/twilio-video-app-react.git` in the terminal
2. created a new `.env` using the variables according to the `.env.example` file
3. ran `npm i` in the terminal
4. ran `npm start` in the terminal

It is possible that the Cpanel Node.js installation is causing the issue. We don't currently test or use Cpanel, so it is difficult for us to know for sure. 

I am curious to see if you run into the same error by following the steps listed above or in the [README.md](https://github.com/twilio/twilio-video-app-react#readme) (without using Cpanel). Do you mind giving that a try and get back to us with the results? Thanks and have a good weekend 🎉

**Comment by Mars-2030** [comment]
Hi
I think the issue is related to cpanel nodejs
It is working fine on the local machine

**Comment by Mars-2030** [comment]
can anyone help me on this ,, it is installed on cpanel and this is the issue I am receiving
