### ISSUE TITLE
How to fix this type error for video processor?

### ISSUE THREAD

**Issue by SanjayBikhchandani** [twilio/twilio-video-app-react#555]
I'm getting this type error while adding a processor to video track

![Screenshot 2021-07-20 160658](https://user-images.githubusercontent.com/63910275/126312333-75610d00-af0c-4902-ad76-3e5f68a9d9cd.png)
![error](https://user-images.githubusercontent.com/63910275/126312336-e6889b0b-2a5c-4cdc-a529-32f9f9d1a384.png)

I've trying out VIDEO-5734 branch

@gabriel-jt can you pls help me with this?

**Comment by charliesantos** [comment]
Hey @SanjayBikhchandani thanks for trying out the branch! We're still in the process of implementing this in the react app and working through the issues. Please check back once this feature is merged in to the master branch.
