### ISSUE TITLE
How to show real name instead of identity for participants?

### ISSUE THREAD

**Issue by baj84** [twilio/twilio-video-app-react#588]
Hi,

My video app is used by many different users, and people may have the same name. So I use the user_id as their identity to keep things consistent and to ensure Twilio sees them as the same user each session (helps with keeping the costs down).

My question is, how do I attach a real name to a participant so that I can show this in the UI and chat? Everywhere in the app is referring to the `participant.identity` - is it possible to change this?

Would my best solution be storing it in local storage and retrieving the data myself? Or is there a better way?

Thanks!

**Comment by mattrothstein** [comment]
I am really interested in resolving a similar issue. And wonder how difficult it would be to implement a `display_name` to go along with the `participant_identity`.  

In fact I recently noticed that the `participant_identity` as documented  [here](https://www.twilio.com/docs/video/api/participants) should not contain PII. This creates a bit of an issue for me as a person's name is considered to be PII. Is there a more appropriate place to store the name?

**Comment by timmydoza** [comment]
Hey @baj84 and @mattrothstein - thanks for the question!

Unfortunately, the only place to store any information about a participant is in the `participant.identity` string. At the moment, there is no other place to store metadata about a participant. There is [an issue](https://github.com/twilio/twilio-video.js/issues/864) in our Twilio Video SDK repo that discusses the idea of storing metadata for a participant. I'd encourage you both to check out that thread, and leave a comment in support of the idea if it sounds good to you. This helps us track community interest in new features. 

To answer your question @baj84 - even with the limitation mentioned above, it is still possible to handle cases where there are multiple users with the same name. What you have to do is add 1) a separator (something like `'###'`, and 2) a random string - to the end of each participant's identity. So if two people named "John Smith" joined a room, their identities could look like this:
`John Smith###hg013bk4`
`John Smith###198vojs3`

This way, each identity is unique, but you can still extract the participant's name to display. So in the app, when you'd like to display the user's real name, you can use some regex to get rid of the separator and the random string:
```js
console.log(participant.identity); // "John Smith###hg013bk4"
const displayName = participant.identity.match(/^([\w|\ ]*)###[\w\d]*/)[1];
console.log(displayName); // "John Smith"
```

It's a little hacky, but it works. There are some other ideas discussed in the [SDK issue](https://github.com/twilio/twilio-video.js/issues/864), like storing JSON in `participant.identity`. Do note that the participant's identity has a limit of 128 characters. 

Hope this helps! Please let me know if you have any other questions.

**Comment by baj84** [comment]
Thanks for the reply @timmydoza - as my app requires more data than just the user's name and doesn't change, I decided to simply store the user data using local storage, using the room name as part of localstorage key so that it avoids any potential conflicts if a user connects to multiple rooms.

Then on the components I needed to update I would just do something like this:

```
  const [bookingData, setBookingData] = React.useState<any>(null);
  React.useEffect(() => {
    const bookingId = window.localStorage.getItem('booking_id');
    const videoData = window.localStorage.getItem(`video_service_data_${bookingId}`);

    if (videoData) {
      setBookingData(JSON.parse(videoData));
    }
  }, []);
```

It's hacky, but it's working fine.
