### ISSUE TITLE
Changing room mode doesn't make any difference in video session UI

### ISSUE THREAD

**Issue by zcurchin** [twilio/twilio-video-app-react#598]
When you change room type to 'Grid', 'Presentation', or 'Collaboration' nothing is changed in UI during the video session. The dominant speaker is always in full screen and others are in smaller containers. Do we need to implement that functionality ourselves or we are missing something?

**Comment by timmydoza** [comment]
Hi @zcurchin - thanks for the question!

No, you aren't missing anything. The UI doesn't change when you change to 'Grid' or 'Collaboration'. This setting simply changes the [bandwidth profile mode](https://www.twilio.com/docs/video/tutorials/using-bandwidth-profile-api#understanding-mode) in the connection options. So it's possible that you may notice some differences in quality when you change that setting, but the UI stays the same. 

At this moment, it is not possible to change the bandwidth profile mode while you are in a room. This means that we can't build an experience where users can switch between a grid UI or a collaboration UI on the fly. We are working on this though, and we hope to soon showcase this new functionality in this app. Star tuned!
