### ISSUE TITLE
Landscape/Portrait issues in iOS Chrome

### ISSUE THREAD

**Issue by LucaProvencal** [twilio/twilio-video-app-react#604]
**Describe the bug**
On Chrome on iOS, when screen is rotated from landscape back to portrait, display does not fill full area

**To Reproduce**
1. Using Chrome on iOS, join a Telehealth room
2. Hold device in landscape orientation
3. Rotate back to portrait orientation
4. Display of Room does not fill full area (see image)

**Expected behavior**
The display should fill the entire area, just like it does when the room is joined in portrait mode.

**Screenshots**
I've tested on 2 devices, both with Chrome 94.0.4606.52 or higher

**iPhone 11:** 
![IMG_0678](https://user-images.githubusercontent.com/25271943/136403929-bbb03f01-8cd4-4418-807c-65af8f13874a.jpg)

**iPhone 7:**
![IMG_0680](https://user-images.githubusercontent.com/25271943/136403931-88039932-f952-4ff0-a29c-c25aaeae6244.jpg)

**Environment (please complete the following information):**
 - iOS 14.7.1 (iPhone 7); iOS 14.8 (iPhone 11)
 - Chrome for iOS 94.0.4606
 - App Version: 0.6.0
 - SDK Version: 2.17.1
 - Node.js version: 15.14.0
 
 - User Agent (iPhone 7): Mozilla/5.0 (iPhone; CPU iPhone OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/94.0.4606.52 Mobile/15E148 Safari/604.1
 - User Agent (iPhone 11): Mozilla/5.0 (iPhone; CPU iPhone OS 14_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/94.0.4606.76 Mobile/15E148 Safari/604.1

**Additional context**
I am investigating a fix, ~~might be related to MUI breakpoints~~ it is related to `useHeight` hook, but wanted to make you aware as well

**Comment by timmydoza** [comment]
Hi @LucaProvencal - thanks for the detailed issue (and PR)!

I have seen this one in the mobile version of the app. Thanks for submitting the PR with a fix for this - we really appreciate it! 

Just wanted to let you know that we've got an eye on this one and we'll take a look when we find a moment. 

Thanks again.

**Comment by mauro-oto** [comment]
@timmydoza any updates on this one? Thanks!

**Comment by LucaProvencal** [comment]
Hi @timmydoza, will close this one since I assume it won't be worked on.
