### ISSUE TITLE
How would I add custom Twilio Functions to this app?

### ISSUE THREAD

**Issue by CodeLPham** [twilio/twilio-video-app-react#609]
I was wondering how I would add my own Twilio functions to this app.  I created a `/functions` folder and have some function code there.  However I was wondering how I would deploy the app with the new functions in the same service.  

running `twilio deploy:twilio-cli` deploys the video app with the `/token` and `/recordingrules` function.  I have to also run 
`twilio serverless:deploy` to deploy my custom functions in a separate service.  Is there a way to add my functions to the video application in a single service and deployment?

**Comment by timmydoza** [comment]
Hi @CodeLPham - thanks for the question!

One thing you could do, is to clone the [plugin-rtc](https://github.com/twilio-labs/plugin-rtc) repo. This is the repo that we made which powers the twilio-cli plugin that deploys these apps. 

Once you clone the repo and install dependencies, you can install it as a twilio-cli plugin from the local directory. [This section](https://github.com/twilio-labs/plugin-rtc#install-the-plugin-for-local-development) of the readme explains how to do that. 

Once that's done, you can add more functions to this [folder](https://github.com/twilio-labs/plugin-rtc/tree/master/src/serverless/functions) and they will be uploaded to Twilio Serverless the next time you deploy the app!

I hope this helps. Another alternative is to use the Functions Editor from the Twilio Console to add and edit new functions (you will see a link to this after you deploy your app or run `twilio rtc:apps:video:view`). The downside to this is that the functions won't be saved anywhere if you tear down the deployment. 

Good luck! Please let me know if you have any other questions!
