### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by jinman** [twilio/twilio-video-app-react#626]
**Question**
I am wondering whether we can use this to create a PWA. Has anyone tried this and does it work on Mobile phone?

**Additional context**
PWA is cool way to build Web app that can work offline, get push notifications etc so we dont have the need to build native apps.  We can also compile them into APK using TWA. Hence I was wondering whether this repo has worked with PWA (service worker) etc?

**Comment by timmydoza** [comment]
Hey @jinman - thanks for the question!

That's a great question! I'm not sure if this app can be used as a PWA - nobody here has ever tried 🙂. This app is designed to perform well in supported mobile browsers (Firefox and Chrome on Android, and Safari and Chrome on iOS), so it's quite possible that it would perform well as a PWA. I think it's worth a shot! Unfortunately we don't have the bandwidth to test this one out ourselves, but please let me know if you have any more questions about this!
