### ISSUE TITLE
Emoji feature and host meeting feature

### ISSUE THREAD

**Issue by 0211ms** [twilio/twilio-video-app-react#628]
Hello @timmydoza @kwhinnery @rrecaredo @mplacona @jesperfj @mattmakai 
**Question 1**
>>Is ther any Emoji feature available in your react video app. while we are chating between video call.

**Question 2**
>>If I am a teacher(host) and I create one meeting room and I share this link with my student so in your react video app there is any feature if teacher(host) leave the room at a same time all joined student also leave from this particular meeting?

**Comment by 0211ms** [comment]
Hello,
Please revert on priority base. Its little bit urgent.

**Comment by yashrojesara** [comment]
@0211ms 

1. I don't think It's available in this demo app but you can use this https://www.npmjs.com/package/emoji-mart 3rd party package to add emoji feature in your app

2. To End Meeting For All, you can use this API https://www.twilio.com/docs/video/api/rooms-resource?code-sample=code-complete-a-room&code-language=Node.js&code-sdk-version=3.x. You just have to call this API when the host leaves from meeting and mark the status as complete with this API

**Comment by 0211ms** [comment]
@yashrojesara 

My application is in .net core and I am using a videoreactapp for only meeting features. If possible can you help me more?

Thanks.

**Comment by yashrojesara** [comment]
@0211ms 

Can you please elaborate on what issue you're facing?
Or you can connect with me on my email: yashsoni9861@gmail.com

**Comment by 0211ms** [comment]
Hello,
I alredy mail you on yashsoni9861@gmail.com

**Comment by timmydoza** [comment]
Hi @0211ms - thanks for the questions!

Question 1:

It's very easy to send an emoji over Twilio Conversations. Emoji's are strings, so it's as easy as sending any other string. Users can type emojis right into the chat window and send them to the chat. [Here's some info](https://www.google.com/search?q=type+emojis+on+mac) on how to type emojis in MacOS.  

If you want users to be able to click on an emoji button in the app to send a specific emoji, this is an example of how you could do it inside `src/components/ChatWindow/ChatInput/ChatInput.tsx`:

First, make a function that can be called when a button is clicked:
```
  const handleSendSmiley = () => {
    conversation.sendMessage('😀');
  };
```
You can add an emoji right into the code!

Then, later you can add a button to the page that will call this function:
```
<button onClick={handleSendSmiley}>😀</button>
```
You can put the emoji in the button just as if it's text.

There are lots of different things that you could do with emojis - it all depends on what specific feature you're trying to build.

Question 2:

The app currently does not have a feature like the one you describe. This is something you would have to build. 

For this to work, your app will need a way to tell the difference between a teacher and a student. It would be helpful if you could tell the difference between a student and a teacher just by looking at their identity. For instance, a teacher's identity could be `Alice---teacher`, and a student's identity could be `Bob---student`.

Once you have a way to identify a teacher by their identity, then we can create a [status callback](https://www.twilio.com/docs/video/api/status-callbacks) for the room. This callback will be called for many different room events. For your use case, your status callback would wait until it sees the `participant-disconnected` event. If your callback receives this event, then it would check to see if the `ParticipantIdentity` is a teacher's identity, and it it is, it will [end the room](https://www.twilio.com/docs/video/api/rooms-resource?code-sample=code-complete-a-room&code-language=C%23&code-sdk-version=5.x) using the [Rooms API](https://www.twilio.com/docs/video/api/rooms-resource). 

I think that would be a good direction to go in. It may be a little tricky, but it's certainly possible to build that feature using Twilio Video.

Please let me know if you have any other questions!
