### ISSUE TITLE
Connection error (53001) when connecting with an iPhone to Peer-to-Peer room

### ISSUE THREAD

**Issue by Daffeldoff** [twilio/twilio-video-app-react#632]
Hello!

When I deploy this application in the default setting (group room type) everything works fine.
If i deploy it in peer-to-peer setting (npm run deploy:twilio-cli -- --override --room-type peer-to-peer) I am unable to connect to a call ("Connection Lost: Reconnecting to room..." snackbar is shown first, after a few seconds it disconnects from the room and Error 53001 is shown). On the other device you see that someone joined the call (the MainParticipant video changes to black), the same snackbar appears ("Connection Lost: Reconnecting to room...") and after a few seconds it disconnects with the error Code 53405 "Media connection failed or Media activity ceased".

To recreate the error:

- deploy the app with peer-to-peer room_type
- use two devices (one of which is an iPhone) that are not in the same wifi
- create a "room" with the other device (not the iPhone)
- join the call with the iPhone

Do you have an idea why this happens? Can you recreate the error?

Cheers, David

**Comment by timmydoza** [comment]
Hi @Daffeldoff - thanks for the issue!

We went through your steps a few times, but unfortunately we were not able to recreate the error that you are seeing. 

I'd guess that there may be some network issues that are causing this issue. Are you seeing this error message in 100% of attempts, or just a few? Also, are the network conditions good on both wifi networks that you are using? Do speed tests give you good results for these networks?

I'm not sure what to suggest here, but it may be helpful if you could provide additional details. What version of the app are you using? What browser and browser versions are you using? iOS version? Can you provide any Room Sids where you see this issue occurring?

**Comment by Daffeldoff** [comment]
Hi @timmydoza - thank you for looking into it!

I did not have the newest version, but the changes in the newer versions don't look like would effect this. 
Nevertheless I will update to the newest version (which I should have done before writing here) and try again with different scenarios. I will get back to you afterwards with more detailed information about devices and software versions.

**Comment by Daffeldoff** [comment]
Under the described conditions I get this error in 100% of attempts. 
The internet connection is good on both wifi networks (speedtests are good and calls with MS Teams are working fine).
I tested it on:
- App version: 0.6.2
- 1. device: MacOS (Version 12.1) with Chrome (Version 97.0.4692.99) or Safari (Version 15.2)
- 2. device: iPhones both with iOS version 15.2.1

This morning I tested it once with each of the iPhones above. The SIDs are:
- RM080b02234208beba49c00b21b4843d1f: mac user "Daffel"/"Da" joined first, iPhone user "Ste"/"S" joined second. We saw that the other connected but no audio and video got through, then the error messages appeared ("connection lost", "reconnecting"...). 
- RM2f342ca9e0b45786cf933ead63d106e6: first the mac user "Daffel" joined first and the iPhone use "Jürgen" joined second. The usual problem happened. After that the iPhone user "Jimmy" (the same as "Jürgen") joined first and "Daffel" second. Everything worked fine here. 

I could also give you the url with passcode in a private message (email?) if you want.

**Comment by Daffeldoff** [comment]
Twilio-Video Version 2.20.1 seems to have fixed the problem.

_Fixed a bug that was introduced in 2.19.0 where the published LocalVideoTracks of Participants on older iOS versions 14.5 and below did not encode and transmit media. (VIDEO-8770)_
