### ISSUE TITLE
Error while clicking on 'join roon

### ISSUE THREAD

**Issue by deekshaa8** [twilio/twilio-video-app-react#665]
Hi,

After entering the username and room name , then clicking on join room button creating this error
![image](https://user-images.githubusercontent.com/90396390/161801028-292db187-d8e6-4ed4-94da-9d664b9af275.png)
![Capture](https://user-images.githubusercontent.com/90396390/161801141-4c2e1e2b-7b41-4c20-a353-342f9b0410d4.PNG)

**Comment by timmydoza** [comment]
Hi @deekshaa8 thanks for the issue!

I think that this error means that there is no token server that is able to serve a video access token to the app. Unfortunately, without more information from you, I'm not able to know what the problem might be. Can you please create a new issue and fill the bug report template in full? Some information that we would be interested in is: how did you run the app? Is the app deployed anywhere? Are you seeing any error messages in your terminal or browser console? What versions of Node and NPM are you running? What browser are you using? Did you make any changes to the code?

The more information that you can provide about this problem - the better we will be able to help you. Thanks for your understanding!
