### ISSUE TITLE
How to increase video recording quality.

### ISSUE THREAD

**Issue by 0211ms** [twilio/twilio-video-app-react#679]
Hello @timmydoza  @yashrojesara
How to increase video recording quality while we our recording is start in meeting.

Thanks.

**Comment by timmydoza** [comment]
Hi @0211ms - thanks for the question!

The quality of a recording cannot be set before or during a recording. A recording is just a dump of the real-time media that the participants are sending to a Group Room. So if the recording quality appears to be low, a likely cause is that the network connection is poor for the participants in the room.

What's the quality like for the participants in the room? In this app, each participant has an indicator for their network quality. If you see that the network quality of the participants is low, then this could be a good indicator that the recording quality will be low too. 

If you're finding that network quality is low, it may be good to select a media region that is geographically close to the participants in the room. The further away participants are from the media region, the worse the quality will be. There's more information about media regions here: https://www.twilio.com/docs/video/tutorials/video-regions-and-global-low-latency#geolocation-and-qualit
