### ISSUE TITLE
Reference Implementations

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video-app-react#725]
**What is the feature that you would like to see in the app? Please describe.**
It would be nice if Twilio kept a list of other open source projects that are built from this repo. I'm thinking of something similar to https://github.com/tmm/wagmi/discussions/201. While developing, I've frequently wanted to see other examples of people using the twilio SDKs but they have been hard to find. 

**Is your feature request related to a problem? Please describe.**
Hard to find complex examples of things. Lots of re-inventing the wheel. 

**Describe alternatives you've considered**
Github code search, but frequently yield good results 

**Additional context**
We created an example with nextjs support https://github.com/alwaysbegrowing/twilio-video-app-react-nextjs & are working on a virtual co-working app https://github.com/alwaysbegrowing/fokus

**Comment by seancoleman2** [comment]
Hey @RusseII - this is a great idea! I started a discussion here: https://github.com/twilio/twilio-video-app-react/discussions/739 

Want to get the ball rolling and add your examples to the discussion? Thanks!
