### ISSUE TITLE
General question about getting started with Twilio Video in React

### ISSUE THREAD

**Issue by jtweaver** [twilio/twilio-video-app-react#726]
This seems to be the only resource I can find for building out Twilio Video in React. It also seems like a lot of assumptions were made in this example application that make it impossible to tell how to just add Twilio Programmable Video into an existing React app.

This app includes firebase... Are you saying we need firebase in order to use Twilio Programmable Video?

Why not just publish an npm package with all of the hooks and a few of the base components in this app for developers to consume in their own apps?

The Twilio marketing material for this says "Launch your own video app with text-based chat in minutes with the updated Twilio Video Open Source ReactJS application". It should say "Launch this demo app we built in minutes and then spend weeks trying to figure out how to get it to work in your own application".

Am I missing something? Where is the documentation on just the core components needed to build out video chat, without an entire app built around it?

**Comment by Geczy** [comment]
aren't you looking for https://github.com/twilio/twilio-video.js/ ?

**Comment by seancoleman2** [comment]
Hi @jtweaver - thanks for the question! This repo demonstrates a fully-featured app focused on the group collaboration, so it might not fit your use case perfectly or be the best place to start if you are just getting started with Twilio Video. 

We do plan to add getting started documentation for React (you aren't the first person with this type of feedback), but a good starting spot is the [JavaScript Getting Started docs](https://www.twilio.com/docs/video/javascript-getting-started) and then we have a number of blog posts for building with React: 
- [Build a Custom Video Chat App with React and Twilio Programmable Video](https://www.twilio.com/blog/build-a-custom-video-chat-app-with-react-and-twilio-programmable-video) 
- [Build a Video Chat with React Hooks](https://www.twilio.com/blog/video-chat-react-hooks)
- [Build a Video Application with Breakout Rooms Using Twilio Programmable Video, React, TypeScript, and Express — Part 1](https://www.twilio.com/blog/build-video-app-breakout-rooms-react-typescript-express-part-1)
- [Build a Video Application with Breakout Rooms Using Twilio Programmable Video, React, TypeScript, and Express — Part 2](https://www.twilio.com/blog/build-video-app-breakout-rooms-react-typescript-express-part-2)
- ... might be more. 

Per Firebase, you don't have to use it (see [here](https://github.com/twilio/twilio-video-app-react#google-authentication-using-firebase-optional) in the readme). Including that functionality serves as an example for adding user authentication, and if someone is already using/wants to use Firebase... even better. 

For your point on the NPM package, we are looking for some early feedback from the community on an ongoing initiative in this area. If you (or anyone reading this) is interested in helping us define this, send me an email at scoleman at twilio.com.

Thanks, and let me know if you have any other questions!
