### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by bhodler** [twilio/twilio-video-app-react#736]
Hi, I installed the twilio CLI via "npm install -g twilio-cli" but when i tried to login using "twilio login", it says command not found

**Comment by sarahcstringer** [comment]
Hi @bhodler, did you try the troubleshooting suggestions recommended in the README? https://github.com/twilio/twilio-video-app-react#login-to-the-twilio-cli

**Comment by timmydoza** [comment]
Hi @bhodler - thanks for the question. 

Unfortunately, without more information it is going to be difficult to help out. When troubleshooting the installation of the Twilio CLI, it's very helpful to know what operating system you are installing it on, what steps you have tried, what the console output was, and what versions of node and npm you are using. 

Also, we have a Github repo specifically for the Twilio CLI here: https://github.com/twilio/twilio-cli

I'd recommend that you create a new issue on that repository, being sure to leave as much information that you can. 

In the meantime, I searched through the issues in that repo and found a few that look similar to the "command not found" problem that you are facing. Maybe you can find some help in these existing issues:

https://github.com/twilio/twilio-cli/issues/350
https://github.com/twilio/twilio-cli/issues/258
https://github.com/twilio/twilio-cli/issues/239
