### ISSUE TITLE
Dominant speaker audio issue on gallery view second page

### ISSUE THREAD

**Issue by arunkb2795** [twilio/twilio-video-app-react#772]
Hi team,
I had a query regarding participant track control in a room.
Our implementation includes a gallery view which is split into pages limited by a maximum video per page (e.g. :10 video per page).
Let's take an example where the dominant speaker is in the first gallery page. When we tested with another participant who is in the second gallery page, the dominant speaker in the first page was not audible for this participant.

**Environment (please complete the following information):**
 - OS: [Windows]
 - Browser: [ Chrome 80]

**Comment by mcarrerasm** [comment]
Hi @arunkb2795 thanks for reaching out!

Unfortunately, I am unable to reproduce the issue. 

I can see that you mentioned that you were using Chrome v80? Could you please try with latest Chrome version? https://chromereleases.googleblog.com/

If you can reproduce the issue on latest Chrome version, Could you please try with [React App ](https://github.com/twilio/twilio-video-app-react) and share the exact steps to reproduce the issue?

Thank you!

**Comment by seancoleman2** [comment]
@arunkb2795 going to close this one due to inactivity, but please let us know if you are still having issues and we will reopen. Thanks!
