### ISSUE TITLE
JSDK-2592 - sdk implement event

### ISSUE THREAD

**Issue by kiliancabrera** [twilio/twilio-video-app-react#775]
**Question**
is this event implemented?

  // TODO: remove when SDK implements this event. See: https://issues.corp.twilio.com/browse/JSDK-2592
  localParticipant?.emit('trackUnpublished', localTrackPublication);

**Additional context**
on useLocalVideoToggle.tsx

**Comment by seancoleman2** [comment]
Hi @kiliancabrera, thanks for the question! No, this event is not implemented. From an SDK user's perspective, you can consider the Track as unpublished as soon as `LocalParticipant.unpublishTrack()` is called.

We are monitoring community interest for this [here](https://github.com/twilio/twilio-video.js/issues/1007). Please do upvote if you would like to see this in the future as that will help us prioritize.

I will close this for now, but let me know if you have any other questions and I will reopen!
