### ISSUE TITLE
Unable to see the screen which is shared by the presenter in the presenter view

### ISSUE THREAD

**Issue by Benitosam** [twilio/twilio-video-app-react#784]
**Question**
Would it be possible to see the screen shared by the presenter in the presenter view?

**Additional context**
All the persons can able to see the shared screen which is shared by someone in the conference. but the person who shared the screen, they can't see their screen on their view.
Is this the feature in Twilio video app or it's a known bug that i identified.

Please refer the attached presenter & participant views for more clarity in this scenario.

Presenter view
![Screenshot from 2023-01-24 10-37-27](https://user-images.githubusercontent.com/96238719/214216333-18c04f73-0238-49c6-b688-1fae665ba6dd.png)

Participant view
![Screenshot from 2023-01-24 10-37-40](https://user-images.githubusercontent.com/96238719/214216358-08cf7cf6-1860-4956-bc1e-2e3319ea782d.png)

**Comment by manjeshbhargav** [comment]
Hi @Benitosam ,

Here are some of the [changes](https://github.com/twilio/twilio-video-app-react/compare/show-local-screen-share) you can try out in order for the presenter to see the screen that they are sharing. Please let me now if this works for you. I will close this ticket as I have answered your question, but we can continue the conversation here.

**Comment by Benitosam** [comment]
Thank you Manjesh, I will check it out.
