### ISSUE TITLE
How to create a link to share other people to connect to my videocall

### ISSUE THREAD

**Issue by hovalle** [twilio/twilio-video-app-react#794]
Hi I have a question, what's the right Approach to generate a sharable link to other people and how to avoid the passcode to be generated every 7 days? I need that link to redirect the invited user to the form in which they add the name and the room name.

**Comment by manjeshbhargav** [comment]
@hovalle ,

You can just remove the passcode verification system from your application. But, for a production application, I do recommend some sort of oauth authentication mechanism.
