### ISSUE TITLE
WhiteBoard Feature

### ISSUE THREAD

**Issue by amrelshehaly** [twilio/twilio-video-app-react#800]
Can Someone help, I need to add a whiteboard feature in the video chat.

I noticed that the whiteboard featured considered a DataTrack. However, I can't figure out from where to start implementing the whiteboard feature 

Thank you in advance.

**Comment by manjeshbhargav** [comment]
@amrelshehaly ,

We have a [whiteboard demo app](https://github.com/twilio/draw-with-twilio) that uses DataTracks. Hope this helps.

**Comment by amrelshehaly** [comment]
Yes this will definitely be useful for our project.

Thank you for your help.

Sincerely,
Amr shehaly
