### ISSUE TITLE
document and present Capability

### ISSUE THREAD

**Issue by Denesh11** [twilio/twilio-video-app-react#803]
**Question**
Is there any Option for upload a document and present it on this lti app?

We need this basic feature for the live chat. If it was not means we have to implement this feature, to implement this please answer the blow questions to help us. Thanks

Could you please help me to how i have to implement this? 
Where I have to implement and record this things and all?

**Comment by manjeshbhargav** [comment]
Hi @Denesh11 ,

There are many tutorials online that demonstrate how to upload a document. Right now, there are no plans to implement this on our end.
